export const Data = [
  {
    id: "1",
    title: "Introduction to Banking",
    drive: "https://drive.google.com/file/d/1yJOmbBYUvJvaamkP_-1AqdAm9zmU2Cow",
    link: "/Halaman/page/5-ternak-uang/20/1",
    category: "Stock and Finance",
  },
  {
    id: "2",
    title: "Mengapa Peran Bank Sangat Fundamental",
    drive: "https://drive.google.com/file/d/1yvS9JMB0y28Z9LnphhKOJjGQAxPU4C66",
    link: "/Halaman/page/5-ternak-uang/20/2",
    category: "Stock and Finance",
  },
  {
    id: "3",
    title: "Perbankan Industri yang Paling Berisiko",
    drive: "https://drive.google.com/file/d/1kKj_SaYZKMWD5FoECefWn7pJ_Xw2MT4S",
    link: "/Halaman/page/5-ternak-uang/20/3",
    category: "Stock and Finance",
  },
  {
    id: "4",
    title: "Kenapa Bank Berbeda dengan Industri Lainnya",
    drive: "https://drive.google.com/file/d/1yyTpVWDff7y2mh0YajSJHXkRivIlxreu",
    link: "/Halaman/page/5-ternak-uang/20/4",
    category: "Stock and Finance",
  },
  {
    id: "5",
    title: "Capital Adequacy",
    drive: "https://drive.google.com/file/d/1WTzvZuiXQj2JB3flN1ByqTUILkv_QAkv",
    link: "/Halaman/page/5-ternak-uang/20/5",
    category: "Stock and Finance",
  },
  {
    id: "6",
    title: "Asset Quality",
    drive: "https://drive.google.com/file/d/1vIz31XMqvzSOua1kTSILv01K1d6NxkNK",
    link: "/Halaman/page/5-ternak-uang/20/6",
    category: "Stock and Finance",
  },
  {
    id: "7",
    title: "Management Efficiency and Earnings",
    drive: "https://drive.google.com/file/d/13Pc62dO1I8Jrv18iUvr5TdEqVLCiCTV9",
    link: "/Halaman/page/5-ternak-uang/20/7",
    category: "Stock and Finance",
  },
  {
    id: "8",
    title: "Liquidity",
    drive: "https://drive.google.com/file/d/1UMpIr4oHi_AFzXdHvT0tIq_t9dyQv6rS",
    link: "/Halaman/page/5-ternak-uang/20/8",
    category: "Stock and Finance",
  },
  {
    id: "9",
    title: "Membandingkan Kinerja Keuangan 4 Bank Buku IV",
    drive: "https://drive.google.com/file/d/1U8sKhzsTSJnVoEi_BnbL166H7w6BoJES",
    link: "/Halaman/page/5-ternak-uang/20/9",
    category: "Stock and Finance",
  },
  {
    id: "10",
    title: "Ini Dia Metode yang Cocok Untuk Valuasi Bank",
    drive: "https://drive.google.com/file/d/1imyW7LEjImdsEjs2_2BmiPDbsnYeYS2u",
    link: "/Halaman/page/5-ternak-uang/20/10",
    category: "Stock and Finance",
  },
  {
    id: "11",
    title: "Praktik Relative Valuation Bank",
    drive: "https://drive.google.com/file/d/1KCQnMtOCfLrPe_W4vaEmKm0ULnzNnsKL",
    link: "/Halaman/page/5-ternak-uang/20/11",
    category: "Stock and Finance",
  },
];