export const Data = [
  {
    id: "1",
    title: "1 Landscape in Blockchain Interoperability",
    drive: "https://drive.google.com/file/d/1Z8awI7P3DbigVZ_rjDGz04eu_-T-ZL54/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/1-Landscape-in-Blockchain-Interoperability",
    category: "Crypto Blockchain",
  },
  {
    id: "2",
    title: "2 Blockchain Dbms",
    drive: "https://drive.google.com/file/d/1ZdeZ61DwJQP18DvDDiG82-4Q56srPUIq/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/2-Blockchain-Dbms",
    category: "Crypto Blockchain",
  },
  {
    id: "3",
    title: "3 Multi Blockchain Environment",
    drive: "https://drive.google.com/file/d/1ZcorMvg8tWO3UHlcsUfF7zNE2rkUFBCG/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/3-Multi-Blockchain-Environment",
    category: "Crypto Blockchain",
  },
  {
    id: "4",
    title: "4 Blockchain Joint",
    drive: "https://drive.google.com/file/d/1ZTGTZM6odGQS32glQDojcx8lWpOrq_d-/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/4-Blockchain-Joint",
    category: "Crypto Blockchain",
  },
  {
    id: "5",
    title: "5 Blockchain Extension sidechain",
    drive: "https://drive.google.com/file/d/1ZTCbGTBmLq7DjrN9P9Ot-ZKtcHhIFy5j/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/5-Blockchain-Extension-sidechain",
    category: "Crypto Blockchain",
  },
  {
    id: "6",
    title: "6 Decentralised Exchange",
    drive: "https://drive.google.com/file/d/1ZNNxImmA2Ue_DYJPXJ4MQOgxDWnBUBUB/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/6-Decentralised-Exchange",
    category: "Crypto Blockchain",
  },
  {
    id: "7",
    title: "7 State Pinning",
    drive: "https://drive.google.com/file/d/1ZIczPUVst8KwD2wIB-upjLPiQ6DBABxj/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/7-State-Pinning",
    category: "Crypto Blockchain",
  },
  {
    id: "8",
    title: "8 Consensus",
    drive: "https://drive.google.com/file/d/1ZDasW5-xgIaU2JwkPJxvzPLGvfhGN8dL/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/8-Consensus",
    category: "Crypto Blockchain",
  },
  {
    id: "9",
    title: "9 Communication and Standardisation",
    drive: "https://drive.google.com/file/d/1ZjPojYULMAILeXAKqVVFc1eTEF75gDhK/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/9-Communication-and-Standardisation",
    category: "Crypto Blockchain",
  },
  {
    id: "10",
    title: "10 Bridge",
    drive: "https://drive.google.com/file/d/1ZjFA75_6P1NgYrEoWOCVYh8O9IaYPZDB/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/10-Bridge",
    category: "Crypto Blockchain",
  },
  {
    id: "11",
    title: "11 Bridge in Summary",
    drive: "https://drive.google.com/file/d/1Zi1Ip3LNYmV-RWEAtWyaq3CwZS0KBevO/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/11-Bridge-in-Summary",
    category: "Crypto Blockchain",
  },
  {
    id: "12",
    title: "12 Benefits and Drawbacks",
    drive: "https://drive.google.com/file/d/1Zfms7lp08MXF5pJE2lrz4qFtKcR42RWu/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/12-Benefits-and-Drawbacks",
    category: "Crypto Blockchain",
  },
  {
    id: "13",
    title: "13 Case Study Blockchain in SCM approach",
    drive: "https://drive.google.com/file/d/1ZfBp_eKNIkvgTctiuY-DXWXbP6pqUA1J/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/13-Case-Study-Blockchain-in-SCM-approach",
    category: "Crypto Blockchain",
  },
  {
    id: "14",
    title: "14 Multi blockchain Multi parties",
    drive: "https://drive.google.com/file/d/1ZegDtH1E4SahoIV2OpdMtsUg_4ILvvTC/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/14-Multi-blockchain-Multi-parties",
    category: "Crypto Blockchain",
  }
];