export const Data = [
  {
    id: "1",
    title: "1 Landscape in Blockchain Interoperability",
    drive: "https://drive.google.com/file/d/1UyZ4NZVGU59fhd4ypAYp0tPOJ3wnHqg4/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/1-Landscape-in-Blockchain-Interoperability",
    category: "Crypto Blockchain",
  },
  {
    id: "2",
    title: "2 Blockchain Dbms",
    drive: "https://drive.google.com/file/d/12pLd3cxKPlO2WBTIYVnFfTDD3s7BNxTt/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/2-Blockchain-Dbms",
    category: "Crypto Blockchain",
  },
  {
    id: "3",
    title: "3 Multi Blockchain Environment",
    drive: "https://drive.google.com/file/d/1mL5c_3o-1OTsSw7tWOlNoJvJi4coI3s3/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/3-Multi-Blockchain-Environment",
    category: "Crypto Blockchain",
  },
  {
    id: "4",
    title: "4 Blockchain Joint",
    drive: "https://drive.google.com/file/d/102ZkJOd9yqat-Xox6mnJJuu3MtKJu96S/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/4-Blockchain-Joint",
    category: "Crypto Blockchain",
  },
  {
    id: "5",
    title: "5 Blockchain Extension sidechain",
    drive: "https://drive.google.com/file/d/19BmOJIBiP7rAv2UHb15awiKqz6GHOLbJ/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/5-Blockchain-Extension-sidechain",
    category: "Crypto Blockchain",
  },
  {
    id: "6",
    title: "6 Decentralised Exchange",
    drive: "https://drive.google.com/file/d/1nWuAiVtIExZp_Dreirrx7svv5FicyEsT/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/6-Decentralised-Exchange",
    category: "Crypto Blockchain",
  },
  {
    id: "7",
    title: "7 State Pinning",
    drive: "https://drive.google.com/file/d/1OyutlFuh_DPuPwBkfh7D_SIKQbqq9KPY/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/7-State-Pinning",
    category: "Crypto Blockchain",
  },
  {
    id: "8",
    title: "8 Consensus",
    drive: "https://drive.google.com/file/d/1mZH_T-TAjpdUS-SJ0vNuH9qkTJ55mVRI/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/8-Consensus",
    category: "Crypto Blockchain",
  },
  {
    id: "9",
    title: "9 Communication and Standardisation",
    drive: "https://drive.google.com/file/d/1S718eDj5KsmVrzDEFAW0hCngrV1KQEon/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/9-Communication-and-Standardisation",
    category: "Crypto Blockchain",
  },
  {
    id: "10",
    title: "10 Bridge",
    drive: "https://drive.google.com/file/d/1mp5VPnWfBrQQzvUmlhKgDP9m0PlE7Pw6/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/10-Bridge",
    category: "Crypto Blockchain",
  },
  {
    id: "11",
    title: "11 Bridge in Summary",
    drive: "https://drive.google.com/file/d/1Qawds3AvZH7wdRufsfMOyDnoMaBmJC0k/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/11-Bridge-in-Summary",
    category: "Crypto Blockchain",
  },
  {
    id: "12",
    title: "12 Benefits and Drawbacks",
    drive: "https://drive.google.com/file/d/1jn4KTMd_6XQ-S_KfZuvb9YGbLC_3BpJB/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/12-Benefits-and-Drawbacks",
    category: "Crypto Blockchain",
  },
  {
    id: "13",
    title: "13 Case Study Blockchain in SCM approach",
    drive: "https://drive.google.com/file/d/1faxdM-wiuA_O2ueEbl5vPU2eUbjeyRlc/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/13-Case-Study-Blockchain-in-SCM-approach",
    category: "Crypto Blockchain",
  },
  {
    id: "14",
    title: "14 Multi blockchain Multi parties",
    drive: "https://drive.google.com/file/d/101UAwPuUjuo_QHKZbvbZlhXjw50Ee1-c/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/2-Blockchain-Interoperability/14-Multi-blockchain-Multi-parties",
    category: "Crypto Blockchain",
  }
];