export const Data = [
  {
    id: "1",
    title: "1 Blockchain and Security Overview",
    drive: "https://drive.google.com/file/d/1feYuN1b7-V39IAjOc8ql3-wEr35NT-VW",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/1-Blockchain-and-Security-Overview",
    category: "Crypto Blockchain",
  },
  {
    id: "2",
    title: "2 Blockchain System Components",
    drive: "https://drive.google.com/file/d/1n0NFAGmy6wb2dDNq7frlW5j_Ayni1ccO",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/2-Blockchain-System-Components",
    category: "Crypto Blockchain",
  },
  {
    id: "3",
    title: "3 Blockchain Execution Environment",
    drive: "https://drive.google.com/file/d/1ETDHzK7BtwKaTKs8_OH1TBI7VlHeCcGD",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/3-Blockchain-Execution-Environment",
    category: "Crypto Blockchain",
  },
  {
    id: "4",
    title: "4 Blockchain is a Warzone",
    drive: "https://drive.google.com/file/d/1VUQBwfW8gVyFQcNgISOOjFFzg9a3gPqu/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/4-Blockchain-is-a-Warzone",
    category: "Crypto Blockchain",
  },
  {
    id: "5",
    title: "5 Instant or Unsafe Products",
    drive: "https://drive.google.com/file/d/13UGn0X0u6TzTqaw-DNpaZRBIeJOmXnLv",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/5-Instant-or-Unsafe-Products",
    category: "Crypto Blockchain",
  },
  {
    id: "6",
    title: "6 Blockchain Security Issues",
    drive: "https://drive.google.com/file/d/1AuXzBvbCmSqKoGF2_y-qMd2gMrFvQCRx",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/6-Blockchain-Security-Issues",
    category: "Crypto Blockchain",
  },
  {
    id: "7",
    title: "7 Cryptographic Techniques",
    drive: "https://drive.google.com/file/d/13yw9b9Vm7piP6DEjII_nvo46CHmGNpft",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/7-Cryptographic-Techniques",
    category: "Crypto Blockchain",
  },
  {
    id: "8",
    title: "8 Blockchain Memory Pool Mempool",
    drive: "https://drive.google.com/file/d/1_x2994WhZKHkrqtoHHi2ZjPcmrenSDyg",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/8-Blockchain-Memory-Pool-Mempool",
    category: "Crypto Blockchain",
  },
  {
    id: "9",
    title: "9 Miner Extractable Value MEV",
    drive: "https://drive.google.com/file/d/1IOJZom997wU7L1DTXzoH7c--rZtQ0b_W",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/9-Miner-Extractable-Value-MEV",
    category: "Crypto Blockchain",
  },
  {
    id: "10",
    title: "10 Finality Issues",
    drive: "https://drive.google.com/file/d/1FGjrfILaYUcTFYFlGOBLmJw0ejCNwzrc",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/10-Finality-Issues",
    category: "Crypto Blockchain",
  },
  {
    id: "11",
    title: "11 Solidity Issues",
    drive: "https://drive.google.com/file/d/1a8D5eu5Qee-XvSqN-AWdz1cbaquQtp7R",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/11-Solidity-Issues",
    category: "Crypto Blockchain",
  },
  {
    id: "12",
    title: "12 Permanent Contract and Upgradeable Contract",
    drive: "https://drive.google.com/file/d/1wajl4KSt70kzEbCbo8tG1FTBLHKQwq3B",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/12-Permanent-Contract-and-Upgradeable-Contract",
    category: "Crypto Blockchain",
  },
  {
    id: "13",
    title: "13 Decentralized Finance Issues",
    drive: "https://drive.google.com/file/d/1w_4prcRadKoST_2ot5TyEYU_sGGIZVCS",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/13-Decentralized-Finance-Issues",
    category: "Crypto Blockchain",
  },
  {
    id: "14",
    title: "14 User Issues",
    drive: "https://drive.google.com/file/d/1HpDcp9gXSB0cDkOoMkyWjY9569aGbpd0",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/14-User-Issues",
    category: "Crypto Blockchain",
  },
  {
    id: "15",
    title: "15 Security Best Practices",
    drive: "https://drive.google.com/file/d/1k8s5p4sfqclrMTEHYPQNh5Mvb5I2bXrC",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/15-Security-Best-Practices",
    category: "Crypto Blockchain",
  }
];