export const Data = [
  {
    id: "1",
    title: "1 Blockchain and Security Overview",
    drive: "https://drive.google.com/file/d/1VaKEkZhz1eNwswoO3H_f-rMcnPZTs0ZP/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/1-Blockchain-and-Security-Overview",
    category: "Crypto Blockchain",
  },
  {
    id: "2",
    title: "2 Blockchain System Components",
    drive: "https://drive.google.com/file/d/1VtkPTtz5VMn1oxgvly6isxQdownb3o-4/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/2-Blockchain-System-Components",
    category: "Crypto Blockchain",
  },
  {
    id: "3",
    title: "3 Blockchain Execution Environment",
    drive: "https://drive.google.com/file/d/1VsUKbLLt-lpPIayq-A6dPyS9hKO7wmTu/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/3-Blockchain-Execution-Environment",
    category: "Crypto Blockchain",
  },
  {
    id: "4",
    title: "4 Blockchain is a Warzone",
    drive: "https://drive.google.com/file/d/1VmkrC4Pea1EkbAtv3qrreSyo1uaxwUGx/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/4-Blockchain-is-a-Warzone",
    category: "Crypto Blockchain",
  },
  {
    id: "5",
    title: "5 Instant or Unsafe Products",
    drive: "https://drive.google.com/file/d/1VljZl1o24lSYYBeNCe1XYvyA9ls1eixm/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/5-Instant-or-Unsafe-Products",
    category: "Crypto Blockchain",
  },
  {
    id: "6",
    title: "6 Blockchain Security Issues",
    drive: "https://drive.google.com/file/d/1VgtJ7CdLOcw4y4wocCWDHmMwyEdDJ8u_/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/6-Blockchain-Security-Issues",
    category: "Crypto Blockchain",
  },
  {
    id: "7",
    title: "7 Cryptographic Techniques",
    drive: "https://drive.google.com/file/d/1Vcq2qvEVqfQYYsIhwrywjpPeUHgm2D-j/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/7-Cryptographic-Techniques",
    category: "Crypto Blockchain",
  },
  {
    id: "8",
    title: "8 Blockchain Memory Pool Mempool",
    drive: "https://drive.google.com/file/d/1VcUQbk7Au6f_l3ff7kFFlxodbrjNK8Fv/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/8-Blockchain-Memory-Pool-Mempool",
    category: "Crypto Blockchain",
  },
  {
    id: "9",
    title: "9 Miner Extractable Value MEV",
    drive: "https://drive.google.com/file/d/1WI8YGVJXGsajc4j7-EKXJbb1LbDF13xi/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/9-Miner-Extractable-Value-MEV",
    category: "Crypto Blockchain",
  },
  {
    id: "10",
    title: "10 Finality Issues",
    drive: "https://drive.google.com/file/d/1VbvDIzP-eZgPfd8cNeZmYJmigd7QjXhW/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/10-Finality-Issues",
    category: "Crypto Blockchain",
  },
  {
    id: "11",
    title: "11 Solidity Issues",
    drive: "https://drive.google.com/file/d/1WCgSZ-c0PGmY4Um4XfBnryfIemLhEkQ4/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/11-Solidity-Issues",
    category: "Crypto Blockchain",
  },
  {
    id: "12",
    title: "12 Permanent Contract and Upgradeable Contract",
    drive: "https://drive.google.com/file/d/1WAebw9PSazAlHKsKGsGMd0erp7eoCERQ/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/12-Permanent-Contract-and-Upgradeable-Contract",
    category: "Crypto Blockchain",
  },
  {
    id: "13",
    title: "13 Decentralized Finance Issues",
    drive: "https://drive.google.com/file/d/1W-d2kJW0dHcZcg1IxxBhRvdJ849p4Ehu/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/13-Decentralized-Finance-Issues",
    category: "Crypto Blockchain",
  },
  {
    id: "14",
    title: "14 User Issues",
    drive: "https://drive.google.com/file/d/1W-Nun6s_pTfUDWcC8BxCueXFMsFhxGu1/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/14-User-Issues",
    category: "Crypto Blockchain",
  },
  {
    id: "15",
    title: "15 Security Best Practices",
    drive: "https://drive.google.com/file/d/1Vx_hSWV-1WndMPWkEP3bKTP2i5w37KOV/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/15-Security-Best-Practices",
    category: "Crypto Blockchain",
  }
];