export const Data = [
  {
    id: "1",
    title: "1 Blockchain and Security Overview",
    drive: "https://drive.google.com/file/d/1gSEUR1KIGUQE7M7kg2NW9gM6p3KegBBN/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/1-Blockchain-and-Security-Overview",
    category: "Crypto Blockchain",
  },
  {
    id: "2",
    title: "2 Blockchain System Components",
    drive: "https://drive.google.com/file/d/1zyENf13va0Ww9H9UfHd_ioEvt59ITWVg/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/2-Blockchain-System-Components",
    category: "Crypto Blockchain",
  },
  {
    id: "3",
    title: "3 Blockchain Execution Environment",
    drive: "https://drive.google.com/file/d/1PaarYBxZ-wzAmwVOUDkx1D1rj6CX_0cW/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/3-Blockchain-Execution-Environment",
    category: "Crypto Blockchain",
  },
  {
    id: "4",
    title: "4 Blockchain is a Warzone",
    drive: "https://drive.google.com/file/d/1VUQBwfW8gVyFQcNgISOOjFFzg9a3gPqu/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/4-Blockchain-is-a-Warzone",
    category: "Crypto Blockchain",
  },
  {
    id: "5",
    title: "5 Instant or Unsafe Products",
    drive: "https://drive.google.com/file/d/13YYBx74hEaLEfj7B5i3oBEsRVCHqJBXS/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/5-Instant-or-Unsafe-Products",
    category: "Crypto Blockchain",
  },
  {
    id: "6",
    title: "6 Blockchain Security Issues",
    drive: "https://drive.google.com/file/d/1Kj89tM9616qSgBleTsrLFtA7GgGcun-u/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/6-Blockchain-Security-Issues",
    category: "Crypto Blockchain",
  },
  {
    id: "7",
    title: "7 Cryptographic Techniques",
    drive: "https://drive.google.com/file/d/18sx7ywpdx0JaVUsAmh9OuvUg2r3Mzhc1/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/7-Cryptographic-Techniques",
    category: "Crypto Blockchain",
  },
  {
    id: "8",
    title: "8 Blockchain Memory Pool Mempool",
    drive: "",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/8-Blockchain-Memory-Pool-Mempool",
    category: "Crypto Blockchain",
  },
  {
    id: "9",
    title: "9 Miner Extractable Value MEV",
    drive: "https://drive.google.com/file/d/1qL6ui_kHEl2li4jSDm43UDpQt_SxLaxa/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/9-Miner-Extractable-Value-MEV",
    category: "Crypto Blockchain",
  },
  {
    id: "10",
    title: "10 Finality Issues",
    drive: "https://drive.google.com/file/d/18v4S41x4tUpBkbBPxypMcJj-Teml6EFB/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/10-Finality-Issues",
    category: "Crypto Blockchain",
  },
  {
    id: "11",
    title: "11 Solidity Issues",
    drive: "https://drive.google.com/file/d/1_KbQmrh1Wuk9cOcGgkpVcbdXAVsQ7BUQ/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/11-Solidity-Issues",
    category: "Crypto Blockchain",
  },
  {
    id: "12",
    title: "12 Permanent Contract and Upgradeable Contract",
    drive: "https://drive.google.com/file/d/13d-nQY0zJIlUm3dP9EHd_163s8PskW9F/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/12-Permanent-Contract-and-Upgradeable-Contract",
    category: "Crypto Blockchain",
  },
  {
    id: "13",
    title: "13 Decentralized Finance Issues",
    drive: "https://drive.google.com/file/d/1WQUU_3C7US1E3UJVb7dl2bFp29kYJpAN/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/13-Decentralized-Finance-Issues",
    category: "Crypto Blockchain",
  },
  {
    id: "14",
    title: "14 User Issues",
    drive: "https://drive.google.com/file/d/1_GUq4hEJ-spJLPQD3b7U1smDB6fjIgKZ/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/14-User-Issues",
    category: "Crypto Blockchain",
  },
  {
    id: "15",
    title: "15 Security Best Practices",
    drive: "https://drive.google.com/file/d/1B0YXzIjQD0l36jJVE6ewIaxxVfSMR8_d/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/4-Cryptocurrency-Security/15-Security-Best-Practices",
    category: "Crypto Blockchain",
  }
];