export const Data = [
  {
    id: "1",
    title: "1 Introduction to Ethereum",
    drive: "https://drive.google.com/file/d/1rXCvjSpMOdhqwKnxHnTwEnyV4FESmtKZ/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/1-Introduction-to-Ethereum",
    category: "Crypto Blockchain",
  },
  {
    id: "2",
    title: "2 Ethereum vs Bitcoin",
    drive: "https://drive.google.com/file/d/17m_9lUwovOPzlcCaHO5ZVCkWqi-HVLo3/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/2-Ethereum-vs-Bitcoin",
    category: "Crypto Blockchain",
  },
  {
    id: "3",
    title: "3 Ethereum History and Stages",
    drive: "https://drive.google.com/file/d/1F1pRtFTz8rry3yByUqPZ_7hoifkZiT4Z/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/3-Ethereum-History-and-Stages",
    category: "Crypto Blockchain",
  },
  {
    id: "4",
    title: "4 Ethereum and Blockchain Components",
    drive: "https://drive.google.com/file/d/1j20q6LCCQxhz-ErUMSstm_b0t1HuT4Y8/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/4-Ethereum-and-Blockchain-Components",
    category: "Crypto Blockchain",
  },
  {
    id: "5",
    title: "5 Ethereum Denomination Wallet and Networks",
    drive: "https://drive.google.com/file/d/1zGL7Q33srZZrQC9i9q7x8QjKAkcLNcKA/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/5-Ethereum-Denomination-Wallet-and-Networks",
    category: "Crypto Blockchain",
  },
  {
    id: "6",
    title: "6 Introduction Ethereum transaction",
    drive: "https://drive.google.com/file/d/13DzQXYg0nt5dHcgcHpxZEoy569EinYVq/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/6-Introduction-Ethereum-transaction",
    category: "Crypto Blockchain",
  },
  {
    id: "7",
    title: "7 the Structure of a Transaction",
    drive: "https://drive.google.com/file/d/13XEdpdXISJX_m5Aw6RSm_POFkIozBa9W/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/7-the-Structure-of-a-Transaction",
    category: "Crypto Blockchain",
  },
  {
    id: "8",
    title: "8 Transaction Nonce Gas and Gas Limit",
    drive: "https://drive.google.com/file/d/1hEDh0uTRzrVwBub7N5fhelPeRgMV5wIO/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/8-Transaction-Nonce-Gas-and-Gas-Limit",
    category: "Crypto Blockchain",
  },
  {
    id: "9",
    title: "9 the Merge",
    drive: "https://drive.google.com/file/d/1aQaPGrMlQwiSkPbw3wT0l_CZaAiGjxeu/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/9-the-Merge",
    category: "Crypto Blockchain",
  },
  {
    id: "10",
    title: "10 Myths about the Merge",
    drive: "https://drive.google.com/file/d/1Vm-TlyBXueOt4Lrln1g1zqyw48bZfYOf/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/10-Myths-about-the-Merge",
    category: "Crypto Blockchain",
  },
  {
    id: "11",
    title: "11 Ethereum Virtual Machine",
    drive: "https://drive.google.com/file/d/1H6li0UXEH1QPfWJGiJzWzbWjGP0VtpPw/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/11-Ethereum-Virtual-Machine",
    category: "Crypto Blockchain",
  },
  {
    id: "12",
    title: "12 Stake ETH di LIDO",
    drive: "https://drive.google.com/file/d/13YtlaQWNzSUdslL_YQfyC2DYKsyXhh6j/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/12-Stake-ETH-di-LIDO",
    category: "Crypto Blockchain",
  },
  {
    id: "13",
    title: "13 stETH dan Withdrawal",
    drive: "https://drive.google.com/file/d/1Nw8tfpuYY9F4s0bhZxnpIn_KYm9eacwp/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/13-stETH-dan-Withdrawal",
    category: "Crypto Blockchain",
  }
];