export const Data = [
  {
    id: "1",
    title: "1 Introduction to Ethereum",
    drive: "https://drive.google.com/file/d/1CFL-BYSg0Brl3CFrWcQYKHZvynOIv65r",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/1-Introduction-to-Ethereum",
    category: "Crypto Blockchain",
  },
  {
    id: "2",
    title: "2 Ethereum vs Bitcoin",
    drive: "https://drive.google.com/file/d/10bZ6q07uc3i1Mlid-wh7GoSY4z09olMf",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/2-Ethereum-vs-Bitcoin",
    category: "Crypto Blockchain",
  },
  {
    id: "3",
    title: "3 Ethereum History and Stages",
    drive: "https://drive.google.com/file/d/1Xq_suTD4o44FoOWGvZEczSuGoiDtjXZV",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/3-Ethereum-History-and-Stages",
    category: "Crypto Blockchain",
  },
  {
    id: "4",
    title: "4 Ethereum and Blockchain Components",
    drive: "https://drive.google.com/file/d/1Jtd8eC1MEZeqtW8B0nwJG70TmfOj7_-w",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/4-Ethereum-and-Blockchain-Components",
    category: "Crypto Blockchain",
  },
  {
    id: "5",
    title: "5 Ethereum Denomination Wallet and Networks",
    drive: "https://drive.google.com/file/d/1-x919kaoKRoK9BgaGp8Pq18TodD74SHB",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/5-Ethereum-Denomination-Wallet-and-Networks",
    category: "Crypto Blockchain",
  },
  {
    id: "6",
    title: "6 Introduction Ethereum transaction",
    drive: "https://drive.google.com/file/d/1Lc8CQQ-_ANLqgIpCqoV50iXP-3TJP1kh",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/6-Introduction-Ethereum-transaction",
    category: "Crypto Blockchain",
  },
  {
    id: "7",
    title: "7 the Structure of a Transaction",
    drive: "https://drive.google.com/file/d/12sESDNj3E6fi8-N7TyVW0uJ2PQRw8Iup",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/7-the-Structure-of-a-Transaction",
    category: "Crypto Blockchain",
  },
  {
    id: "8",
    title: "8 Transaction Nonce Gas and Gas Limit",
    drive: "https://drive.google.com/file/d/1_pEMHoxN8yPjXe2120UrcI_IllgyaKpS",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/8-Transaction-Nonce-Gas-and-Gas-Limit",
    category: "Crypto Blockchain",
  },
  {
    id: "9",
    title: "9 the Merge",
    drive: "https://drive.google.com/file/d/1m0WUgfskAVCgWJjbCfakHf74KwMug27a",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/9-the-Merge",
    category: "Crypto Blockchain",
  },
  {
    id: "10",
    title: "10 Myths about the Merge",
    drive: "https://drive.google.com/file/d/1zg89zax4mc5FjXAWI0iveuGfRsqaHtmd",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/10-Myths-about-the-Merge",
    category: "Crypto Blockchain",
  },
  {
    id: "11",
    title: "11 Ethereum Virtual Machine",
    drive: "https://drive.google.com/file/d/1FzSc2UtHrbXWa2wbC7IrvorMqOuNSgYm",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/11-Ethereum-Virtual-Machine",
    category: "Crypto Blockchain",
  },
  {
    id: "12",
    title: "12 Stake ETH di LIDO",
    drive: "https://drive.google.com/file/d/1bfBAurE97aJy6nAKc6FP-o2B6bLvFr9l",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/12-Stake-ETH-di-LIDO",
    category: "Crypto Blockchain",
  },
  {
    id: "13",
    title: "13 stETH dan Withdrawal",
    drive: "https://drive.google.com/file/d/1abs8JW0TXBBWHceZMho65_UZD3l0FbwV",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/13-stETH-dan-Withdrawal",
    category: "Crypto Blockchain",
  }
];