export const Data = [
  {
    id: "1",
    title: "1 Introduction to Ethereum",
    drive: "https://drive.google.com/file/d/1U3NR3PqBPkOOt6ZA5EmxaVZYG3gn54Kc/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/1-Introduction-to-Ethereum",
    category: "Crypto Blockchain",
  },
  {
    id: "2",
    title: "2 Ethereum vs Bitcoin",
    drive: "https://drive.google.com/file/d/1UwYEnqfNScLcLnaO13j6UbXIttvBe3sG/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/2-Ethereum-vs-Bitcoin",
    category: "Crypto Blockchain",
  },
  {
    id: "3",
    title: "3 Ethereum History and Stages",
    drive: "https://drive.google.com/file/d/1Uw0p9GYArf-9XzKjMFx3AIlknqXOl8O3/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/3-Ethereum-History-and-Stages",
    category: "Crypto Blockchain",
  },
  {
    id: "4",
    title: "4 Ethereum and Blockchain Components",
    drive: "https://drive.google.com/file/d/1Uvk1lbQE54gPCXov0FWKAjyojAECfDui/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/4-Ethereum-and-Blockchain-Components",
    category: "Crypto Blockchain",
  },
  {
    id: "5",
    title: "5 Ethereum Denomination Wallet and Networks",
    drive: "https://drive.google.com/file/d/1UvJ2pTGZmBXaqSK_t3SETJjYP5Zwx35N/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/5-Ethereum-Denomination-Wallet-and-Networks",
    category: "Crypto Blockchain",
  },
  {
    id: "6",
    title: "6 Introduction Ethereum transaction",
    drive: "https://drive.google.com/file/d/1UTftrep48WtEob39Uf-kHuIv-f1CiAQ5/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/6-Introduction-Ethereum-transaction",
    category: "Crypto Blockchain",
  },
  {
    id: "7",
    title: "7 the Structure of a Transaction",
    drive: "https://drive.google.com/file/d/1ULU7PoHXjEi9B5AOm173Qd09yjwF7qw8/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/7-the-Structure-of-a-Transaction",
    category: "Crypto Blockchain",
  },
  {
    id: "8",
    title: "8 Transaction Nonce Gas and Gas Limit",
    drive: "https://drive.google.com/file/d/1UAsjmZEnN1IoebOZobspck4KUAhgUiir/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/8-Transaction-Nonce-Gas-and-Gas-Limit",
    category: "Crypto Blockchain",
  },
  {
    id: "9",
    title: "9 the Merge",
    drive: "https://drive.google.com/file/d/1U9OK3OvneSr4V1Z7nXX5WNUjNSpDMozs/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/9-the-Merge",
    category: "Crypto Blockchain",
  },
  {
    id: "10",
    title: "10 Myths about the Merge",
    drive: "https://drive.google.com/file/d/1U7GBsGVzZ5SAwKXn87iAC62fXhpnL2HD/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/10-Myths-about-the-Merge",
    category: "Crypto Blockchain",
  },
  {
    id: "11",
    title: "11 Ethereum Virtual Machine",
    drive: "https://drive.google.com/file/d/1Uy_209is061s4C43wNVdyaRRwUx0LIl1/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/11-Ethereum-Virtual-Machine",
    category: "Crypto Blockchain",
  },
  {
    id: "12",
    title: "12 Stake ETH di LIDO",
    drive: "https://drive.google.com/file/d/1U6LnJRdmkECFqcujWWCrW8S28r4oHUlf/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/12-Stake-ETH-di-LIDO",
    category: "Crypto Blockchain",
  },
  {
    id: "13",
    title: "13 stETH dan Withdrawal",
    drive: "https://drive.google.com/file/d/1Ux0zWRQB7IXGc1iziFpa0Wj2kUVw0Zc9/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/8-Ethereum-Programmable-Money/13-stETH-dan-Withdrawal",
    category: "Crypto Blockchain",
  }
];