export const Data = [
  {
    id: "1",
    title: "What is Technical Analysis",
    drive: "https://drive.google.com/file/d/1-DhhYGboBhAYLvPQlv8eRxoj3yTlVb8z",
    link: "/Halaman/page/5-ternak-uang/5/1",
    category: "Stock and Finance",
  },
  {
    id: "2",
    title: "Side to Side Fundamental vs Technical",
    drive: "https://drive.google.com/file/d/1x6tpeT_xglodtmGkOax0m_LCWG0GJyl2",
    link: "/Halaman/page/5-ternak-uang/5/2",
    category: "Stock and Finance",
  },
  {
    id: "3",
    title: "Why Use Technical Analysis",
    drive: "https://drive.google.com/file/d/1nDivhoD8LKRmA7hn1eD5Gfr7bbopJdLI",
    link: "/Halaman/page/5-ternak-uang/5/3",
    category: "Stock and Finance",
  },
  {
    id: "4",
    title: "Why Trendline",
    drive: "https://drive.google.com/file/d/1BDSnoveAX3_OpqRMyigNyZpREmLcShZt",
    link: "/Halaman/page/5-ternak-uang/5/4",
    category: "Stock and Finance",
  },
  {
    id: "5",
    title: "Praktek Trendline",
    drive: "https://drive.google.com/file/d/1pWtm6ADALhjiHxMJCGAxorsL0tmBh33a",
    link: "/Halaman/page/5-ternak-uang/5/5",
    category: "Stock and Finance",
  },
  {
    id: "6",
    title: "Apa itu Support and Resistance",
    drive: "https://drive.google.com/file/d/12JMmt3tP9_8VCgEGBQRvMVu3bUHjB_lh",
    link: "/Halaman/page/5-ternak-uang/5/6",
    category: "Stock and Finance",
  },
  {
    id: "7",
    title: "Contoh Support and Resistance",
    drive: "https://drive.google.com/file/d/1ryEHW2FDa8bPSYCMxjaRTMcNxbMSmPPr",
    link: "/Halaman/page/5-ternak-uang/5/7",
    category: "Stock and Finance",
  },
  {
    id: "8",
    title: "Pengertian Candlestick",
    drive: "https://drive.google.com/file/d/1l4EWh-wO15ORbJQ_hJgdszZq2JB0XPs5",
    link: "/Halaman/page/5-ternak-uang/5/8",
    category: "Stock and Finance",
  },
  {
    id: "9",
    title: "Pattern",
    drive: "https://drive.google.com/file/d/125jJtwC2QYT7qTNz0XBS9fSCJOZW07KD",
    link: "/Halaman/page/5-ternak-uang/5/9",
    category: "Stock and Finance",
  },
  {
    id: "10",
    title: "Praktek Candlestick",
    drive: "https://drive.google.com/file/d/15aAtFPW5tof8B32W97SrAk3-T2NkcyhP",
    link: "/Halaman/page/5-ternak-uang/5/10",
    category: "Stock and Finance",
  },
  {
    id: "11",
    title: "Apa itu Indicator",
    drive: "https://drive.google.com/file/d/1_CkkstaNNjIZNQJC1Dsr4wszukxDYG7z",
    link: "/Halaman/page/5-ternak-uang/5/11",
    category: "Stock and Finance",
  },
  {
    id: "12",
    title: "Trend (Moving Average) dan Praktek",
    drive: "https://drive.google.com/file/d/19fWXSek-NMGnL3ngg6JQo434JDh_34IF",
    link: "/Halaman/page/5-ternak-uang/5/12",
    category: "Stock and Finance",
  },
  {
    id: "13",
    title: "Oscilator (Stochastic and MACD) with Praktek",
    drive: "https://drive.google.com/file/d/14fGXxx2dqaYbOon3-t09lgRgYQlGPbcN",
    link: "/Halaman/page/5-ternak-uang/5/13",
    category: "Stock and Finance",
  },
  {
    id: "14",
    title: "Pentingnya Volume",
    drive: "https://drive.google.com/file/d/1ZqhOK1cj1X_nJmNuAtGwOYQfEo_IIXrL",
    link: "/Halaman/page/5-ternak-uang/5/14",
    category: "Stock and Finance",
  },
  {
    id: "15",
    title: "Pros and Cons Indicators",
    drive: "https://drive.google.com/file/d/1kBz4XqD8aqPOw8w528hDuTpRnbVNmekz",
    link: "/Halaman/page/5-ternak-uang/5/15",
    category: "Stock and Finance",
  },
  {
    id: "16",
    title: "What is Chart Pattern",
    drive: "https://drive.google.com/file/d/1ux7f8Fic5F5wZyGPHYiVn3toEzj-uGP1",
    link: "/Halaman/page/5-ternak-uang/5/16",
    category: "Stock and Finance",
  },
  {
    id: "17",
    title: "Chart Pattern di Fase Bullish and Bearish",
    drive: "https://drive.google.com/file/d/1er4Ozlr3bafuUd1yIh-vIBoaEH3lrnyc",
    link: "/Halaman/page/5-ternak-uang/5/17",
    category: "Stock and Finance",
  },
  {
    id: "18",
    title: "Praktik Chart Pattern",
    drive: "https://drive.google.com/file/d/1WNQElKStYs7WKvkI19qMt7jG8xAHyASN",
    link: "/Halaman/page/5-ternak-uang/5/18",
    category: "Stock and Finance",
  },
  {
    id: "19",
    title: "What is Fibonacci",
    drive: "https://drive.google.com/file/d/1FbwigzUpesPH3EMenYlNfJsQohcFnpkh",
    link: "/Halaman/page/5-ternak-uang/5/19",
    category: "Stock and Finance",
  },
  {
    id: "20",
    title: "Jenis Fibonacci Umum",
    drive: "https://drive.google.com/file/d/1yY1vY-BwkwgdWEUXh0aCSinKtUwq0ONF",
    link: "/Halaman/page/5-ternak-uang/5/20",
    category: "Stock and Finance",
  },
  {
    id: "21",
    title: "Cara Mengukur Target Harga by Fibonacci",
    drive: "https://drive.google.com/file/d/1AcRSxBlsaBIHDX99AxyZKGjm1xtSI3Ap",
    link: "/Halaman/page/5-ternak-uang/5/21",
    category: "Stock and Finance",
  },
  {
    id: "22",
    title: "Apa itu Flow",
    drive: "https://drive.google.com/file/d/1-a4bGSyS_J-GceamP5DH6_ZLxaDlejQe",
    link: "/Halaman/page/5-ternak-uang/5/22",
    category: "Stock and Finance",
  },
  {
    id: "23",
    title: "Praktek Mengamati Flow",
    drive: "https://drive.google.com/file/d/1DoaHg-Dw60l-RSnpsSqnDG-DY3_mP0CW",
    link: "/Halaman/page/5-ternak-uang/5/23",
    category: "Stock and Finance",
  },
  {
    id: "24",
    title: "Investasi itu Soal Preferensi",
    drive: "https://drive.google.com/file/d/19YZG4M0VF33LUY744xO65EOmiMiO43oe",
    link: "/Halaman/page/5-ternak-uang/5/24",
    category: "Stock and Finance",
  },
];