export const Data = [
  {
    id: "1",
    title: "1 Introduction to Crypto Research",
    drive: "https://drive.google.com/file/d/1Pz9U-hL-Th5Ed0Vn2Yi__A8k4Q5G_9DH/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/10-Crypto-Research/1-Introduction-to-Crypto-Research",
    category: "Crypto Blockchain",
  },
  {
    id: "2",
    title: "2 Value Proposition and Qualitative Analysis",
    drive: "https://drive.google.com/file/d/1QIseo8fOddiJO64Asy3StpnltvYWDoMe/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/10-Crypto-Research/2-Value-Proposition-and-Qualitative-Analysis",
    category: "Crypto Blockchain",
  },
  {
    id: "3",
    title: "3 Quantitative Analysis",
    drive: "https://drive.google.com/file/d/1QID6jNwIV44nI4t65A8ARsN5QcXhl_6Z/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/10-Crypto-Research/3-Quantitative-Analysis",
    category: "Crypto Blockchain",
  },
  {
    id: "4",
    title: "4 Token Terminal Tutorial",
    drive: "https://drive.google.com/file/d/1QGeU4TzFL17fYDcTzEXCEa_2zwBp2cWk/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/10-Crypto-Research/4-Token-Terminal-Tutorial",
    category: "Crypto Blockchain",
  },
  {
    id: "5",
    title: "5 Opinion Strategy and Follow Up",
    drive: "https://drive.google.com/file/d/1QE4zvw70ztO-WjLn-pyE_3mf_UkAhA4E/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/10-Crypto-Research/5-Opinion-Strategy-and-Follow-Up",
    category: "Crypto Blockchain",
  },
  {
    id: "6",
    title: "6 Blockchain Economics",
    drive: "https://drive.google.com/file/d/1QCJZUcEdxyblQVBDvsrMh8Zf5zmmgKaN/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/10-Crypto-Research/6-Blockchain-Economics",
    category: "Crypto Blockchain",
  },
  {
    id: "7",
    title: "7 Introduction to Crypto Airdrop",
    drive: "https://drive.google.com/file/d/1Q99uCLy5CVG9X87fXmzg13cgnTpq4DmJ/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/10-Crypto-Research/7-Introduction-to-Crypto-Airdrop",
    category: "Crypto Blockchain",
  },
  {
    id: "8",
    title: "8 ZkSync Airdrop Tutorial",
    drive: "https://drive.google.com/file/d/1Q5bRnEjNYmIlxsBjUSOS7wArDJRt6LYw/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/10-Crypto-Research/8-ZkSync-Airdrop-Tutorial",
    category: "Crypto Blockchain",
  },
  {
    id: "9",
    title: "9 Layer Zero",
    drive: "https://drive.google.com/file/d/1Q1_NQcUkL5Eq8YHY40dLfPkZy6AAk5Fi/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/10-Crypto-Research/9-Layer-Zero",
    category: "Crypto Blockchain",
  }
];