export const Data = [
  {
    id: "1",
    title: "Introduction",
    drive: "https://drive.google.com/file/d/1pgnAdYR01gXIiNJYDofiOdwpWvTh-Q0B",
    link: "/Halaman/page/5-ternak-uang/1/1",
    category: "Stock and Finance",
  },
  {
    id: "2",
    title: "Apa itu Saham",
    drive: "https://drive.google.com/file/d/19yGdxlJOWADRIxDuJ9Dl7-_aLMb37WFJ",
    link: "/Halaman/page/5-ternak-uang/1/2",
    category: "Stock and Finance",
  },
  {
    id: "3",
    title: "Siapa cocok investasi saham",
    drive: "https://drive.google.com/file/d/1Ef-sW0H-1kT3drNQLiQjFHwHKETEBpib",
    link: "/Halaman/page/5-ternak-uang/1/3",
    category: "Stock and Finance",
  },
  {
    id: "4",
    title: "Untung dan rugi saham darimana",
    drive: "https://drive.google.com/file/d/1OcC5Fwi47hPtcDjEiQpWrg06NwSg6Oug",
    link: "/Halaman/page/5-ternak-uang/1/4",
    category: "Stock and Finance",
  },
  {
    id: "5",
    title: "Cara Kerja Saham",
    drive: "https://drive.google.com/file/d/1KJ6aya_PkIT5ohnx2VIeXAFXTpBj_s02",
    link: "/Halaman/page/5-ternak-uang/1/5",
    category: "Stock and Finance",
  },
  {
    id: "6",
    title: "Memilih Saham Pertama",
    drive: "https://drive.google.com/file/d/1QUmTVflbPo5FxaRQEtbdJ8eFrc2DjziZ",
    link: "/Halaman/page/5-ternak-uang/1/6",
    category: "Stock and Finance",
  },
  {
    id: "7",
    title: "Gagal Berinvestasi Saham",
    drive: "https://drive.google.com/file/d/1Vx5C3HLESjeTX63J0hwKbw_R5PstoY7B",
    link: "/Halaman/page/5-ternak-uang/1/7",
    category: "Stock and Finance",
  },
  {
    id: "9",
    title: "Introduction",
    drive: "https://drive.google.com/file/d/1qkhj3XGFi2fpWLYWBURYM5XBA5gje5Gp",
    link: "/Halaman/page/5-ternak-uang/1/9",
    category: "Stock and Finance",
  },
  {
    id: "10",
    title: "Analisa Kualitas Perusahaan",
    drive: "https://drive.google.com/file/d/1jOfybDio5f5osU01-y7uqcK2E9YjNuZ9",
    link: "/Halaman/page/5-ternak-uang/1/10",
    category: "Stock and Finance",
  },
  {
    id: "11",
    title: "Analisa Rasio Keuangan",
    drive: "https://drive.google.com/file/d/1YxX7LufjCEIgFrdgjmf_D5rhGRkmUJE3",
    link: "/Halaman/page/5-ternak-uang/1/11",
    category: "Stock and Finance",
  },
  {
    id: "12",
    title: "Analisa Teknikal",
    drive: "https://drive.google.com/file/d/1x3TBTGeYVj1iMsvkwnITblzmiQRUyPpf",
    link: "/Halaman/page/5-ternak-uang/1/12",
    category: "Stock and Finance",
  },
];