export const Data = [
  {
    id: "1",
    title: "1 Bitcoin Transaction In Depth",
    drive: "https://drive.google.com/file/d/1SXp29ZPLGcYpH548ghe4J7GuuY50XQMS/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/1-Bitcoin-Transaction-In-Depth",
    category: "Crypto Blockchain",
  },
  {
    id: "2",
    title: "2 base58Check Encoding",
    drive: "https://drive.google.com/file/d/1SmG8tAjhJbWvYpJHAdde1993zBv8xE4n/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/2-base58Check-Encoding",
    category: "Crypto Blockchain",
  },
  {
    id: "3",
    title: "3 Bitcoin Scripting",
    drive: "https://drive.google.com/file/d/1SjzCyKGmtCRXqTgl6tz2MOYkAYcZ0yNH/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/3-Bitcoin-Scripting",
    category: "Crypto Blockchain",
  },
  {
    id: "4",
    title: "4 Pay to Address P2A",
    drive: "https://drive.google.com/file/d/1QSkamFJbc_r4K0EwHpgMGLVAJrDkhdsS/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/4-Pay-to-Address-P2A",
    category: "Crypto Blockchain",
  },
  {
    id: "5",
    title: "5 Pay to Public Key P2PK",
    drive: "https://drive.google.com/file/d/1RHGpC7wDqk-tK8KtPVYm-x57Bvzm2lnJ/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/5-Pay-to-Public-Key-P2PK",
    category: "Crypto Blockchain",
  },
  {
    id: "6",
    title: "6 Hash Locked Transaction HLT",
    drive: "https://drive.google.com/file/d/1RH1tzbA0e1V1cbEG_FPWnAFpdVjv0wLe/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/6-Hash-Locked-Transaction-HLT",
    category: "Crypto Blockchain",
  },
  {
    id: "7",
    title: "7 Sequence Number",
    drive: "https://drive.google.com/file/d/1R6RGxXaKcY9A8qoNhJ5dw8a4pfZmm5YF/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/7-Sequence-Number",
    category: "Crypto Blockchain",
  },
  {
    id: "8",
    title: "8 Playing Around with IDE",
    drive: "https://drive.google.com/file/d/1QmrF6FHciSnMWH1NgcJDFweUc5pW71XD/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/8-Playing-Around-with-IDE",
    category: "Crypto Blockchain",
  },
  {
    id: "9",
    title: "9 QUIZ",
    drive: "https://drive.google.com/file/d/1QKmWPpLo62HvCgfIG9770JHOILHuw3JD/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/9-QUIZ",
    category: "Crypto Blockchain",
  },
  {
    id: "10",
    title: "10 Revisting Bitcoin Transaction",
    drive: "https://drive.google.com/file/d/1RMdYcgm8lrgM9u2FrE9Oqwq8E4UbdnQx/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/10-Revisting-Bitcoin-Transaction",
    category: "Crypto Blockchain",
  },
  {
    id: "11",
    title: "11 RAW Transaction",
    drive: "https://drive.google.com/file/d/1T2IFYc1v6-mYsiNgDZ3BLHKxUauB5AXc/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/11-RAW-Transaction",
    category: "Crypto Blockchain",
  },
  {
    id: "12",
    title: "12 Creating Bitcoin Script",
    drive: "https://drive.google.com/file/d/1Ss-TpRjUGOup0hJGVYwM1kgVWtm3SYjX/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/12-Creating-Bitcoin-Script",
    category: "Crypto Blockchain",
  },
  {
    id: "13",
    title: "13 Advanced Bitcoin Protocol",
    drive: "https://drive.google.com/file/d/1T4q6IOND64t6LYZ413K4kxVJM9QH-vj8/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/13-Advanced-Bitcoin-Protocol",
    category: "Crypto Blockchain",
  },
  {
    id: "14",
    title: "14 Bitcoin Programming with BX",
    drive: "https://drive.google.com/file/d/1T3ocQP28EOGOs2gJ1f5jrbo8_4vDG8Eh/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/14-Bitcoin-Programming-with-BX",
    category: "Crypto Blockchain",
  },
  {
    id: "15",
    title: "15 Key Generation with BX",
    drive: "https://drive.google.com/file/d/1TAVi8wNVYpoMseZ11Eh71iy1SpsJI2Dh/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/15-Key-Generation-with-BX",
    category: "Crypto Blockchain",
  },
  {
    id: "16",
    title: "16 Other Important BX Operations",
    drive: "https://drive.google.com/file/d/1TCjbKCdkrTFeP9N4kf-0CZ82sPW7JWNU/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/16-Other-Important-BX-Operations",
    category: "Crypto Blockchain",
  }
];