export const Data = [
  {
    id: "1",
    title: "1 Bitcoin Transaction In Depth",
    drive: "https://drive.google.com/file/d/1jfK2k8bHHeDBVqdY7wjsIxicvTbRCdTV/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/1-Bitcoin-Transaction-In-Depth",
    category: "Crypto Blockchain",
  },
  {
    id: "2",
    title: "2 base58Check Encoding",
    drive: "https://drive.google.com/file/d/169OxNH1QUaKToPoiFvCAh4h_B3Dd4Gvl/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/2-base58Check-Encoding",
    category: "Crypto Blockchain",
  },
  {
    id: "3",
    title: "3 Bitcoin Scripting",
    drive: "https://drive.google.com/file/d/1NS0UoKHZx2tcibXXJ_akFTAGEFA-7wnP/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/3-Bitcoin-Scripting",
    category: "Crypto Blockchain",
  },
  {
    id: "4",
    title: "4 Pay to Address P2A",
    drive: "https://drive.google.com/file/d/1evDGiGjbGOj6E44mhd7lBgJKk1z3PfJf/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/4-Pay-to-Address-P2A",
    category: "Crypto Blockchain",
  },
  {
    id: "5",
    title: "5 Pay to Public Key P2PK",
    drive: "https://drive.google.com/file/d/1FKgbDknfW46tOjxj2CLsnIyqvPwnwAps/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/5-Pay-to-Public-Key-P2PK",
    category: "Crypto Blockchain",
  },
  {
    id: "6",
    title: "6 Hash Locked Transaction HLT",
    drive: "https://drive.google.com/file/d/1I6Fu1C992AcuNkllYkWXsC8GZz19hKt7/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/6-Hash-Locked-Transaction-HLT",
    category: "Crypto Blockchain",
  },
  {
    id: "7",
    title: "7 Sequence Number",
    drive: "https://drive.google.com/file/d/1n63DK-YnuZCBIY3TGpQrx0Zn-VSM4r8n/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/7-Sequence-Number",
    category: "Crypto Blockchain",
  },
  {
    id: "8",
    title: "8 Playing Around with IDE",
    drive: "https://drive.google.com/file/d/1sj8okv5LWA27-EzD_kax7jL3SYZ4CJRy/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/8-Playing-Around-with-IDE",
    category: "Crypto Blockchain",
  },
  {
    id: "9",
    title: "9 QUIZ",
    drive: "https://drive.google.com/file/d/1dSBeUpVJgWYNKyLkjuLh4Nm4FieQwSqV/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/9-QUIZ",
    category: "Crypto Blockchain",
  },
  {
    id: "10",
    title: "10 Revisting Bitcoin Transaction",
    drive: "https://drive.google.com/file/d/1JLBIrfv-qy5QSrE-9apBlsW6YzZH8GP0/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/10-Revisting-Bitcoin-Transaction",
    category: "Crypto Blockchain",
  },
  {
    id: "11",
    title: "11 RAW Transaction",
    drive: "https://drive.google.com/file/d/12CyXvD3fja43X0lC_5yKyhNCnwlr8ScX/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/11-RAW-Transaction",
    category: "Crypto Blockchain",
  },
  {
    id: "12",
    title: "12 Creating Bitcoin Script",
    drive: "https://drive.google.com/file/d/1QkOKpczHnFPMQ5hWzTqTGg4liTaNy3pE/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/12-Creating-Bitcoin-Script",
    category: "Crypto Blockchain",
  },
  {
    id: "13",
    title: "13 Advanced Bitcoin Protocol",
    drive: "https://drive.google.com/file/d/1d-JCkVYbRadHWhC5iakQ79LlgsSk0y0x/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/13-Advanced-Bitcoin-Protocol",
    category: "Crypto Blockchain",
  },
  {
    id: "14",
    title: "14 Bitcoin Programming with BX",
    drive: "https://drive.google.com/file/d/1YKjIWZs-npTdtmpFZCHBYULGecdVjb9y/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/14-Bitcoin-Programming-with-BX",
    category: "Crypto Blockchain",
  },
  {
    id: "15",
    title: "15 Key Generation with BX",
    drive: "https://drive.google.com/file/d/1Tvcl5kv9HpLgVwlZS0PW7owQpts6S5iG/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/15-Key-Generation-with-BX",
    category: "Crypto Blockchain",
  },
  {
    id: "16",
    title: "16 Other Important BX Operations",
    drive: "https://drive.google.com/file/d/1g9COgUn1f9RqANJYVG2ijuOxSk5yb3Va/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/9-Bitcoin-Transaction-in-Depth/16-Other-Important-BX-Operations",
    category: "Crypto Blockchain",
  }
];