export const Data = [
  {
    id: "1",
    title: "Apa itu Financial Analysis",
    drive: "https://drive.google.com/file/d/1g4QlqrFEW768pEts671bWV7ZmqcYo89O",
    link: "/Halaman/page/5-ternak-uang/2/1",
    category: "Stock and Finance",
  },
  {
    id: "2",
    title: "Tentang Laporan Laba Rugi",
    drive: "https://drive.google.com/file/d/1mmAEopf677wqFQ_qWqCFztrBuXEMf6Sp",
    link: "/Halaman/page/5-ternak-uang/2/2",
    category: "Stock and Finance",
  },
  {
    id: "3",
    title: "Mengecek Kesehatan Perusahaan",
    drive: "https://drive.google.com/file/d/1MYkE5J8GGeY5UQoTtRh9w5gvpUrpWLnk",
    link: "/Halaman/page/5-ternak-uang/2/3",
    category: "Stock and Finance",
  },
  {
    id: "4",
    title: "Arus Kas Dalam Perusahaan",
    drive: "https://drive.google.com/file/d/1fLnGoNa-n3i8vmELh-cmgmOpy7YJufVT",
    link: "/Halaman/page/5-ternak-uang/2/4",
    category: "Stock and Finance",
  },
  {
    id: "5",
    title: "Kesimpulan Laporan Keuangan",
    drive: "https://drive.google.com/file/d/1F4Lt6KgsEWFF3YfSvB70jWxgZUAbbA-O",
    link: "/Halaman/page/5-ternak-uang/2/5",
    category: "Stock and Finance",
  },
  {
    id: "6",
    title: "Fungsi Rasio Keuangan",
    drive: "https://drive.google.com/file/d/1GbKGdkgetMZ5_U9kbR5hAz3H9lKQTXw7",
    link: "/Halaman/page/5-ternak-uang/2/6",
    category: "Stock and Finance",
  },
  {
    id: "7",
    title: "Sehat-DER",
    drive: "https://drive.google.com/file/d/1V0BXqH_V755Vz5cwK1uZbl8_DmLDcPhB",
    link: "/Halaman/page/5-ternak-uang/2/7",
    category: "Stock and Finance",
  },
  {
    id: "8",
    title: "Profitabilitas-NPM ROE",
    drive: "https://drive.google.com/file/d/1v3zG4-GDV4nwKTKENKODl0EnLxA6_xzY",
    link: "/Halaman/page/5-ternak-uang/2/8",
    category: "Stock and Finance",
  },
  {
    id: "9",
    title: "Growth-EPS",
    drive: "https://drive.google.com/file/d/1A4ZTWTPe34YKQjyg7flbkbkzOFjVM-eZ",
    link: "/Halaman/page/5-ternak-uang/2/9",
    category: "Stock and Finance",
  },
  {
    id: "10",
    title: "Value-PE , PBV",
    drive: "https://drive.google.com/file/d/1r1g7OFiFLvqTrIkF2LE4H-PhluFcVa5Q",
    link: "/Halaman/page/5-ternak-uang/2/10",
    category: "Stock and Finance",
  },
  {
    id: "11",
    title: "Rangkuman Rasio Keuangan",
    drive: "https://drive.google.com/file/d/1yD4E0quTo2HVbdoD-u9qaIld4si-Re7D",
    link: "/Halaman/page/5-ternak-uang/2/11",
    category: "Stock and Finance",
  },
  {
    id: "12",
    title: "Consumer Good Food and Beverage",
    drive: "https://drive.google.com/file/d/1XXArXSplMHykb6oHqWEtM61MbLqxo__a",
    link: "/Halaman/page/5-ternak-uang/2/12",
    category: "Stock and Finance",
  },
  {
    id: "13",
    title: "Property and Real Estate",
    drive: "https://drive.google.com/file/d/1epxahz2h_T5moPorr51bbd8pYB9JQL-i",
    link: "/Halaman/page/5-ternak-uang/2/13",
    category: "Stock and Finance",
  },
  {
    id: "14",
    title: "TLKM vs EXCL",
    drive: "https://drive.google.com/file/d/1YjQblLSSkAczPfy36uYnuZ9tQ6LHFkd0",
    link: "/Halaman/page/5-ternak-uang/2/14",
    category: "Stock and Finance",
  },
];