export const Data = [
  {
    id: "1",
    title: "1 Norway Cryptocurrency Ransom Case 2018",
    drive: "https://drive.google.com/file/d/1NpXIjHn5aS1Q74zUDbFO_zlX2pIg7fos/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/7-Monero-Anonymity/1-Norway-Cryptocurrency-Ransom-Case-2018",
    category: "Crypto Blockchain",
  },
  {
    id: "2",
    title: "2 History of Monero",
    drive: "https://drive.google.com/file/d/1DLTJYOBdSeqLBU46pHsHfGoFZPGefUV_/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/7-Monero-Anonymity/2-History-of-Monero",
    category: "Crypto Blockchain",
  },
  {
    id: "3",
    title: "3 Cryptocurrency Privacy Background",
    drive: "https://drive.google.com/file/d/1YL7uUZKZTZU-X0Ikvv5MQC9IIIw3FYTd/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/7-Monero-Anonymity/3-Cryptocurrency-Privacy-Background",
    category: "Crypto Blockchain",
  },
  {
    id: "4",
    title: "4 Anonimity Monero as Cryptocurrency",
    drive: "https://drive.google.com/file/d/17YxhcQZ9b6rIBUUXqoSOnFlWszb0TSt5/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/7-Monero-Anonymity/4-Anonimity-Monero-as-Cryptocurrency",
    category: "Crypto Blockchain",
  },
  {
    id: "5",
    title: "5 Monero Transaction Part 1",
    drive: "https://drive.google.com/file/d/1G9RpXLRrSbkPg38cscxhZvCB8V2oBHz-/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/7-Monero-Anonymity/5-Monero-Transaction-Part-1",
    category: "Crypto Blockchain",
  },
  {
    id: "6",
    title: "6 Monero Transaction Part 2",
    drive: "https://drive.google.com/file/d/1ikEEJ_GPam4HiKuN2AwAFDt2oTZBdeCE/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/7-Monero-Anonymity/6-Monero-Transaction-Part-2",
    category: "Crypto Blockchain",
  },
  {
    id: "7",
    title: "7 Known Anonymity Problems",
    drive: "https://drive.google.com/file/d/1GiXdl_vwQcNsoRct4SPTmgICiSSDg9Bm/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/7-Monero-Anonymity/7-Known-Anonymity-Problems",
    category: "Crypto Blockchain",
  },
  {
    id: "8",
    title: "8 Monero Ring Attack MRA",
    drive: "https://drive.google.com/file/d/1huPKXMFy_9VVRNFwQZrBj_wvXP-h3xhq/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/7-Monero-Anonymity/8-Monero-Ring-Attack-MRA",
    category: "Crypto Blockchain",
  },
  {
    id: "9",
    title: "9 Problems of Key Reuse",
    drive: "https://drive.google.com/file/d/1ASnN-Icp2ErpALLwqXHK8fVZhPv0Iczq/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/7-Monero-Anonymity/9-Problems-of-Key-Reuse",
    category: "Crypto Blockchain",
  }
];