export const Data = [
  {
    id: "1",
    title: "1 Norway Cryptocurrency Ransom Case 2018",
    drive: "https://drive.google.com/file/d/1PS8-_PUVkDC3lS4LWtxTTFShmPasqT7A",
    link: "/Halaman/page/3-crypto-blockchain/7-Monero-Anonymity/1-Norway-Cryptocurrency-Ransom-Case-2018",
    category: "Crypto Blockchain",
  },
  {
    id: "2",
    title: "2 History of Monero",
    drive: "https://drive.google.com/file/d/1_6w5G_41DbJeFXfCr_VM-k-HOumBWGXr",
    link: "/Halaman/page/3-crypto-blockchain/7-Monero-Anonymity/2-History-of-Monero",
    category: "Crypto Blockchain",
  },
  {
    id: "3",
    title: "3 Cryptocurrency Privacy Background",
    drive: "https://drive.google.com/file/d/1CKAbUnxoR24Yeq71Fb_oVd0i9Bj22pbk",
    link: "/Halaman/page/3-crypto-blockchain/7-Monero-Anonymity/3-Cryptocurrency-Privacy-Background",
    category: "Crypto Blockchain",
  },
  {
    id: "4",
    title: "4 Anonimity Monero as Cryptocurrency",
    drive: "https://drive.google.com/file/d/1Bd1o2Kq-BgsbqR3z1JKI8KtYUpYwUT4d",
    link: "/Halaman/page/3-crypto-blockchain/7-Monero-Anonymity/4-Anonimity-Monero-as-Cryptocurrency",
    category: "Crypto Blockchain",
  },
  {
    id: "5",
    title: "5 Monero Transaction Part 1",
    drive: "https://drive.google.com/file/d/1G3qbndxb2tpoPPDdZkbLMKjSuh2z48H0",
    link: "/Halaman/page/3-crypto-blockchain/7-Monero-Anonymity/5-Monero-Transaction-Part-1",
    category: "Crypto Blockchain",
  },
  {
    id: "6",
    title: "6 Monero Transaction Part 2",
    drive: "https://drive.google.com/file/d/1RUZDbqOXnNCo1SvvD7zhO6Cc9kkW4wHk",
    link: "/Halaman/page/3-crypto-blockchain/7-Monero-Anonymity/6-Monero-Transaction-Part-2",
    category: "Crypto Blockchain",
  },
  {
    id: "7",
    title: "7 Known Anonymity Problems",
    drive: "https://drive.google.com/file/d/1VvN0316tmGT3zkjef9SXqB1DToWYiPOE",
    link: "/Halaman/page/3-crypto-blockchain/7-Monero-Anonymity/7-Known-Anonymity-Problems",
    category: "Crypto Blockchain",
  },
  {
    id: "8",
    title: "8 Monero Ring Attack MRA",
    drive: "https://drive.google.com/file/d/13GdWjmjEIOKe6cSezrqJEu54QrMHn4TN",
    link: "/Halaman/page/3-crypto-blockchain/7-Monero-Anonymity/8-Monero-Ring-Attack-MRA",
    category: "Crypto Blockchain",
  },
  {
    id: "9",
    title: "9 Problems of Key Reuse",
    drive: "https://drive.google.com/file/d/1besto8_D1QClrL6ewbgU9cGFW3jsManV",
    link: "/Halaman/page/3-crypto-blockchain/7-Monero-Anonymity/9-Problems-of-Key-Reuse",
    category: "Crypto Blockchain",
  }
];