export const Data = [
  {
    id: "1",
    title: "1 Introduction",
    drive: "https://drive.google.com/file/d/16qQP8nsEoAsX680nWfbWSbNnIGUGVw05/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/1-Introduction",
    category: "Crypto Blockchain",
  },
  {
    id: "2",
    title: "2 Sejarah Singkat Ethereum",
    drive: "https://drive.google.com/file/d/1vAblxmQuIV3K4doOlnAS5LxTVjcTqFtG/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/2-Sejarah-Singkat-Ethereum",
    category: "Crypto Blockchain",
  },
  {
    id: "3",
    title: "3 Apa itu Ethereum",
    drive: "https://drive.google.com/file/d/1DHLKfsVFnVjdJGrxASEmRLeeND6M1WpT/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/3-Apa-itu-Ethereum",
    category: "Crypto Blockchain",
  },
  {
    id: "4",
    title: "4 Berinteraksi dengan Ethereum",
    drive: "https://drive.google.com/file/d/1D-8c28dAe_C2NGiK9YGy14pYzqzeQ8cx/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/4-Berinteraksi-dengan-Ethereum",
    category: "Crypto Blockchain",
  },
  {
    id: "5",
    title: "5 Meta Mask Setup",
    drive: "https://drive.google.com/file/d/1NAafuuFYqF2zS9-MqCMD5T0iv19w3Moq/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/5-Meta-Mask-Setup",
    category: "Crypto Blockchain",
  },
  {
    id: "6",
    title: "6 Ethereum Account",
    drive: "https://drive.google.com/file/d/1lqoZD-bsuuviyhFFk_2Q8tNTanq1Vtwx/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/6-Ethereum-Account",
    category: "Crypto Blockchain",
  },
  {
    id: "7",
    title: "7 Cara Mendapatkan Testnet Eth",
    drive: "https://drive.google.com/file/d/1v_mB7YAWOZElwFvZAb_uJuQ_RHVdHz9x/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/7-Cara-Mendapatkan-Testnet-Eth",
    category: "Crypto Blockchain",
  },
  {
    id: "8",
    title: "8 Transaksi",
    drive: "https://drive.google.com/file/d/1Kg6MYWfYa2VLCXdflFvv2bUdHPUS5cr0/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/8-Transaksi",
    category: "Crypto Blockchain",
  },
  {
    id: "9",
    title: "9 Kenapa ada waktu tunggu transaksi",
    drive: "https://drive.google.com/file/d/1YoL_4DkYGk9WDx_tETnYNNB63CVlQ2Wc/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/9-Kenapa-ada-waktu-tunggu-transaksi",
    category: "Crypto Blockchain",
  },
  {
    id: "10",
    title: "10 Basic Blockchain",
    drive: "https://drive.google.com/file/d/1q9v4mizccR8xutsWP0h76MesQm-B_2pl/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/10-Basic-Blockchain",
    category: "Crypto Blockchain",
  },
  {
    id: "11",
    title: "11 Block Time",
    drive: "https://drive.google.com/file/d/1lgKfctn31AdqdNk-dW4WszELvgtHmjJd/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/11-Block-Time",
    category: "Crypto Blockchain",
  },
  {
    id: "12",
    title: "12 Smart Contract",
    drive: "https://drive.google.com/file/d/1CS8ere_6SecwDetKbN6xbUtZARkEk-0G/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/12-Smart-Contract",
    category: "Crypto Blockchain",
  },
  {
    id: "13",
    title: "13 Solidity",
    drive: "https://drive.google.com/file/d/15gsEHvVHXEytxhZJ1ALoZZ43l-Ia18xM/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/13-Solidity",
    category: "Crypto Blockchain",
  },
  {
    id: "14",
    title: "14 Remix Interface",
    drive: "https://drive.google.com/file/d/1uiLvTBo76hRdvzDlK21q8MXv4eJbtduB/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/14-Remix-Interface",
    category: "Crypto Blockchain",
  },
  {
    id: "15",
    title: "15 Contract Pertama Kita",
    drive: "https://drive.google.com/file/d/1mV-VFWZ9DufUv2YDqpYTqfj3DQUnvSuT/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/15-Contract-Pertama-Kita",
    category: "Crypto Blockchain",
  },
  {
    id: "16",
    title: "16 Struktur Contract",
    drive: "https://drive.google.com/file/d/1d3OBpcULsY9frX6oU2qTt2O-1tEJ1xJ1/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/16-Struktur-Contract",
    category: "Crypto Blockchain",
  },
  {
    id: "17",
    title: "17 Deklarasi Function",
    drive: "https://drive.google.com/file/d/18cxlemWMeYdUmJFbpBKcbQD9777R5e07/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/17-Deklarasi-Function",
    category: "Crypto Blockchain",
  },
  {
    id: "18",
    title: "18 Testing and Deploying Contract di Remix",
    drive: "https://drive.google.com/file/d/1DhJ7X1olxEoPxxUAD9OLjrGfWrGbbpJ2/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/18-Testing-and-Deploying-Contract-di-Remix",
    category: "Crypto Blockchain",
  },
  {
    id: "19",
    title: "19 Re deploy Smart Contract",
    drive: "https://drive.google.com/file/d/17iVNambcG-jUcdLUSe6k6n8hLZ7rdU0V/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/19-Re-deploy-Smart-Contract",
    category: "Crypto Blockchain",
  },
  {
    id: "20",
    title: "20 BTS Smart Contract Deployment",
    drive: "https://drive.google.com/file/d/13QYfZ6J_gT2oCwBFDPDlIXYGddrxTn--/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/20-BTS-Smart-Contract-Deployment",
    category: "Crypto Blockchain",
  },
  {
    id: "21",
    title: "21 Menjalankan Function in depth",
    drive: "https://drive.google.com/file/d/1vlyi9PKnU14f5sYmM1pFbifTGdvhhCAG/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/21-Menjalankan-Function-in-depth",
    category: "Crypto Blockchain",
  },
  {
    id: "22",
    title: "22 Wei vs Ether",
    drive: "https://drive.google.com/file/d/1NNzOI75WuT9zzrjuAoQ3o3l6eIek9sdQ/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/22-Wei-vs-Ether",
    category: "Crypto Blockchain",
  },
  {
    id: "23",
    title: "23 Gas dan Transaksi",
    drive: "https://drive.google.com/file/d/1OcFKqafqecOjuBhuZIp24Ry7_55NZA8_/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/23-Gas-dan-Transaksi",
    category: "Crypto Blockchain",
  },
  {
    id: "24",
    title: "24 Mnemonic Phrases",
    drive: "https://drive.google.com/file/d/1lw20Q1a1uXtOaWxO7PH1VErchDQ290TP/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/24-Mnemonic-Phrases",
    category: "Crypto Blockchain",
  },
  {
    id: "25",
    title: "25 Setup Mengeluarkan Smart Contract dari Remix",
    drive: "https://drive.google.com/file/d/1STDplF-d215oWQCpcF5xJBnEMgKORLFq/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/25-Setup-Mengeluarkan-Smart-Contract-dari-Remix",
    category: "Crypto Blockchain",
  },  {
    id: "26",
    title: "26 Testing Architecture",
    drive: "https://drive.google.com/file/d/1XWyp2XfQ6HNx6zaaR3SLhSr4nddXTNQY/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/26-Testing-Architecture",
    category: "Crypto Blockchain",
  },
  {
    id: "27",
    title: "27 Testing Modules",
    drive: "https://drive.google.com/file/d/1r8DhBrKVayO20oWQ2q2KSpOFtQRTn8Fn/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/27-Testing-Modules",
    category: "Crypto Blockchain",
  },
  {
    id: "28",
    title: "28 Mocha Intro",
    drive: "https://drive.google.com/file/d/18RvrJfLLm7P-uuQs8BMgRZJPTIDCJLXB/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/28-Mocha-Intro",
    category: "Crypto Blockchain",
  },
  {
    id: "29",
    title: "29 Update Compiler untuk Solidity v0 8 19",
    drive: "https://drive.google.com/file/d/1E2ivo7OMIlJN2lNUs4Kk515IH0lJ9Ujx/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/29-Update-Compiler-untuk-Solidity-v0-8-19",
    category: "Crypto Blockchain",
  },
  {
    id: "30",
    title: "30 Flow Mocha Test",
    drive: "https://drive.google.com/file/d/1QeMTX-z0SigbE7Ze3SUt7vzwKqRyfMm-/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/30-Flow-Mocha-Test",
    category: "Crypto Blockchain",
  },
  {
    id: "31",
    title: "31 Ganache Accounts",
    drive: "https://drive.google.com/file/d/1vJ486H2Cl8WdN7WITtpdd7CMkLPE3fDD/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/31-Ganache-Accounts",
    category: "Crypto Blockchain",
  },
  {
    id: "32",
    title: "32 Contract Deployment dengan Web3",
    drive: "https://drive.google.com/file/d/1VAh3CqaNjYl80jKGL-eIbtYAZXNEinlS/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/32-Contract-Deployment-dengan-Web3",
    category: "Crypto Blockchain",
  },
  {
    id: "33",
    title: "33 Contract Assertion",
    drive: "https://drive.google.com/file/d/18aHsXCLJGQnw3pUN0tNIplMZJvlVtsm-/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/33-Contract-Assertion",
    category: "Crypto Blockchain",
  },
  {
    id: "34",
    title: "34 Deployment dengan Infura",
    drive: "https://drive.google.com/file/d/15622NzFM0WV1BrqJAou7QGbgmGqhO5ks/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/34-Deployment-dengan-Infura",
    category: "Crypto Blockchain",
  },
  {
    id: "35",
    title: "35 Wallet Provider Setup",
    drive: "https://drive.google.com/file/d/1OT7uUxNi_mApNBpqFPfXOGsj0U51mcae/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/35-Wallet-Provider-Setup",
    category: "Crypto Blockchain",
  },
  {
    id: "36",
    title: "36 Deploy ke Goerli",
    drive: "https://drive.google.com/file/d/1iZabqZWUj50xHAwmlrBNASwUpw_oi6UQ/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/36-Deploy-ke-Goerli",
    category: "Crypto Blockchain",
  },
  {
    id: "37",
    title: "37 Deployed Contracts in Remix",
    drive: "https://drive.google.com/file/d/19cqEX3VpatYHV4zZU721xGZ9ffryOnJ1/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/37-Deployed-Contracts-in-Remix",
    category: "Crypto Blockchain",
  },
  {
    id: "38",
    title: "38 Smart Contract Design",
    drive: "https://drive.google.com/file/d/1LH6l1qmhFcGZsLyvbJkcyXtEM-9_8LIE/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/38-Smart-Contract-Design",
    category: "Crypto Blockchain",
  },
  {
    id: "39",
    title: "39 Solidity Basic Data Types",
    drive: "https://drive.google.com/file/d/1GDfIttKKDBhh-k_HPsOM4zt4p4bOuhnL/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/39-Solidity-Basic-Data-Types",
    category: "Crypto Blockchain",
  },
  {
    id: "40",
    title: "40 Assign Manager Enter Lottery Flow",
    drive: "https://drive.google.com/file/d/1vEMVLgLCvURBNgeTPb9gWysvmDO8q_sP/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/40-Assign-Manager-Enter-Lottery-Flow",
    category: "Crypto Blockchain",
  },
  {
    id: "41",
    title: "41 Assign Players Testing",
    drive: "https://drive.google.com/file/d/1RpjcJFtNonVUaMPVJCBdrV4MsIy4rQRM/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/41-Assign-Players-Testing",
    category: "Crypto Blockchain",
  },
  {
    id: "42",
    title: "42 Validasi dengan Require",
    drive: "https://drive.google.com/file/d/1RZ0qzoFEe17o9bN2SF7SMsc7TkI08s2S/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/42-Validasi-dengan-Require",
    category: "Crypto Blockchain",
  },
  {
    id: "43",
    title: "43 Memilih Pemenang Lottery",
    drive: "https://drive.google.com/file/d/1KVtNmhkopwO_uIV_vVivU7Q2AlBIpOjU/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/43-Memilih-Pemenang-Lottery",
    category: "Crypto Blockchain",
  },
  {
    id: "44",
    title: "44 Kirim Hadiah Reset Lottery",
    drive: "https://drive.google.com/file/d/1d7cKB399Qk8IbKjfKLTeBmNDtInpCymf/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/44-Kirim-Hadiah-Reset-Lottery",
    category: "Crypto Blockchain",
  },
  {
    id: "45",
    title: "45 Function Modifiers",
    drive: "https://drive.google.com/file/d/1oWoS3-ah8FS_o1cX53L9F5rIPdLL5tQ7/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/45-Function-Modifiers",
    category: "Crypto Blockchain",
  },
  {
    id: "46",
    title: "46 Deploying to Sepolia Testnet plus Challenge",
    drive: "https://drive.google.com/file/d/1CD9Id3p1ls4YH2D0HFeOEd3bIDhAhOob/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/46-Deploying-to-Sepolia-Testnet-plus-Challenge",
    category: "Crypto Blockchain",
  },
  {
    id: "47",
    title: "47 Apa itu ERC 20",
    drive: "https://drive.google.com/file/d/1hqLwgvw1jds0n-YRn1jf4IL2QiZenWEh/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/47-Apa-itu-ERC-20",
    category: "Crypto Blockchain",
  },
  {
    id: "48",
    title: "48 ERC20 Smart Contract",
    drive: "https://drive.google.com/file/d/1QC7SA65IQ1XCW32mgvocvvoOqzUPG75J/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/48-ERC20-Smart-Contract",
    category: "Crypto Blockchain",
  },
  {
    id: "49",
    title: "49 Add Liquidity Pool",
    drive: "https://drive.google.com/file/d/148d5lMXNuyUfG1K7v626F-nB-o9_Li6T/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/49-Add-Liquidity-Pool",
    category: "Crypto Blockchain",
  },
  {
    id: "50",
    title: "50 Introduction to Oracles",
    drive: "https://drive.google.com/file/d/1lRsp1UuUkwBOf7B_uCRfTqKGH442WOyx/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/50-Introduction-to-Oracles",
    category: "Crypto Blockchain",
  },
  {
    id: "51",
    title: "51 The Oracle Problem Types of Oracles",
    drive: "https://drive.google.com/file/d/1UqS66n85MwoJ7zK5qCJh7HgrPVhpkBa7/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/51-The-Oracle-Problem-Types-of-Oracles",
    category: "Crypto Blockchain",
  },
  {
    id: "52",
    title: "52 Chainlink VRF LINK Faucet",
    drive: "https://drive.google.com/file/d/154yndU2jYKHfRQFTiF3CjxqtqzFooyWI/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/52-Chainlink-VRF-LINK-Faucet",
    category: "Crypto Blockchain",
  },
  {
    id: "53",
    title: "53 Chainlink VRF Subscription Method",
    drive: "https://drive.google.com/file/d/1X--kuf8rga6o862oM92JQWWwPEUGfOoT/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/53-Chainlink-VRF-Subscription-Method",
    category: "Crypto Blockchain",
  },
  {
    id: "54",
    title: "54 Importing Contract",
    drive: "https://drive.google.com/file/d/1r12odtDXled5KAXi4u_TjRalZJyrSviF/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/54-Importing-Contract",
    category: "Crypto Blockchain",
  },
  {
    id: "55",
    title: "55 Hardhat Tutorial Compile Deploy Testing",
    drive: "https://drive.google.com/file/d/1z_O0i8i0lXiBKz5g5Qhov7A895s4Zgy0/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/55-Hardhat-Tutorial-Compile-Deploy-Testing",
    category: "Crypto Blockchain",
  },
];
