export const Data = [
  {
    id: "1",
    title: "1 Introduction",
    drive: "https://drive.google.com/file/d/1YLptkdaGu8Ew4ozGyPHGA0Q-p-O6yUna/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/1-Introduction",
    category: "Crypto Blockchain",
  },
  {
    id: "2",
    title: "2 Sejarah Singkat Ethereum",
    drive: "https://drive.google.com/file/d/1YyBAtZBcvplxEPVmX581ZeAlZgO4tZaZ/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/2-Sejarah-Singkat-Ethereum",
    category: "Crypto Blockchain",
  },
  {
    id: "3",
    title: "3 Apa itu Ethereum",
    drive: "https://drive.google.com/file/d/1YwTDM2QN34HXXn4fUc2RG_dyEMEvTw8M/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/3-Apa-itu-Ethereum",
    category: "Crypto Blockchain",
  },
  {
    id: "4",
    title: "4 Berinteraksi dengan Ethereum",
    drive: "https://drive.google.com/file/d/1Yq0s99F5jCBcNL42EopIu3BIomKFu-n-/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/4-Berinteraksi-dengan-Ethereum",
    category: "Crypto Blockchain",
  },
  {
    id: "5",
    title: "5 Meta Mask Setup",
    drive: "https://drive.google.com/file/d/1YiY5Q3WzF1LuzSJ7fPSNfWMO9FTVQgQr/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/5-Meta-Mask-Setup",
    category: "Crypto Blockchain",
  },
  {
    id: "6",
    title: "6 Ethereum Account",
    drive: "https://drive.google.com/file/d/1Yga_-IFplL16pL5RuuofRbgnYijJ2EI9/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/6-Ethereum-Account",
    category: "Crypto Blockchain",
  },
  {
    id: "7",
    title: "7 Cara Mendapatkan Testnet Eth",
    drive: "https://drive.google.com/file/d/1YZ44xMbDyuIeBBQXi1VRv7n77baNQLFB/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/7-Cara-Mendapatkan-Testnet-Eth",
    category: "Crypto Blockchain",
  },
  {
    id: "8",
    title: "8 Transaksi",
    drive: "https://drive.google.com/file/d/1eEn-q0_nUOR-hIHycEijG0nJ1hobfqpX/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/8-Transaksi",
    category: "Crypto Blockchain",
  },
  {
    id: "9",
    title: "9 Kenapa ada waktu tunggu transaksi",
    drive: "https://drive.google.com/file/d/1etSnobXa1k-nb0txqo27-qJijYupSZ_V/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/9-Kenapa-ada-waktu-tunggu-transaksi",
    category: "Crypto Blockchain",
  },
  {
    id: "10",
    title: "10 Basic Blockchain",
    drive: "https://drive.google.com/file/d/1eso9vsVBQ6lXLNSUza4_9-KeM278oSD6/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/10-Basic-Blockchain",
    category: "Crypto Blockchain",
  },
  {
    id: "11",
    title: "11 Block Time",
    drive: "https://drive.google.com/file/d/1ekJxikBJ5dTw9hKoywnSQ9KH696MInXB/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/11-Block-Time",
    category: "Crypto Blockchain",
  },
  {
    id: "12",
    title: "12 Smart Contract",
    drive: "https://drive.google.com/file/d/1eePsutxbY8kXxrTsO6XJFOKfd36pohVS/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/12-Smart-Contract",
    category: "Crypto Blockchain",
  },
  {
    id: "13",
    title: "13 Solidity",
    drive: "https://drive.google.com/file/d/1eck1w0UiBGg0z6KQWUnfMjh0FbUb5Abm/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/13-Solidity",
    category: "Crypto Blockchain",
  },
  {
    id: "14",
    title: "14 Remix Interface",
    drive: "https://drive.google.com/file/d/1eTZ9dDxeV4sB1OEChyrejkCGiMtGo6hf/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/14-Remix-Interface",
    category: "Crypto Blockchain",
  },
  {
    id: "15",
    title: "15 Contract Pertama Kita",
    drive: "https://drive.google.com/file/d/1eQVnwll3jwXHR5_2EUztBaoXje__vcsh/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/15-Contract-Pertama-Kita",
    category: "Crypto Blockchain",
  },
  {
    id: "16",
    title: "16 Struktur Contract",
    drive: "https://drive.google.com/file/d/1eKt5RHjSWYo7LIZRbuT6DFLoNMqzNCyd/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/16-Struktur-Contract",
    category: "Crypto Blockchain",
  },
  {
    id: "17",
    title: "17 Deklarasi Function",
    drive: "https://drive.google.com/file/d/1eK1r7XjmBP7Ej5MWEPVd6FhFCvkooLBn/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/17-Deklarasi-Function",
    category: "Crypto Blockchain",
  },
  {
    id: "18",
    title: "18 Testing and Deploying Contract di Remix",
    drive: "https://drive.google.com/file/d/1fOZUgrnjsoVBAJ8anPN8txsK-CUncUhr/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/18-Testing-and-Deploying-Contract-di-Remix",
    category: "Crypto Blockchain",
  },
  {
    id: "19",
    title: "19 Re deploy Smart Contract",
    drive: "https://drive.google.com/file/d/1fOQpbOAoo-dJK5X1b6ChFDUApeS6cNyx/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/19-Re-deploy-Smart-Contract",
    category: "Crypto Blockchain",
  },
  {
    id: "20",
    title: "20 BTS Smart Contract Deployment",
    drive: "https://drive.google.com/file/d/1fNqVbPQJpPHdgMSfpK-V9EwgwWaMnpUe/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/20-BTS-Smart-Contract-Deployment",
    category: "Crypto Blockchain",
  },
  {
    id: "21",
    title: "21 Menjalankan Function in depth",
    drive: "https://drive.google.com/file/d/1fMHLGjw0YZQ7aWXb09g_mr7UnyQeR-cv/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/21-Menjalankan-Function-in-depth",
    category: "Crypto Blockchain",
  },
  {
    id: "22",
    title: "22 Wei vs Ether",
    drive: "https://drive.google.com/file/d/1fJ3RdjlfIESJx2mPySND4LPbPsaqsbeN/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/22-Wei-vs-Ether",
    category: "Crypto Blockchain",
  },
  {
    id: "23",
    title: "23 Gas dan Transaksi",
    drive: "https://drive.google.com/file/d/1fFq5KBWOl6q5unYVKRzjPOYsvv0ac6IM/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/23-Gas-dan-Transaksi",
    category: "Crypto Blockchain",
  },
  {
    id: "24",
    title: "24 Mnemonic Phrases",
    drive: "https://drive.google.com/file/d/1fCX_RW7tX3LETKiC7cFM_YM31BCiRLbU/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/24-Mnemonic-Phrases",
    category: "Crypto Blockchain",
  },
  {
    id: "25",
    title: "25 Setup Mengeluarkan Smart Contract dari Remix",
    drive: "https://drive.google.com/file/d/1fBcK2WemUO9e_6viQ-0KNfpb2EzRwC4a/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/25-Setup-Mengeluarkan-Smart-Contract-dari-Remix",
    category: "Crypto Blockchain",
  },  {
    id: "26",
    title: "26 Testing Architecture",
    drive: "https://drive.google.com/file/d/1f8v0IoC70cLPfSdmvmhGlupnEvDnhAhN/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/26-Testing-Architecture",
    category: "Crypto Blockchain",
  },
  {
    id: "27",
    title: "27 Testing Modules",
    drive: "https://drive.google.com/file/d/1fWMbOLKSqXPfjcpEPd-DKp3M8cwylD0k/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/27-Testing-Modules",
    category: "Crypto Blockchain",
  },
  {
    id: "28",
    title: "28 Mocha Intro",
    drive: "https://drive.google.com/file/d/1fRGZETt-Pggt2iM9eEgoahQJbS6-NnzD/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/28-Mocha-Intro",
    category: "Crypto Blockchain",
  },
  {
    id: "29",
    title: "29 Update Compiler untuk Solidity v0 8 19",
    drive: "https://drive.google.com/file/d/1f5x-gy8fQ7OQSg3h2xLTQXGgplRE3hk_/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/29-Update-Compiler-untuk-Solidity-v0-8-19",
    category: "Crypto Blockchain",
  },
  {
    id: "30",
    title: "30 Flow Mocha Test",
    drive: "https://drive.google.com/file/d/1ezRh7YXhwS1PsEQggLn8B-v1pejQeZH6/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/30-Flow-Mocha-Test",
    category: "Crypto Blockchain",
  },
  {
    id: "31",
    title: "31 Ganache Accounts",
    drive: "https://drive.google.com/file/d/1fQB_2YxI2cVjQUBeCk2nYiN4pwHlCDg1/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/31-Ganache-Accounts",
    category: "Crypto Blockchain",
  },
  {
    id: "32",
    title: "32 Contract Deployment dengan Web3",
    drive: "https://drive.google.com/file/d/1fWScI6y_ZncCqkUfjMUKzXzt3ybtkKNO/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/32-Contract-Deployment-dengan-Web3",
    category: "Crypto Blockchain",
  },
  {
    id: "33",
    title: "33 Contract Assertion",
    drive: "https://drive.google.com/file/d/1gAR9wbJnVGCIO45Xb7MXVnco4QyF4Hl1/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/33-Contract-Assertion",
    category: "Crypto Blockchain",
  },
  {
    id: "34",
    title: "34 Deployment dengan Infura",
    drive: "https://drive.google.com/file/d/1g8q3cnHLUCC3Ry8Bpn3gtJIrHjfzAIg_/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/34-Deployment-dengan-Infura",
    category: "Crypto Blockchain",
  },
  {
    id: "35",
    title: "35 Wallet Provider Setup",
    drive: "https://drive.google.com/file/d/1g3OpFXXs_F_dMRofhT0M7Kyml7nysxU-/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/35-Wallet-Provider-Setup",
    category: "Crypto Blockchain",
  },
  {
    id: "36",
    title: "36 Deploy ke Goerli",
    drive: "https://drive.google.com/file/d/1fvD9w-QqgD033zAvW7g60yo068B2nT1l/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/36-Deploy-ke-Goerli",
    category: "Crypto Blockchain",
  },
  {
    id: "37",
    title: "37 Deployed Contracts in Remix",
    drive: "https://drive.google.com/file/d/1fu81yZ1J4LcJWoXAih6off-uBfURynvj/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/37-Deployed-Contracts-in-Remix",
    category: "Crypto Blockchain",
  },
  {
    id: "38",
    title: "38 Smart Contract Design",
    drive: "https://drive.google.com/file/d/1fpXm3ePsfHC506H4ftynY8Koe6oo_yK1/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/38-Smart-Contract-Design",
    category: "Crypto Blockchain",
  },
  {
    id: "39",
    title: "39 Solidity Basic Data Types",
    drive: "https://drive.google.com/file/d/1fko8_7MqijcgA3Y2MdOrl0MMzXuDimdk/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/39-Solidity-Basic-Data-Types",
    category: "Crypto Blockchain",
  },
  {
    id: "40",
    title: "40 Assign Manager Enter Lottery Flow",
    drive: "https://drive.google.com/file/d/1fkXCcxto6KvwddhviIP50UBmmmAXaM8o/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/40-Assign-Manager-Enter-Lottery-Flow",
    category: "Crypto Blockchain",
  },
  {
    id: "41",
    title: "41 Assign Players Testing",
    drive: "https://drive.google.com/file/d/1fiYmIitCi5yqtoNgG8NLevnYS6h_ahob/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/41-Assign-Players-Testing",
    category: "Crypto Blockchain",
  },
  {
    id: "42",
    title: "42 Validasi dengan Require",
    drive: "https://drive.google.com/file/d/1fhRMoXaz9PzG1qNCAdcxY-0G_kQqs6x5/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/42-Validasi-dengan-Require",
    category: "Crypto Blockchain",
  },
  {
    id: "43",
    title: "43 Memilih Pemenang Lottery",
    drive: "https://drive.google.com/file/d/1gsAWv80nMDEyyT8SlWjhqdlIS-o-q54w/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/43-Memilih-Pemenang-Lottery",
    category: "Crypto Blockchain",
  },
  {
    id: "44",
    title: "44 Kirim Hadiah Reset Lottery",
    drive: "https://drive.google.com/file/d/1gmyFT4HsXE0tQ4hP5Cdh2MDBzfv-jmPv/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/44-Kirim-Hadiah-Reset-Lottery",
    category: "Crypto Blockchain",
  },
  {
    id: "45",
    title: "45 Function Modifiers",
    drive: "https://drive.google.com/file/d/1ghf48f5mh-OthS3eMKaNrWK96T-jRMb2/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/45-Function-Modifiers",
    category: "Crypto Blockchain",
  },
  {
    id: "46",
    title: "46 Deploying to Sepolia Testnet plus Challenge",
    drive: "https://drive.google.com/file/d/1g_T5S8clEJWltP0jYBMyJfNvcasLuK8p/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/46-Deploying-to-Sepolia-Testnet-plus-Challenge",
    category: "Crypto Blockchain",
  },
  {
    id: "47",
    title: "47 Apa itu ERC 20",
    drive: "https://drive.google.com/file/d/1gOpvXsj9HRI7gsD3sPC3L28nzKLnR5rM/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/47-Apa-itu-ERC-20",
    category: "Crypto Blockchain",
  },
  {
    id: "48",
    title: "48 ERC20 Smart Contract",
    drive: "https://drive.google.com/file/d/1h2cP9X0Qkbt6oajuP6QS-FfEpjY3BGSd/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/48-ERC20-Smart-Contract",
    category: "Crypto Blockchain",
  },
  {
    id: "49",
    title: "49 Add Liquidity Pool",
    drive: "https://drive.google.com/file/d/1gLwm9HjUdm9VKDQamOi3c5srwSk5860m/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/49-Add-Liquidity-Pool",
    category: "Crypto Blockchain",
  },
  {
    id: "50",
    title: "50 Introduction to Oracles",
    drive: "https://drive.google.com/file/d/1gL1_vvsN4V8K3rLXGhBVuJwZI5BcG1Qc/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/50-Introduction-to-Oracles",
    category: "Crypto Blockchain",
  },
  {
    id: "51",
    title: "51 The Oracle Problem Types of Oracles",
    drive: "https://drive.google.com/file/d/1h2ZlNshUUndcglOK4tQN5Q7U0HUNcii4/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/51-The-Oracle-Problem-Types-of-Oracles",
    category: "Crypto Blockchain",
  },
  {
    id: "52",
    title: "52 Chainlink VRF LINK Faucet",
    drive: "https://drive.google.com/file/d/1gHVGbQWdj1GsvU6uAPfTi7vTEPlCM4D1/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/52-Chainlink-VRF-LINK-Faucet",
    category: "Crypto Blockchain",
  },
  {
    id: "53",
    title: "53 Chainlink VRF Subscription Method",
    drive: "https://drive.google.com/file/d/1gyh43O_YosE_Z2qXyCpf5w1Y2s-8y3C4/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/53-Chainlink-VRF-Subscription-Method",
    category: "Crypto Blockchain",
  },
  {
    id: "54",
    title: "54 Importing Contract",
    drive: "https://drive.google.com/file/d/1gtOUqYDC97S0aFV_BLOy1wCfN5GvyyU0/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/54-Importing-Contract",
    category: "Crypto Blockchain",
  },
  {
    id: "55",
    title: "55 Hardhat Tutorial Compile Deploy Testing",
    drive: "https://drive.google.com/file/d/1h3_1gMH3ZiBct7hEFiXdMSEMELAuhY1a/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/55-Hardhat-Tutorial-Compile-Deploy-Testing",
    category: "Crypto Blockchain",
  },
  {
    id: "56",
    title: "56 Call Delegate",
    drive: "https://drive.google.com/file/d/1dJn-4WKvnmj6Q622Jem2nZzknoi-k47g/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/56 Call Delegate",
    category: "Crypto Blockchain",
  },
  {
    id: "57",
    title: "57 Jenis Unit",
    drive: "https://drive.google.com/file/d/1dNTvAhnC6FAWbe7ig30HJ0sEzI3fC4H4/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/57 Jenis Unit",
    category: "Crypto Blockchain",
  },
  {
    id: "58",
    title: "58 Smart Contrack Dev",
    drive: "https://drive.google.com/file/d/1dJn-4WKvnmj6Q622Jem2nZzknoi-k47g/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/58 Smart Contrack Dev",
    category: "Crypto Blockchain",
  },
  {
    id: "59",
    title: "59 Delegate Call Attack",
    drive: "https://drive.google.com/file/d/1dNTvAhnC6FAWbe7ig30HJ0sEzI3fC4H4/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/59 Delegate Call Attack",
    category: "Crypto Blockchain",
  },
  {
    id: "60",
    title: "60 Fallback Functions",
    drive: "https://drive.google.com/file/d/1dYNuuucv6F9kP6YYBjP_w-WG8PlKmiXT/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/60 Fallback Functions",
    category: "Crypto Blockchain",
  },
  {
    id: "61",
    title: "61 Gambaran Storage Slot Solidity",
    drive: "https://drive.google.com/file/d/1dTvgyhlPYFlQPeyQopXo0Wd92GISwwD3/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/61 Gambaran Storage Slot Solidity",
    category: "Crypto Blockchain",
  },
  {
    id: "62",
    title: "Assignment 1 ToDo",
    drive: "https://drive.google.com/file/d/1dTmtFbk0ImfKmt6jYyFH3EAs2QeO5sOP/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/62 Assignment 1 ToDo",
    category: "Crypto Blockchain",
  },
  {
    id: "63",
    title: "63 Intro to Algorithm and Data Types",
    drive: "https://drive.google.com/file/d/1dbPv_r-oI_rES5H2GdkbhwjYH_db3ZM2/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/63 Intro to Algorithm and Data Types",
    category: "Crypto Blockchain",
  },
  {
    id: "64",
    title: "64 Solidity and Protocol",
    drive: "https://drive.google.com/file/d/1disyCAQL_Ao9DnBNFSfDJ2nabnEKT_M9/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/64 Solidity and Protocol",
    category: "Crypto Blockchain",
  },
  {
    id: "65",
    title: "65 Verify Contract Whit Hardhat & Thirdweb",
    drive: "https://drive.google.com/file/d/1dkkNVgfBRVUHYnTjrKRH5olHF5xhYmTb/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/65 Verify Contract Whit Hardhat & Thirdweb",
    category: "Crypto Blockchain",
  },
  {
    id: "66",
    title: "66 Basic Uniswap V2",
    drive: "https://drive.google.com/file/d/1dxvVEQo6YPVJY15rOGh0rZgoQKNnZ1ae/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/66 Basic Uniswap V2",
    category: "Crypto Blockchain",
  },
  {
    id: "67",
    title: "67 ERC20 Tax Token",
    drive: "https://drive.google.com/file/d/1e2EuykxYg-fttYLa7-sqos8ypgoRjTQN/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/67 ERC20 Tax Token",
    category: "Crypto Blockchain",
  },
  {
    id: "68",
    title: "68 Disperse App Batch Transfer",
    drive: "https://drive.google.com/file/d/1e4n4qpqd6WQ2Y-YuNHTiiGczEbO3KM73/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/68 Disperse App Batch Transfer",
    category: "Crypto Blockchain",
  },
  {
    id: "69",
    title: "69 Merkle-Airdrop",
    drive: "https://drive.google.com/file/d/1eATMmNfWZibw4rCyTU3GLwfQmOqrQ60b/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/1-Smart-Contract-Development/69 Merkle-Airdrop",
    category: "Crypto Blockchain",
  },
];
