export const Data = [
  {
    id: "1",
    title: "Apa itu Aksi Korporasi",
    drive: "https://drive.google.com/file/d/1jZVSatkERICARfJjoakU1cg8eubuVLvf",
    link: "/Halaman/page/5-ternak-uang/6/1",
    category: "Stock and Finance",
  },
  {
    id: "2",
    title: "Initial Public Offering",
    drive: "https://drive.google.com/file/d/11k3GO49ktISjDV7HPENV4qavebtvCNp5",
    link: "/Halaman/page/5-ternak-uang/6/2",
    category: "Stock and Finance",
  },
  {
    id: "3",
    title: "Dividen",
    drive: "https://drive.google.com/file/d/1vO_Rz0wRRjUWribGrcFEOVs-OvmtgvAw",
    link: "/Halaman/page/5-ternak-uang/6/3",
    category: "Stock and Finance",
  },
  {
    id: "4",
    title: "Rights Issue",
    drive: "https://drive.google.com/file/d/1E0Y-nmjM8HleEvgVpJ59cDc9O_QhJXaA",
    link: "/Halaman/page/5-ternak-uang/6/4",
    category: "Stock and Finance",
  },
  {
    id: "5",
    title: "Private Placementa",
    drive: "https://drive.google.com/file/d/1zlOuP9l-rrMWayih7dvXTXGIRNpZIEwY",
    link: "/Halaman/page/5-ternak-uang/6/5",
    category: "Stock and Finance",
  },
  {
    id: "6",
    title: "Stock Split and Reverse Stock Split",
    drive: "https://drive.google.com/file/d/1WBP-jlXA8rtE-OCmUDKpryqOqhWDp3TT",
    link: "/Halaman/page/5-ternak-uang/6/6",
    category: "Stock and Finance",
  },
  {
    id: "7",
    title: "Rapat Umum Pemegang Saham",
    drive: "https://drive.google.com/file/d/1g6J5CbNE5SqmovGekZn4rG6P8nzI9gYR",
    link: "/Halaman/page/5-ternak-uang/6/7",
    category: "Stock and Finance",
  },
  {
    id: "8",
    title: "Merger dan Akuisisi",
    drive: "https://drive.google.com/file/d/1hiX-kJr91P0kqdSXJbY5wZIKrdebcfJE",
    link: "/Halaman/page/5-ternak-uang/6/8",
    category: "Stock and Finance",
  },
];