export const Data = [
  {
    id: "1",
    title: "Introduction to Consumer Goods",
    drive: "https://drive.google.com/file/d/11ehFMKnQ_EQM-MPbt6NnuTFnrymDDF4k",
    link: "/Halaman/page/5-ternak-uang/13/1",
    category: "Stock and Finance",
  },
  {
    id: "2",
    title: "Industrial Classification JASICA vs IDXIC",
    drive: "https://drive.google.com/file/d/1fqNf47Y6zlIQLxrjGgjTisoC_LLSIefK",
    link: "/Halaman/page/5-ternak-uang/13/2",
    category: "Stock and Finance",
  },
  {
    id: "3",
    title: "Siapa yang cocok Investasi di Sektor Consumer Goods",
    drive: "https://drive.google.com/file/d/11Y2WdI9udtTtsi4P04xn4RJYofb3jVGR",
    link: "/Halaman/page/5-ternak-uang/13/3",
    category: "Stock and Finance",
  },
  {
    id: "4",
    title: "Checklist yang Wajib Dipenuhi Sebelum Beli Saham",
    drive: "https://drive.google.com/file/d/1BhAWVOKPg47_o56rTaQIklwVqnf9-cAh",
    link: "/Halaman/page/5-ternak-uang/13/4",
    category: "Stock and Finance",
  },
  {
    id: "5",
    title: "Checklist 1 Business Model",
    drive: "https://drive.google.com/file/d/1jH6vBO2kZhcWxQUcJ-65HMlWnwRGUTIV",
    link: "/Halaman/page/5-ternak-uang/13/5",
    category: "Stock and Finance",
  },
  {
    id: "6",
    title: "Checklist 2 Prospect",
    drive: "https://drive.google.com/file/d/1Oh_Pd3I86Z0lQVz5bI9ObTKqLjvloAiN",
    link: "/Halaman/page/5-ternak-uang/13/6",
    category: "Stock and Finance",
  },
  {
    id: "7",
    title: "Checklist 3 Valuation",
    drive: "https://drive.google.com/file/d/1Y86kTnd2YAx89imRhk-4pmYOwTZ8OSsA",
    link: "/Halaman/page/5-ternak-uang/13/7",
    category: "Stock and Finance",
  },
  {
    id: "8",
    title: "Tantangan Perusahaan Sektor Consumer Goods",
    drive: "https://drive.google.com/file/d/1uKj1Q5RNhD7xWUYTY1OLMWOUCnzwsbch",
    link: "/Halaman/page/5-ternak-uang/13/8",
    category: "Stock and Finance",
  },
  {
    id: "9",
    title: "Metrics Consumer Goods",
    drive: "https://drive.google.com/file/d/1CmBcKEv_vyLBYLn-1HYpMV_X-ZWYeTci",
    link: "/Halaman/page/5-ternak-uang/13/9",
    category: "Stock and Finance",
  },
  {
    id: "10",
    title: "Revenue Model and Cost Structure Model",
    drive: "https://drive.google.com/file/d/1F7xamQOj10woMQisAHtFrFjibXL8Lim3",
    link: "/Halaman/page/5-ternak-uang/13/10",
    category: "Stock and Finance",
  },
  {
    id: "11",
    title: "Rasio Kesehatan Perusahaan",
    drive: "https://drive.google.com/file/d/19dgExADq5HCHSoSzuNi7SCo03l9yj_Zz",
    link: "/Halaman/page/5-ternak-uang/13/11",
    category: "Stock and Finance",
  },
  {
    id: "12",
    title: "Rasio Profitabilitas",
    drive: "https://drive.google.com/file/d/1LDV8Ynii1EBs8OJ1Eo32PMVOJ_zcRBen",
    link: "/Halaman/page/5-ternak-uang/13/12",
    category: "Stock and Finance",
  },
  {
    id: "13",
    title: "Rasio Efisiensi",
    drive: "https://drive.google.com/file/d/1cF-NOjX-1pcI4UPAGNnBxDRN1NvuFKaW",
    link: "/Halaman/page/5-ternak-uang/13/13",
    category: "Stock and Finance",
  },
  {
    id: "14",
    title: "Valuasi yang Cocok Untuk Consumer Goods",
    drive: "https://drive.google.com/file/d/15QKby2oOS2ExsF9XBjGiwWPpeDk3huq4",
    link: "/Halaman/page/5-ternak-uang/13/14",
    category: "Stock and Finance",
  },
  {
    id: "15",
    title: "Consumer Goods 101 Consumer Goods Valuation Praktik Yuk",
    drive: "https://drive.google.com/file/d/1bOZRz_Jo2b2kqTFt96zx0p9I2gAPbSPG",
    link: "/Halaman/page/5-ternak-uang/13/15",
    category: "Stock and Finance",
  },
];