export const Data = [
  {
    id: "1",
    title: "Cara Melakukan Trend Analysis",
    drive: "https:/drive.google.com/file/d/1hZKJudlFmQX-8syUUBGGvw9U5_BAOYwr/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/01-Cara-Melakukan-Trend-Analysis",
    category: "Technical Research",
  },
  {
    id: "2",
    title: "Cara Melakukan Area Analysis",
    drive: "https:/drive.google.com/file/d/1UZIAVaQv_OYhKmx-MlKPZm0ezWr2f3Mp/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/02-Cara-Melakukan-Area-Analysis",
    category: "Technical Research",
  },
  {
    id: "3",
    title: "Cara Melakukan Pattern Analysis",
    drive: "https:/drive.google.com/file/d/1qhThz2T6zKsA8-ww76wBeb5Jox2CDyWr/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/03-Cara-Melakukan-Pattern-Analysis",
    category: "Technical Research",
  },
  {
    id: "4",
    title: "Cara Melakukan Trigger Analysis",
    drive: "https:/drive.google.com/file/d/1Qt-7kxqsCS-tzsakfqvhSD6Um82gaZLz/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/04-Cara-Melakukan-Trigger-Analysis",
    category: "Technical Research",
  },
  {
    id: "5",
    title: "Cara Melakukan Entry Exit Analysis",
    drive: "https:/drive.google.com/file/d/13jjLIi3DEkD_D__ZBIYd4_ce0GovW-GV/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/05-Cara-Melakukan-Entry-Exit-Analysis",
    category: "Technical Research",
  },
  {
    id: "6",
    title: "Intro to Fundamental Research",
    drive: "https:/drive.google.com/file/d/1WZdphdqLxQziaij2pHbG01ySvAFxvFQU/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/06-Intro-to-Fundamental-Research",
    category: "Fundamental Research",
  },
  {
    id: "7",
    title: "Faktor yang Berperan Dalam Fundamental Research",
    drive: "https:/drive.google.com/file/d/10b_tcoqLLkywo89-i0hzFSAS3QxGHYa3/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/07-Faktor-yang-Berperan-Dalam-Fundamental-Research",
    category: "Fundamental Research",
  },
  {
    id: "8",
    title: "Mendalami Tokenomics Project",
    drive: "https:/drive.google.com/file/d/1DFxeDRMUqHa7XM1a5XfsunScdcKLR-mG/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/08-Mendalami-Tokenomics-Project",
    category: "Fundamental Research",
  },
  {
    id: "9",
    title: "Intro To Narrative Analysis",
    drive: "https:/drive.google.com/file/d/1TBwgSJK1d0CFm3RuiIINM_N2qfR-0Avj/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/09-Intro-To-Narrative-Analysis",
    category: "Narrative Analysis",
  },
  {
    id: "10",
    title: "How to be Early in Every Narratives",
    drive: "https:/drive.google.com/file/d/1WjDxudMd3YK-FcEtOcmsG7QUU7pgz-TH/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/10-How-to-be-Early-in-Every-Narratives",
    category: "Narrative Analysis",
  },
  {
    id: "11",
    title: "Portofolio Allocation",
    drive: "https:/drive.google.com/file/d/1A8-TfzrAX3otVDY_TyNM-t22v6SuCWmW/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/11-Portofolio-Allocation",
    category: "Narrative Analysis",
  },
  {
    id: "12",
    title: "Possible Narratives For Next Bull Run",
    drive: "https:/drive.google.com/file/d/1jaTX8HQqr_vizd9XdLS9uz6Z8RCXgZ4y/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/12-Possible-Narratives-For-Next-Bull-Run",
    category: "Narrative Analysis",
  },
  {
    id: "13",
    title: "Spatial Computing Narative",
    drive: "https:/drive.google.com/file/d/1ywDEln4d9kgvqXDBx8iw8BUatif3r4Ya/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/13-Spatial-Computing-Narative",
    category: "Narrative Analysis",
  },
  {
    id: "14",
    title: "Pemahaman Dasar Altcoins",
    drive: "https:/drive.google.com/file/d/10P-9m9mjwpPrpPazF_LrKD64yfUR4C7u/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/14-Pemahaman-Dasar-Altcoins",
    category: "Altcoin Scalping",
  },
  {
    id: "15",
    title: "Pemahaman Dasar Teknik Scalping",
    drive: "https:/drive.google.com/file/d/1B0YeJ7joIdTqnIta_q9SkOG-5CUuC3ge/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/15-Pemahaman-Dasar-Teknik-Scalping",
    category: "Altcoin Scalping",
  },
  {
    id: "16",
    title: "Persiapan Mental Sebelum Scalping",
    drive: "https:/drive.google.com/file/d/1_NrYHSMpweGQweNkrcO4EabX1bL-Fc9p/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/16-Persiapan-Mental-Sebelum-Scalping",
    category: "Altcoin Scalping",
  },
  {
    id: "17",
    title: "Persiapan Teknikal Sebelum Scalping",
    drive: "https:/drive.google.com/file/d/1Z7M4UHq7oIMIteHr2FGmy6ZARoGfb4nQ/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/17-Persiapan-Teknikal-Sebelum-Scalping",
    category: "Altcoin Scalping",
  },
  {
    id: "18",
    title: "Cara Melakukan Screening Altcoins untuk Scalping",
    drive: "https:/drive.google.com/file/d/1Aqmz5tTW8wmN99TOdzN93IPsxadqPCIM/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/18-Cara-Melakukan-Screening-Altcoins-untuk-Scalping",
    category: "Altcoin Scalping",
  },
  {
    id: "19",
    title: "Pengenalan On Chain Trading",
    drive: "https:/drive.google.com/file/d/1S8Jezbjs_b2tw-M_PyUwUlvGz2XjwqKB/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/19-Pengenalan-On-Chain-Trading",
    category: "On Chain Trading",
  },
  {
    id: "20",
    title: "Menggali Decentralized Exchange",
    drive: "https:/drive.google.com/file/d/1nF0KL8TWLlZUiycR8kjHfb8imoM0OiMG/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/20-Menggali-Decentralized-Exchange",
    category: "On Chain Trading",
  },
  {
    id: "21",
    title: "Cara Menggunakan Wallet dan Exchange",
    drive: "https:/drive.google.com/file/d/1VODay6vyxalQqMc06RAvclv0kcLJnsmt/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/21-Cara-Menggunakan-Wallet-dan-Exchange",
    category: "On Chain Trading",
  },
  {
    id: "22",
    title: "Tools untuk On Chain",
    drive: "https:/drive.google.com/file/d/1I1r09P8Z557r1Ff6kR9cUOU-gL72kFBE/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/22-Tools-untuk-On-Chain",
    category: "On Chain Trading",
  },
  {
    id: "23",
    title: "Kesalahan yang harus dihindari Sebelum Transaksi On Chain",
    drive: "https:/drive.google.com/file/d/1xZoSM3Rc7u9CFWtuHFopmiTvvt1ss4ld/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/23-Kesalahan-yang-harus-dihindari-Sebelum-Transaksi-On-Chain",
    category: "On Chain Trading",
  },
  {
    id: "24",
    title: "Pengenalan Dow Theory",
    drive: "https:/drive.google.com/file/d/1WEXX05MawudgIP91XTgG1fXZziOCRiyP/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/24-Pengenalan-Dow-Theory",
    category: "Crypto Dow Theory",
  },
  {
    id: "25",
    title: "Memahami Konsep Trend dalam Dow Theory",
    drive: "https:/drive.google.com/file/d/1WYusTYFvN4wwTRiE0XSzl9T3r0MDOM6y/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/25-Memahami-Konsep-Trend-dalam-Dow-Theory",
    category: "Crypto Dow Theory",
  },
  {
    id: "26",
    title: "Memahami Konsep Trend Lanjutan Dalam Dow Theory",
    drive: "https:/drive.google.com/file/d/1Zeblm5tBFdYCmQxcgNfTe7zKUB1cCohV/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/26-Memahami-Konsep-Trend-Lanjutan-Dalam-Dow-Theory",
    category: "Crypto Dow Theory",
  },
  {
    id: "27",
    title: "Penggunaan Moving Averages dan Validasi Dow",
    drive: "https:/drive.google.com/file/d/1L6r8aLv8BgEo_Rfdh6-Fb7pSPTepns_O/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/27-Penggunaan-Moving-Averages-dan-Validasi-Dow",
    category: "Crypto Dow Theory",
  },
  {
    id: "28",
    title: "Fase pada Dow Theory",
    drive: "https:/drive.google.com/file/d/1grJ3LatiXyp8rt1X4irx6QdRrfz1fouD/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/28-Fase-pada-Dow-Theory",
    category: "Crypto Dow Theory",
  }
];