export const Data = [
  {
    id: "1",
    title: "Cara Melakukan Trend Analysis",
    drive: "https://drive.google.com/file/d/1Kq6_WhRiGPjKRXHU1IvuHOje7spKP8da/view?usp=drivesdk",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/01-Cara-Melakukan-Trend-Analysis",
    category: "Technical Research",
  },
  {
    id: "2",
    title: "Cara Melakukan Area Analysis",
    drive: "https://drive.google.com/file/d/1L5usqxpKDe7DIvU0ikc_KAxqqAvpq3fN/view?usp=drivesdk",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/02-Cara-Melakukan-Area-Analysis",
    category: "Technical Research",
  },
  {
    id: "3",
    title: "Cara Melakukan Pattern Analysis",
    drive: "https://drive.google.com/file/d/1LIM_h5gQA46azvQRAtqGpe1tx1z4J0Qt/view?usp=drivesdk",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/03-Cara-Melakukan-Pattern-Analysis",
    category: "Technical Research",
  },
  {
    id: "4",
    title: "Cara Melakukan Trigger Analysis",
    drive: "https://drive.google.com/file/d/1LLbmg8ymvkFmDkFUgXg5FF-0i4cInTNg/view?usp=drivesdk",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/04-Cara-Melakukan-Trigger-Analysis",
    category: "Technical Research",
  },
  {
    id: "5",
    title: "Cara Melakukan Entry Exit Analysis",
    drive: "https://drive.google.com/file/d/1LLufl586XKUmJk97-S3Haf_4TqOo45AL/view?usp=drivesdk",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/05-Cara-Melakukan-Entry-Exit-Analysis",
    category: "Technical Research",
  },
  {
    id: "6",
    title: "Intro to Fundamental Research",
    drive: "https://drive.google.com/file/d/1LPQmRXyVR2B2FS2yPnxAvPqIsMxdOKPl/view?usp=drivesdk",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/06-Intro-to-Fundamental-Research",
    category: "Fundamental Research",
  },
  {
    id: "7",
    title: "Faktor yang Berperan Dalam Fundamental Research",
    drive: "https://drive.google.com/file/d/1LPkUlvNKxe6vkJ3YvanX6rP_iF1-e1Sj/view?usp=drivesdk",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/07-Faktor-yang-Berperan-Dalam-Fundamental-Research",
    category: "Fundamental Research",
  },
  {
    id: "8",
    title: "Mendalami Tokonomics Project",
    drive: "https://drive.google.com/file/d/1LXnvBMo1mfg5Rh1BfcYth6xgA15ZLvh6/view?usp=drivesdk",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/08-Mendalami-Tokenomics-Project",
    category: "Fundamental Research",
  },
  {
    id: "9",
    title: "Intro to Narrative Analysis",
    drive: "https://drive.google.com/file/d/1LYDAxOs-UfknH6TWNtZdLesJH_p4Y6_b/view?usp=drivesdk",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/09-Intro-To-Narrative-Analysis",
    category: "Narrative Analysis",
  },
  {
    id: "10",
    title: "How to be Early in Every Narratives",
    drive: "https://drive.google.com/file/d/1LZsA9Ol4YUuzZoxLwcUqxf1M1_z787-R/view?usp=drivesdk",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/10-How-to-be-Early-in-Every-Narratives",
    category: "Narrative Analysis",
  },
  {
    id: "11",
    title: "Portofolio Allocation",
    drive: "https://drive.google.com/file/d/1LiX1mhhVMXrNLm20InUPb6RCKE5lcf9s/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/11-Portofolio-Allocation",
    category: "Narrative Analysis",
  },
  {
    id: "12",
    title: "Possible Narratives For Next Bull Run",
    drive: "https://drive.google.com/file/d/1LiqrfuF14VDly_UuWUtm18ITbMzMyXjh/view?usp=drivesdk",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/12-Possible-Narratives-For-Next-Bull-Run",
    category: "Narrative Analysis",
  },
  {
    id: "13",
    title: "Spacial Computing Narrative",
    drive: "https://drive.google.com/file/d/1LnGyUENImYSZMK7aANVJdU_0zqSabvkO/view?usp=drivesdk",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/13-Spatial-Computing-Narative",
    category: "Narrative Analysis",
  },
  {
    id: "14",
    title: "Pemahaman Dasar Mengenai Apa itu Altcoins",
    drive: "https://drive.google.com/file/d/1AszyuclAqdzIjY1Ifx7OxYbHQzn1BZ6D/view?usp=drivesdk",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/14-Pemahaman-Dasar-Altcoins",
    category: "Altcoin Scalping",
  },
  {
    id: "15",
    title: "Pemahaman Dasar Mengenai Teknik Scalping",
    drive: "https://drive.google.com/file/d/1AmNBabmcqTlIgAWKvtgHif9wcTdVNBwN/view?usp=drivesdk",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/15-Pemahaman-Dasar-Teknik-Scalping",
    category: "Altcoin Scalping",
  },
  {
    id: "16",
    title: "Persiapan Mental Sebelum Melakukan Scalping Altcoins",
    drive: "https://drive.google.com/file/d/1AugLEEJcJh-TbOlIIAt4ENqQkLG22lU-/view?usp=drivesdk",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/16-Persiapan-Mental-Sebelum-Scalping",
    category: "Altcoin Scalping",
  },
  {
    id: "17",
    title: "Persiapan Technical Sebelum Melakukan Scalping",
    drive: "https://drive.google.com/file/d/1AuhcOhMMveUo5QyqozACpw-Big2AUImq/view?usp=drivesdk",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/17-Persiapan-Teknikal-Sebelum-Scalping",
    category: "Altcoin Scalping",
  },
  {
    id: "18",
    title: "Cara Melakukan Screening Altcoins Untuk Scalping",
    drive: "https://drive.google.com/file/d/1AiyL8GIObbLcgjqkC-bMO4kDTt07Fo5h/view?usp=drivesdk",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/18-Cara-Melakukan-Screening-Altcoins-untuk-Scalping",
    category: "Altcoin Scalping",
  },
  {
    id: "19",
    title: "Pengenalan Dow Theory Pada Market Crypto",
    drive: "https://drive.google.com/file/d/1B1aubzsRo3HTl-K-PXpfSIgIsddbS67x/view?usp=drivesdk",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/19-Pengenalan-On-Chain-Trading",
    category: "On Chain Trading",
  },
  {
    id: "20",
    title: "Memahami Konsep Trend dalam Dow Theory",
    drive: "https://drive.google.com/file/d/1B1wuBz-o33WbixhgO9Jjm-zmnLK1BTdg/view?usp=drivesdk",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/20-Menggali-Decentralized-Exchange",
    category: "On Chain Trading",
  },
  {
    id: "21",
    title: "Memahami Konsep Trend Lanjutan Dalam Dow Theory",
    drive: "https://drive.google.com/file/d/1BBJn1qpAfrmxenYNFnTazyVrj84jaVBT/view?usp=drivesdk",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/21-Cara-Menggunakan-Wallet-dan-Exchange",
    category: "On Chain Trading",
  },
  {
    id: "22",
    title: "Penggunaan Moving Averages dan Validasi Dow",
    drive: "https://drive.google.com/file/d/1AzqdNaQyM6tlJKQLZASW0KchaBIHG3Jw/view?usp=drivesdk",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/22-Tools-untuk-On-Chain",
    category: "On Chain Trading",
  },
  {
    id: "23",
    title: "Fase pada Dow Theory",
    drive: "https://drive.google.com/file/d/1BNXU_SwnKvEJ2jiTDxvb5BSr01_80MCP/view?usp=drivesdk",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/23-Kesalahan-yang-harus-dihindari-Sebelum-Transaksi-On-Chain",
    category: "On Chain Trading",
  },
];
