export const Data = [
  {
    id: "1",
    title: "Cara Melakukan Trend Analysis",
    drive: "https://drive.google.com/file/d/1buPKLlsfjXsqzJI40GkOwaks7L0LqaUL",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/01-Cara-Melakukan-Trend-Analysis",
    category: "Technical Research",
  },
  {
    id: "2",
    title: "Cara Melakukan Area Analysis",
    drive: "https://drive.google.com/file/d/14EpPeAKgGRq8JPwlfzGZ0Vh3nLJS3QgJ",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/02-Cara-Melakukan-Area-Analysis",
    category: "Technical Research",
  },
  {
    id: "3",
    title: "Cara Melakukan Pattern Analysis",
    drive: "https://drive.google.com/file/d/185_b5n6V52asBtnqAa_VLabOSdkCGHzX",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/03-Cara-Melakukan-Pattern-Analysis",
    category: "Technical Research",
  },
  {
    id: "4",
    title: "Cara Melakukan Trigger Analysis",
    drive: "https://drive.google.com/file/d/1khbx1D52gYSHvbEXP_FqR0atCcM70zPV",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/04-Cara-Melakukan-Trigger-Analysis",
    category: "Technical Research",
  },
  {
    id: "5",
    title: "Cara Melakukan Entry Exit Analysis",
    drive: "https://drive.google.com/file/d/1_j9t1xf2X8Ac1Qx8E-nV-cxQSUZrcVcE",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/05-Cara-Melakukan-Entry-Exit-Analysis",
    category: "Technical Research",
  },
  {
    id: "6",
    title: "Intro to Fundamental Research",
    drive: "https://drive.google.com/file/d/1E2xc38-BGE3cDVUKG39jT_TXqYq2eg0F",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/06-Intro-to-Fundamental-Research",
    category: "Fundamental Research",
  },
  {
    id: "7",
    title: "Faktor yang Berperan Dalam Fundamental Research",
    drive: "https://drive.google.com/file/d/1x91SMyuAoVP03kMpptWsTHEgGnlN16Mi",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/07-Faktor-yang-Berperan-Dalam-Fundamental-Research",
    category: "Fundamental Research",
  },
  {
    id: "8",
    title: "Mendalami Tokenomics Project",
    drive: "https://drive.google.com/file/d/1SyxS7btPxyaNBQ6BYZqZ_qS_no6VQZym",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/08-Mendalami-Tokenomics-Project",
    category: "Fundamental Research",
  },
  {
    id: "9",
    title: "Intro To Narrative Analysis",
    drive: "https://drive.google.com/file/d/1vFKM4-w7jhaqL2-57JduKybNcB3YHFxG",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/09-Intro-To-Narrative-Analysis",
    category: "Narrative Analysis",
  },
  {
    id: "10",
    title: "How to be Early in Every Narratives",
    drive: "https://drive.google.com/file/d/17wNJKEd7VHEbd0ikekBILH0EwxaueiFW",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/10-How-to-be-Early-in-Every-Narratives",
    category: "Narrative Analysis",
  },
  {
    id: "11",
    title: "Portofolio Allocation",
    drive: "https://drive.google.com/file/d/1C3Jd0bEBhBTsuS3yE5s_5cSXqV8AYMGc",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/11-Portofolio-Allocation",
    category: "Narrative Analysis",
  },
  {
    id: "12",
    title: "Possible Narratives For Next Bull Run",
    drive: "https://drive.google.com/file/d/1e8rAAGYj_rguSnL1gUdR2chX6tu59pUW",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/12-Possible-Narratives-For-Next-Bull-Run",
    category: "Narrative Analysis",
  },
  {
    id: "13",
    title: "Spatial Computing Narative",
    drive: "https://drive.google.com/file/d/1IP0MygvvXtG0KSS-po6fvXW87f9-U1FS",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/13-Spatial-Computing-Narative",
    category: "Narrative Analysis",
  },
  {
    id: "14",
    title: "Pemahaman Dasar Altcoins",
    drive: "https://drive.google.com/file/d/1KYYJwyFaZ08YNh9HwJKmWbHeJQK8OVkU",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/14-Pemahaman-Dasar-Altcoins",
    category: "Altcoin Scalping",
  },
  {
    id: "15",
    title: "Pemahaman Dasar Teknik Scalping",
    drive: "https://drive.google.com/file/d/1XDkfLL887Zs0r7P_VpVyb3JReapU55Bt",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/15-Pemahaman-Dasar-Teknik-Scalping",
    category: "Altcoin Scalping",
  },
  {
    id: "16",
    title: "Persiapan Mental Sebelum Scalping",
    drive: "https://drive.google.com/file/d/1TM7LSx8sKPJxhhjYOxheFp_VET7fUKDL",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/16-Persiapan-Mental-Sebelum-Scalping",
    category: "Altcoin Scalping",
  },
  {
    id: "17",
    title: "Persiapan Teknikal Sebelum Scalping",
    drive: "https://drive.google.com/file/d/1kj9lJbV2q-xBZD5s6MauF_d62Mtd-Ska",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/17-Persiapan-Teknikal-Sebelum-Scalping",
    category: "Altcoin Scalping",
  },
  {
    id: "18",
    title: "Cara Melakukan Screening Altcoins untuk Scalping",
    drive: "https://drive.google.com/file/d/15u7t7LOxT48Y0JkWT7-QEzBxjCfR7h5t",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/18-Cara-Melakukan-Screening-Altcoins-untuk-Scalping",
    category: "Altcoin Scalping",
  },
  {
    id: "19",
    title: "Pengenalan On Chain Trading",
    drive: "https://drive.google.com/file/d/1jt_uw11DtUBLMwxM1So8SLBPReuUgIzq",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/19-Pengenalan-On-Chain-Trading",
    category: "On Chain Trading",
  },
  {
    id: "20",
    title: "Menggali Decentralized Exchange",
    drive: "https://drive.google.com/file/d/1d-b9nw7yAM6Vc_zGIa7VBgSwl5bx6D-W",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/20-Menggali-Decentralized-Exchange",
    category: "On Chain Trading",
  },
  {
    id: "21",
    title: "Cara Menggunakan Wallet dan Exchange",
    drive: "https://drive.google.com/file/d/16vxNfCwSS1O5_-tNXXfHiR4ocjYzzn9Y",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/21-Cara-Menggunakan-Wallet-dan-Exchange",
    category: "On Chain Trading",
  },
  {
    id: "22",
    title: "Tools untuk On Chain",
    drive: "https://drive.google.com/file/d/1xrjwvIGtqXKjt_uizGBLwO85AS2wB4X0",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/22-Tools-untuk-On-Chain",
    category: "On Chain Trading",
  },
  {
    id: "23",
    title: "Kesalahan yang harus dihindari Sebelum Transaksi On Chain",
    drive: "https://drive.google.com/file/d/1gavrh2GbHTS3jTbSvqtiC_mG6_ZthfQF",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/23-Kesalahan-yang-harus-dihindari-Sebelum-Transaksi-On-Chain",
    category: "On Chain Trading",
  },
  {
    id: "24",
    title: "Pengenalan Dow Theory",
    drive: "",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/24-Pengenalan-Dow-Theory",
    category: "Crypto Dow Theory",
  },
  {
    id: "25",
    title: "Memahami Konsep Trend dalam Dow Theory",
    drive: "",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/25-Memahami-Konsep-Trend-dalam-Dow-Theory",
    category: "Crypto Dow Theory",
  },
  {
    id: "26",
    title: "Memahami Konsep Trend Lanjutan Dalam Dow Theory",
    drive: "",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/26-Memahami-Konsep-Trend-Lanjutan-Dalam-Dow-Theory",
    category: "Crypto Dow Theory",
  },
  {
    id: "27",
    title: "Penggunaan Moving Averages dan Validasi Dow",
    drive: "",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/27-Penggunaan-Moving-Averages-dan-Validasi-Dow",
    category: "Crypto Dow Theory",
  },
  {
    id: "28",
    title: "Fase pada Dow Theory",
    drive: "",
    link: "/Halaman/page/1-crypto-trading/01-Crypto-Trading-Kalimasada/28-Fase-pada-Dow-Theory",
    category: "Crypto Dow Theory",
  }
];