export const Data = [
  {
    id: "1",
    title: "Limiting Belief",
    drive: "https://drive.google.com/file/d/1KALseEwrIK5B26RjjEta9pVwb0BMZCDk/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/1-Limiting-Belief",
    category: "Mentalitas Anak Jalanan",
  },
  {
    id: "2",
    title: "Focus",
    drive: "https://drive.google.com/file/d/1KBHy_Bu3MuulmTNiQDqJxbZCbtZIoGhH/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/2-Focus",
    category: "Mentalitas Anak Jalanan",
  },
  {
    id: "3",
    title: "Decision Making",
    drive: "https://drive.google.com/file/d/1KBflUka9Dq0xdd1Ay0X60f3i1o_7Cjej/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/3-Decision-Making",
    category: "Mentalitas Anak Jalanan",
  },
  {
    id: "4",
    title: "Kekayaan dan Pikiran",
    drive: "https://drive.google.com/file/d/1KIQJvJgsYNCmC5gssDZhLaSovTuMgQhl/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/4-Kekayaan-dan-Pikiran",
    category: "Mentalitas Anak Jalanan",
  },
  {
    id: "5",
    title: "Introduction to Sales",
    drive: "https://drive.google.com/file/d/1KJSXks8Ejn3zxY-JtHNNE8SPWmyoH9lc/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/5-Introduction-to-Sales",
    category: "Sales Fundamentals",
  },
  {
    id: "6",
    title: "The Psychology of Selling",
    drive: "https://drive.google.com/file/d/1KJqPtD1xm5Cvx8nU2iKDDiBWDiIohSqE/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/6-The-Psychology-of-Selling",
    category: "Sales Fundamentals",
  },
  {
    id: "7",
    title: "Building a Rapport",
    drive: "https://drive.google.com/file/d/1KLAm--T9o-ruaoNyq_kYghoe9CszAhCl/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/7-Building-a-Rapport",
    category: "Sales Fundamentals",
  },
  {
    id: "8",
    title: "Cara Jadi Sales Yang Terbaik",
    drive: "https://drive.google.com/file/d/1KO7tYFgJhnl-I_0vvv2cFq7kZ7x1LbU9/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/8-Cara-Jadi-Sales-Yang-Terbaik",
    category: "Sales Fundamentals",
  },
  {
    id: "9",
    title: "Sales Mentality",
    drive: "https://drive.google.com/file/d/1KSfTXthGd7f1HyxfO9ktXKzu7c39zPZ8/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/9-Sales-Mentality",
    category: "Sales Fundamentals",
  },
  {
    id: "10",
    title: "Breakdown Tipe Penjualan",
    drive: "https://drive.google.com/file/d/1KVs-DnwNoQvTYtKUe0LaSllT982zkuO3/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/10-Breakdown-Tipe-Penjualan",
    category: "Sales Fundamentals",
  },
  {
    id: "11",
    title: "Decision Making Flow",
    drive: "https://drive.google.com/file/d/1KYcz6dq9rCNmpok1-G93a14j4IRHyJ4w/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/11-Decision-Making-Flow",
    category: "Sales Fundamentals",
  },
  {
    id: "12",
    title: "The Art of Storytelling",
    drive: "https://drive.google.com/file/d/1KaL1uGIezgx2TYiLX1VAUA87YVlh_U-H/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/12-The-Art-of-Storytelling",
    category: "Sales Fundamentals",
  },
  {
    id: "13",
    title: "The Art of Persuasion",
    drive: "https://drive.google.com/file/d/1KcAcYTlUP0DhQV7xeV88UjefdwRnYgJS/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/13-The-Art-of-Persuasion",
    category: "Sales Fundamentals",
  },
  {
    id: "14",
    title: "Sales Funnel",
    drive: "https://drive.google.com/file/d/1KhJ-jEHhorXnldGRIfJYzo5ORG5zwEHq/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/14-Sales-Funnel",
    category: "Sales Fundamentals",
  },
  {
    id: "15",
    title: "How to Follow Up",
    drive: "https://drive.google.com/file/d/1Ki9eJXLS6i5pvaRHG9EfUtaELrFNvLj6/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/15-How-to-Follow-Up",
    category: "Sales Fundamentals",
  },
  {
    id: "16",
    title: "Objection Handling",
    drive: "https://drive.google.com/file/d/1KjKQRBZP80TPwGxJV45ufStodFKfLO72/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/16-Objection-Handling",
    category: "Sales Fundamentals",
  }
];