export const Data = [
  {
    id: "1",
    title: "Limiting Belief",
    drive: "https://drive.google.com/file/d/1hRO3hcIAx0YGWq_1NhpTFGh6gpFeN55C/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/1-Limiting-Belief",
    category: "Mentalitas Anak Jalanan",
  },
  {
    id: "2",
    title: "Focus",
    drive: "https://drive.google.com/file/d/1iLdLJ459MLQRopJa1gxf_9u8dyqMF64Z/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/2-Focus",
    category: "Mentalitas Anak Jalanan",
  },
  {
    id: "3",
    title: "Decision Making",
    drive: "https://drive.google.com/file/d/1iKVgksu-jmea1qN5k3XKCy5enaPFKlCN/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/3-Decision-Making",
    category: "Mentalitas Anak Jalanan",
  },
  {
    id: "4",
    title: "Kekayaan dan Pikiran",
    drive: "https://drive.google.com/file/d/1iHrxTahYUXcuzL250a88syjlzZcFVs3P/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/4-Kekayaan-dan-Pikiran",
    category: "Mentalitas Anak Jalanan",
  },
  {
    id: "5",
    title: "Introduction to Sales",
    drive: "https://drive.google.com/file/d/1iHnRhO4mzx7qyYdFysw9e5hQfkt4GG3h/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/5-Introduction-to-Sales",
    category: "Sales Fundamentals",
  },
  {
    id: "6",
    title: "The Psychology of Selling",
    drive: "https://drive.google.com/file/d/1iGn1OdkUIEiPcqGzSH-BJkVbPW7ksb8Q/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/6-The-Psychology-of-Selling",
    category: "Sales Fundamentals",
  },
  {
    id: "7",
    title: "Building a Rapport",
    drive: "https://drive.google.com/file/d/1iDVjCPZHBVpsmLscntHb9IzY7FOyOOUC/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/7-Building-a-Rapport",
    category: "Sales Fundamentals",
  },
  {
    id: "8",
    title: "Cara Jadi Sales Yang Terbaik",
    drive: "https://drive.google.com/file/d/1i1lUCokIun6zj8ULiup_oWAbfhbMDW_d/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/8-Cara-Jadi-Sales-Yang-Terbaik",
    category: "Sales Fundamentals",
  },
  {
    id: "9",
    title: "Sales Mentality",
    drive: "https://drive.google.com/file/d/1i0NeXHW_8Cz2O4_6HzhWl9kCdZJnosbJ/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/9-Sales-Mentality",
    category: "Sales Fundamentals",
  },
  {
    id: "10",
    title: "Breakdown Tipe Penjualan",
    drive: "https://drive.google.com/file/d/1i-xQJVghPvIOT7xWaKuI3a-MGlBXtgBk/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/10-Breakdown-Tipe-Penjualan",
    category: "Sales Fundamentals",
  },
  {
    id: "11",
    title: "Decision Making Flow",
    drive: "https://drive.google.com/file/d/1htJp0sKPs2kT3LKyZjkv0Ke1JM10-thd/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/11-Decision-Making-Flow",
    category: "Sales Fundamentals",
  },
  {
    id: "12",
    title: "The Art of Storytelling",
    drive: "https://drive.google.com/file/d/1hkBZMgVAqAx4SysB3LEP6Jx14Kyveu-z/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/12-The-Art-of-Storytelling",
    category: "Sales Fundamentals",
  },
  {
    id: "13",
    title: "The Art of Persuasion",
    drive: "https://drive.google.com/file/d/1hgXDl4u3q4RYHLraP8Ira5mzAY93T0jD/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/13-The-Art-of-Persuasion",
    category: "Sales Fundamentals",
  },
  {
    id: "14",
    title: "Sales Funnel",
    drive: "https://drive.google.com/file/d/1hgJAUGb3hcD_np_sF8J0Sj2Ylfa5zurf/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/14-Sales-Funnel",
    category: "Sales Fundamentals",
  },
  {
    id: "15",
    title: "How to Follow Up",
    drive: "https://drive.google.com/file/d/1h_AwR1tnIZHv6ze8fP495k6J-47Kr2fO/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/15-How-to-Follow-Up",
    category: "Sales Fundamentals",
  },
  {
    id: "16",
    title: "Objection Handling",
    drive: "https://drive.google.com/file/d/1hTAl06Ytsn-LLlyZ7noCXngC4w8V3emp/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/16-Objection-Handling",
    category: "Sales Fundamentals",
  }
];