export const Data = [
  {
    id: "1",
    title: "Limiting Belief",
    drive: "https://drive.google.com/file/d/1JtrjWWeGnqq-O2tRuvEQMbnP2NsPQkxh/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/1-Limiting-Belief",
    category: "Mentalitas Anak Jalanan",
  },
  {
    id: "2",
    title: "Focus",
    drive: "https://drive.google.com/file/d/1CEjWjQ42JfWACpa5dHv9AQ1cT8pGqbE_/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/2-Focus",
    category: "Mentalitas Anak Jalanan",
  },
  {
    id: "3",
    title: "Decision Making",
    drive: "https://drive.google.com/file/d/1zuiJhzlGI4cYItNL4dgS9GhWXyDollvj/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/3-Decision-Making",
    category: "Mentalitas Anak Jalanan",
  },
  {
    id: "4",
    title: "Kekayaan dan Pikiran",
    drive: "https://drive.google.com/file/d/11xKLceIoS5TByXw5SjXXiF7W7Pyv35ac/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/4-Kekayaan-dan-Pikiran",
    category: "Mentalitas Anak Jalanan",
  },
  {
    id: "5",
    title: "Introduction to Sales",
    drive: "https://drive.google.com/file/d/141bUHSlmAHJwNDixceZB2Hz0yqOL_Gtk/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/5-Introduction-to-Sales",
    category: "Sales Fundamentals",
  },
  {
    id: "6",
    title: "The Psychology of Selling",
    drive: "https://drive.google.com/file/d/1Xr8clPP9u1lq9kdHE6IBbt2b2ym_c-U8/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/6-The-Psychology-of-Selling",
    category: "Sales Fundamentals",
  },
  {
    id: "7",
    title: "Building a Rapport",
    drive: "https://drive.google.com/file/d/1NIzwppS45Mp1KKs9fDyk7dJl69PD0-FN/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/7-Building-a-Rapport",
    category: "Sales Fundamentals",
  },
  {
    id: "8",
    title: "Cara Jadi Sales Yang Terbaik",
    drive: "https://drive.google.com/file/d/18gD6FA1Aae92le6nnazOcddHCdtEegTG/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/8-Cara-Jadi-Sales-Yang-Terbaik",
    category: "Sales Fundamentals",
  },
  {
    id: "9",
    title: "Sales Mentality",
    drive: "https://drive.google.com/file/d/1vatC7Su6yotLNrea-2nET3ba-6PlOrLf/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/9-Sales-Mentality",
    category: "Sales Fundamentals",
  },
  {
    id: "10",
    title: "Breakdown Tipe Penjualan",
    drive: "https://drive.google.com/file/d/1SfSsU6feWUteWvxXinFUqqA7EUM6K62r/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/10-Breakdown-Tipe-Penjualan",
    category: "Sales Fundamentals",
  },
  {
    id: "11",
    title: "Decision Making Flow",
    drive: "https://drive.google.com/file/d/16GlOgbWMAknri_jPpgn4lFgvJppON1h9/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/11-Decision-Making-Flow",
    category: "Sales Fundamentals",
  },
  {
    id: "12",
    title: "The Art of Storytelling",
    drive: "https://drive.google.com/file/d/1wSXzMaTgzRFmLhi0yQvyFTwFY1HKN3h-/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/12-The-Art-of-Storytelling",
    category: "Sales Fundamentals",
  },
  {
    id: "13",
    title: "The Art of Persuasion",
    drive: "https://drive.google.com/file/d/1k4ObPDGdho1lAZk-cOVaXO9_gy8jXuh1/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/13-The-Art-of-Persuasion",
    category: "Sales Fundamentals",
  },
  {
    id: "14",
    title: "Sales Funnel",
    drive: "https://drive.google.com/file/d/18tdfMbXjN-5ozzKURGZk_iUdmRSB-G2y/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/14-Sales-Funnel",
    category: "Sales Fundamentals",
  },
  {
    id: "15",
    title: "How to Follow Up",
    drive: "https://drive.google.com/file/d/1lkXDqYKeLMQjrGDcwULZYPtJNbLaUZ58/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/15-How-to-Follow-Up",
    category: "Sales Fundamentals",
  },
  {
    id: "16",
    title: "Objection Handling",
    drive: "https://drive.google.com/file/d/1CfRrHz8wVzkRO43UBf1hz8ydxHvZMRee/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery/16-Objection-Handling",
    category: "Sales Fundamentals",
  }
];