export const ternakuangData = [
  {
    title: "-",
    image: "/images/tu25.jpg",
    link: "/Halaman/page/5-ternak-uang/-",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu24.jpg",
    link: "/Halaman/page/5-ternak-uang/-",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu23.jpg",
    link: "/Halaman/page/5-ternak-uang/-",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu22.jpg",
    link: "/Halaman/page/5-ternak-uang/-",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu21.jpg",
    link: "/Halaman/page/5-ternak-uang/-",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu20.jpg",
    link: "/Halaman/page/5-ternak-uang/-",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu19.jpg",
    link: "/Halaman/page/5-ternak-uang/-",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu18.jpg",
    link: "/Halaman/page/5-ternak-uang/-",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu17.jpg",
    link: "/Halaman/page/5-ternak-uang/-",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu16.jpg",
    link: "/Halaman/page/5-ternak-uang/-",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu15.jpg",
    link: "/Halaman/page/5-ternak-uang/-",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu14.jpg",
    link: "/Halaman/page/5-ternak-uang/-",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu13.jpg",
    link: "/Halaman/page/5-ternak-uang/-",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu12.jpg",
    link: "/Halaman/page/5-ternak-uang/-",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu11.jpg",
    link: "/Halaman/page/5-ternak-uang/-",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu10.jpg",
    link: "/Halaman/page/5-ternak-uang/-",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu9.jpg",
    link: "/Halaman/page/5-ternak-uang/-",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu8.jpg",
    link: "/Halaman/page/5-ternak-uang/-",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu7.jpg",
    link: "/Halaman/page/5-ternak-uang/-",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu6.jpg",
    link: "/Halaman/page/5-ternak-uang/-",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu5.jpg",
    link: "/Halaman/page/5-ternak-uang/-",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu4.jpg",
    link: "/Halaman/page/5-ternak-uang/-",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu3.jpg",
    link: "/Halaman/page/5-ternak-uang/-",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu2.jpg",
    link: "/Halaman/page/5-ternak-uang/-",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu1.jpg",
    link: "/Halaman/page/5-ternak-uang/-",
    category: "Stock and Finance",
  },
];