export const ternakuangData = [
  {
    title: "-",
    image: "/images/tu25.jpg",
    link: "/Halaman/page/5-ternak-uang/25",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu24.jpg",
    link: "/Halaman/page/5-ternak-uang/24",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu23.jpg",
    link: "/Halaman/page/5-ternak-uang/23",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu22.jpg",
    link: "/Halaman/page/5-ternak-uang/22",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu21.jpg",
    link: "/Halaman/page/5-ternak-uang/21",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu20.jpg",
    link: "/Halaman/page/5-ternak-uang/20",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu19.jpg",
    link: "/Halaman/page/5-ternak-uang/19",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu18.jpg",
    link: "/Halaman/page/5-ternak-uang/18",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu17.jpg",
    link: "/Halaman/page/5-ternak-uang/17",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu16.jpg",
    link: "/Halaman/page/5-ternak-uang/16",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu15.jpg",
    link: "/Halaman/page/5-ternak-uang/15",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu14.jpg",
    link: "/Halaman/page/5-ternak-uang/14",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu13.jpg",
    link: "/Halaman/page/5-ternak-uang/13",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu12.jpg",
    link: "/Halaman/page/5-ternak-uang/12",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu11.jpg",
    link: "/Halaman/page/5-ternak-uang/11",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu10.jpg",
    link: "/Halaman/page/5-ternak-uang/10",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu9.jpg",
    link: "/Halaman/page/5-ternak-uang/9",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu8.jpg",
    link: "/Halaman/page/5-ternak-uang/8",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu7.jpg",
    link: "/Halaman/page/5-ternak-uang/7",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu6.jpg",
    link: "/Halaman/page/5-ternak-uang/6",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu5.jpg",
    link: "/Halaman/page/5-ternak-uang/5",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu4.jpg",
    link: "/Halaman/page/5-ternak-uang/4",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu3.jpg",
    link: "/Halaman/page/5-ternak-uang/3",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu2.jpg",
    link: "/Halaman/page/5-ternak-uang/2",
    category: "Stock and Finance",
  },
  {
    title: "-",
    image: "/images/tu1.jpg",
    link: "/Halaman/page/5-ternak-uang/1",
    category: "Stock and Finance",
  },
];