export const Data = [
  {
    id: "1",
    title: "Apa Itu Pattern",
    drive: "https:/drive.google.com/file/d/15xfmXafoQcyTYrjQQ8qqi5mZABQfgar1/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/02-Kamus-Pattern-Crypto-Kalimasada/01-Apa-Itu-Pattern",
    category: "Crypto Trading",
  },
  {
    id: "2",
    title: "ABCD Pattern",
    drive: "https:/drive.google.com/file/d/1TubzrApMpuTMEv2aNQ1AGaPineUQRsTo/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/02-Kamus-Pattern-Crypto-Kalimasada/02-ABCD-Pattern",
    category: "Crypto Trading",
  },
  {
    id: "3",
    title: "Bat Pattern",
    drive: "https:/drive.google.com/file/d/1aiSc4bnYzTluVZaheGS9xSnX4U7b0jDd/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/02-Kamus-Pattern-Crypto-Kalimasada/03-Bat-Pattern",
    category: "Crypto Trading",
  },
  {
    id: "4",
    title: "Gartley Pattern",
    drive: "https:/drive.google.com/file/d/1YFFbtNNEwMQiFuCdkza7zYyrq0eR0tNK/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/02-Kamus-Pattern-Crypto-Kalimasada/04-Gartley-Pattern",
    category: "Crypto Trading",
  },
  {
    id: "5",
    title: "Crab Pattern",
    drive: "https:/drive.google.com/file/d/1Ued2DMoLWhQGwtBXvE7D2f-FMMnBJrRx/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/02-Kamus-Pattern-Crypto-Kalimasada/05-Crab-Pattern",
    category: "Crypto Trading",
  },
  {
    id: "6",
    title: "Diamond Pattern",
    drive: "https:/drive.google.com/file/d/1JIVXNQXAEjSsOZDGuX3-lwihd0T0bcyA/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/02-Kamus-Pattern-Crypto-Kalimasada/06-Diamond-Pattern",
    category: "Crypto Trading",
  },
  {
    id: "7",
    title: "Broadening Pattern",
    drive: "https:/drive.google.com/file/d/136s5lH2xFItq7DdxfeDjMks826MPHCXc/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/02-Kamus-Pattern-Crypto-Kalimasada/07-Broadening-Pattern",
    category: "Crypto Trading",
  },
  {
    id: "8",
    title: "Andrews Pitchfork Pattern",
    drive: "https:/drive.google.com/file/d/19EYka0yoswRahkuyM8sRzNKBJw2osxkH/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/02-Kamus-Pattern-Crypto-Kalimasada/08-Andrews-Pitchfork-Pattern",
    category: "Crypto Trading",
  },
  {
    id: "9",
    title: "Linear Regression Channel",
    drive: "https:/drive.google.com/file/d/1PMtIWE8dHeRXun5UCQ4JPDO-O94r6w-X/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/02-Kamus-Pattern-Crypto-Kalimasada/09-Linear-Regression-Channel",
    category: "Crypto Trading",
  },
  {
    id: "10",
    title: "Rectangle Channels",
    drive: "https:/drive.google.com/file/d/1h89IHUs6VLh16stY7KBy17aN4sGpr2iQ/view?usp=drive_link",
    link: "/Halaman/page/1-crypto-trading/02-Kamus-Pattern-Crypto-Kalimasada/10-Rectangle-Channels",
    category: "Crypto Trading",
  }
];