export const Data = [
  {
    id: "1",
    title: "Apa Itu Pattern",
    drive: "https://drive.google.com/file/d/1CpowG3ijXtsZAUudA8UjsjUkto6KbpNI",
    link: "/Halaman/page/1-crypto-trading/02-Kamus-Pattern-Crypto-Kalimasada/01-Apa-Itu-Pattern",
    category: "Crypto Trading",
  },
  {
    id: "2",
    title: "ABCD Pattern",
    drive: "https://drive.google.com/file/d/1Lw3RHSnW0plulGsvp-LCFCAsshUNy_mf",
    link: "/Halaman/page/1-crypto-trading/02-Kamus-Pattern-Crypto-Kalimasada/02-ABCD-Pattern",
    category: "Crypto Trading",
  },
  {
    id: "3",
    title: "Bat Pattern",
    drive: "https://drive.google.com/file/d/1KT66Wie3Vhh8FdIEezkRXxfLHnJXwBWw",
    link: "/Halaman/page/1-crypto-trading/02-Kamus-Pattern-Crypto-Kalimasada/03-Bat-Pattern",
    category: "Crypto Trading",
  },
  {
    id: "4",
    title: "Gartley Pattern",
    drive: "https://drive.google.com/file/d/1sGn48UkGaSMNnus8evMTdHwQx06gpIIg",
    link: "/Halaman/page/1-crypto-trading/02-Kamus-Pattern-Crypto-Kalimasada/04-Gartley-Pattern",
    category: "Crypto Trading",
  },
  {
    id: "5",
    title: "Crab Pattern",
    drive: "https://drive.google.com/file/d/19mxcNIgT8UWcieWcZ1dcb_nyfdcfBZE_",
    link: "/Halaman/page/1-crypto-trading/02-Kamus-Pattern-Crypto-Kalimasada/05-Crab-Pattern",
    category: "Crypto Trading",
  },
  {
    id: "6",
    title: "Diamond Pattern",
    drive: "https://drive.google.com/file/d/18ufUFD8SopEmZBGva4Exeq8BSzRquN6M",
    link: "/Halaman/page/1-crypto-trading/02-Kamus-Pattern-Crypto-Kalimasada/06-Diamond-Pattern",
    category: "Crypto Trading",
  },
  {
    id: "7",
    title: "Broadening Pattern",
    drive: "https://drive.google.com/file/d/1b3nv9pHgO8LOlXRwQAzzSDa4DBIu-Dhv",
    link: "/Halaman/page/1-crypto-trading/02-Kamus-Pattern-Crypto-Kalimasada/07-Broadening-Pattern",
    category: "Crypto Trading",
  },
  {
    id: "8",
    title: "Andrews Pitchfork Pattern",
    drive: "https://drive.google.com/file/d/10WLxN6bSDu6iXUz3vSefcmTjKx_O-xh-",
    link: "/Halaman/page/1-crypto-trading/02-Kamus-Pattern-Crypto-Kalimasada/08-Andrews-Pitchfork-Pattern",
    category: "Crypto Trading",
  },
  {
    id: "9",
    title: "Linear Regression Channel",
    drive: "https://drive.google.com/file/d/1nB5064h3Nai8Vx79oqzLMWEmVUleGdvL",
    link: "/Halaman/page/1-crypto-trading/02-Kamus-Pattern-Crypto-Kalimasada/09-Linear-Regression-Channel",
    category: "Crypto Trading",
  },
  {
    id: "10",
    title: "Rectangle Channels",
    drive: "https://drive.google.com/file/d/1In6s87gHV3ynTBD_NdokW1FE0Hj9HHw0",
    link: "/Halaman/page/1-crypto-trading/02-Kamus-Pattern-Crypto-Kalimasada/10-Rectangle-Channels",
    category: "Crypto Trading",
  }
];