export const Data = [
  {
    id: "1",
    title: "Apa Itu Pattern",
    drive: "https://drive.google.com/file/d/16fQl5OlLi19-Des0BHDgicSzmSCTTpVo/view?usp=drivesdk",
    link: "/Halaman/page/1-crypto-trading/02-Kamus-Pattern-Crypto-Kalimasada/01-Apa-Itu-Pattern",
    category: "Crypto Trading",
  },
  {
    id: "2",
    title: "ABCD Pattern",
    drive: "https://drive.google.com/file/d/16zzhNTOjcjwhwk0p0qnuRkF15zVoG0z_/view?usp=drivesdk",
    link: "/Halaman/page/1-crypto-trading/02-Kamus-Pattern-Crypto-Kalimasada/02-ABCD-Pattern",
    category: "Crypto Trading",
  },
  {
    id: "3",
    title: "Bat Pattern",
    drive: "https://drive.google.com/file/d/175Y4TlA0LkpaHJLCngJppGtkiEAa2Tfy/view?usp=drivesdk",
    link: "/Halaman/page/1-crypto-trading/02-Kamus-Pattern-Crypto-Kalimasada/03-Bat-Pattern",
    category: "Crypto Trading",
  },
  {
    id: "4",
    title: "Gartley Pattern",
    drive: "https://drive.google.com/file/d/179Se11CCfUZ7OPLqzMXWf1xhCdZOzes6/view?usp=drivesdk",
    link: "/Halaman/page/1-crypto-trading/02-Kamus-Pattern-Crypto-Kalimasada/04-Gartley-Pattern",
    category: "Crypto Trading",
  },
  {
    id: "5",
    title: "Crab Pattern",
    drive: "https://drive.google.com/file/d/16nZu07RryHCBQbLcD7qWgkjI8bhbxPvC/view?usp=drivesdk",
    link: "/Halaman/page/1-crypto-trading/02-Kamus-Pattern-Crypto-Kalimasada/05-Crab-Pattern",
    category: "Crypto Trading",
  },
  {
    id: "6",
    title: "Diamond Pattern",
    drive: "https://drive.google.com/file/d/16ZTCweKGIk8DENd9TnNT455KUKXeyCog/view?usp=drivesdk",
    link: "/Halaman/page/1-crypto-trading/02-Kamus-Pattern-Crypto-Kalimasada/06-Diamond-Pattern",
    category: "Crypto Trading",
  },
  {
    id: "7",
    title: "Broadening Pattern",
    drive: "https://drive.google.com/file/d/16xJ03c7_fxm6q78g5iB7xVqWcadfhiAI/view?usp=drivesdk",
    link: "/Halaman/page/1-crypto-trading/02-Kamus-Pattern-Crypto-Kalimasada/07-Broadening-Pattern",
    category: "Crypto Trading",
  },
  {
    id: "8",
    title: "Andrews Pitchfork Pattern",
    drive: "https://drive.google.com/file/d/16ZXm1U7Yp1HWFKI_UYX3N4tIrjpotNFJ/view?usp=drivesdk",
    link: "/Halaman/page/1-crypto-trading/02-Kamus-Pattern-Crypto-Kalimasada/08-Andrews-Pitchfork-Pattern",
    category: "Crypto Trading",
  },
  {
    id: "9",
    title: "Linear Regression Channel",
    drive: "https://drive.google.com/file/d/16rQJ8s2y3TXOOLFuso3AKu23pKgcXLpp/view?usp=drivesdk",
    link: "/Halaman/page/1-crypto-trading/02-Kamus-Pattern-Crypto-Kalimasada/09-Linear-Regression-Channel",
    category: "Crypto Trading",
  },
  {
    id: "10",
    title: "Rectangle Channels",
    drive: "https://drive.google.com/file/d/16_WNXeEPvqE5JJU0_BkMhdjnz1qQUGZO/view?usp=drivesdk",
    link: "/Halaman/page/1-crypto-trading/02-Kamus-Pattern-Crypto-Kalimasada/10-Rectangle-Channels",
    category: "Crypto Trading",
  }
];