export const Data = [
  {
    id: "1",
    title: "Mimpi Besar, tapi Seberapa",
    drive: "https://drive.google.com/file/d/13XQmtt2m4PWyzBBrA-7C-oLvSMP9XD1t",
    link: "/Halaman/page/5-ternak-uang/23/1",
    category: "Stock and Finance",
  },
  {
    id: "2",
    title: "Level Finansial Versi Ternak Uang",
    drive: "https://drive.google.com/file/d/1RrV-Cp0pZulvAa0mDlaYkC-6wEXwyN_0",
    link: "/Halaman/page/5-ternak-uang/23/2",
    category: "Stock and Finance",
  },
  {
    id: "3",
    title: "Introduction",
    drive: "https://drive.google.com/file/d/1vC1yBTMVeny_AaxhFu_2d0fS6FiEpV2s",
    link: "/Halaman/page/5-ternak-uang/23/3",
    category: "Stock and Finance",
  },
  {
    id: "4",
    title: "Sekolah, Kuliah",
    drive: "https://drive.google.com/file/d/1f0tDsBP78mQvW1nf8rhpp2a0bsCZm-pd",
    link: "/Halaman/page/5-ternak-uang/23/4",
    category: "Stock and Finance",
  },
  {
    id: "5",
    title: "Intern",
    drive: "https://drive.google.com/file/d/15Z9MtjvIEJMeYj2RnE8adfxGNPPWwCe4",
    link: "/Halaman/page/5-ternak-uang/23/5",
    category: "Stock and Finance",
  },
  {
    id: "6",
    title: "Baru Masuk Dunia Kerja",
    drive: "https://drive.google.com/file/d/1ReU_adh4bpLhKFxDI32qdRyetxVlYu-m",
    link: "/Halaman/page/5-ternak-uang/23/6",
    category: "Stock and Finance",
  },
  {
    id: "7",
    title: "Bekerja dengan 1-2 Tanggungan",
    drive: "https://drive.google.com/file/d/1tsUjl0QdqLwE-hkpwvYlCdM_N07-kBOs",
    link: "/Halaman/page/5-ternak-uang/23/7",
    category: "Stock and Finance",
  },
  {
    id: "8",
    title: "Berbisnis, Free Lancing",
    drive: "https://drive.google.com/file/d/1SJHSMw9SB25UPFys1gko6aUDpT7j3Zfu",
    link: "/Halaman/page/5-ternak-uang/23/8",
    category: "Stock and Finance",
  },
  {
    id: "9",
    title: "Mempersiapkan Pensiun",
    drive: "https://drive.google.com/file/d/1lEkSahhuYuv0rHzA70BtGi9rHVPhW8se",
    link: "/Halaman/page/5-ternak-uang/23/9",
    category: "Stock and Finance",
  },
  {
    id: "10",
    title: "Rahasia Sukses",
    drive: "https://drive.google.com/file/d/1EirGoArJ-mF-tsrxHKhhYDiGqgVGq6G_",
    link: "/Halaman/page/5-ternak-uang/23/10",
    category: "Stock and Finance",
  },
];