export const Data = [
  {
    id: "1",
    title: "Instrumen Proteksi",
    drive: "https://drive.google.com/file/d/17CTtuVy4SRQ6YL0qjWsy7_8tVWq-F4xV",
    link: "/Halaman/page/5-ternak-uang/18/1",
    category: "Stock and Finance",
  },
  {
    id: "2",
    title: "Kamus Dasar Asuransi",
    drive: "https://drive.google.com/file/d/1FM4yXeemmmIwKgJx7_NLCU4TLUEnNk2W",
    link: "/Halaman/page/5-ternak-uang/18/2",
    category: "Stock and Finance",
  },
  {
    id: "3",
    title: "Insurance Life Cycle",
    drive: "https://drive.google.com/file/d/12bugJ1EwE5XHjW2vR_6KRIZ36knuntlm",
    link: "/Halaman/page/5-ternak-uang/18/3",
    category: "Stock and Finance",
  },
  {
    id: "4",
    title: "Bagaimana Asuransi Bekerja",
    drive: "https://drive.google.com/file/d/1HWFS5VDLL-7Jv50R4Vq3xnciUCVDA23c",
    link: "/Halaman/page/5-ternak-uang/18/4",
    category: "Stock and Finance",
  },
  {
    id: "5",
    title: "Jenis Asuransi Ini Perlu Kamu Ketahui",
    drive: "https://drive.google.com/file/d/1EKE5AXaqnIursOl9uvKQDDMBx7aYjUWH",
    link: "/Halaman/page/5-ternak-uang/18/5",
    category: "Stock and Finance",
  },
  {
    id: "6",
    title: "Asuransi Jiwa",
    drive: "https://drive.google.com/file/d/17NP9IG-JaQjaenkBP9FfJg_FqP6bb-oV",
    link: "/Halaman/page/5-ternak-uang/18/6",
    category: "Stock and Finance",
  },
  {
    id: "7",
    title: "Asuransi Kesehatan",
    drive: "https://drive.google.com/file/d/1T0zxKhJQBcjL2blvocdCgPSBPkSvw3Z0",
    link: "/Halaman/page/5-ternak-uang/18/7",
    category: "Stock and Finance",
  },
  {
    id: "8",
    title: "Asuransi Penyakit Kritis",
    drive: "https://drive.google.com/file/d/1nUNoTOy1toPCvY_vr3wjBc30u1IdpRk1",
    link: "/Halaman/page/5-ternak-uang/18/8",
    category: "Stock and Finance",
  },
  {
    id: "9",
    title: "Unitlink vs Tradisional (Part 1)",
    drive: "https://drive.google.com/file/d/1Qh8GJYhDUF97BSch6JOufrwkj73Hi-0z",
    link: "/Halaman/page/5-ternak-uang/18/9",
    category: "Stock and Finance",
  },
  {
    id: "10",
    title: "Unitlink vs Tradisional (Part 2)",
    drive: "https://drive.google.com/file/d/1CPlaOvY_A4u7kdeQTgtuBKsenfsKuzEX",
    link: "/Halaman/page/5-ternak-uang/18/10",
    category: "Stock and Finance",
  },
  {
    id: "11",
    title: "cara memilih asuransi yang tepat",
    drive: "https://drive.google.com/file/d/13x3hJUeMvAlC_ZeGQ2aaIFsLvKixlaQC",
    link: "/Halaman/page/5-ternak-uang/18/11",
    category: "Stock and Finance",
  },
  {
    id: "12",
    title: "Hitung UP ala Financial Planner",
    drive: "https://drive.google.com/file/d/1AYSpPd9ZVURs2ESAc-tSEjx5dioa48r-",
    link: "/Halaman/page/5-ternak-uang/18/12",
    category: "Stock and Finance",
  },
  {
    id: "13",
    title: "Bedah Asuransi Unitlink Kesehatan",
    drive: "https://drive.google.com/file/d/1mF_DcYI9rgKH43nsZKuH9wje6gc0WmYI",
    link: "/Halaman/page/5-ternak-uang/18/13",
    category: "Stock and Finance",
  },
  {
    id: "14",
    title: "Bedah Asuransi Tradisional",
    drive: "https://drive.google.com/file/d/1uJHe5OsBH_f4udcBZN-ZjkY5dANDge2z",
    link: "/Halaman/page/5-ternak-uang/18/14",
    category: "Stock and Finance",
  },
  {
    id: "15",
    title: "Asuransi101 Memilih Asuransi yang Tepat Closing Challenge Buat Kamu",
    drive: "https://drive.google.com/file/d/1lVQ4MD2DzIniAQsNpVu0J55xQBInFDBw",
    link: "/Halaman/page/5-ternak-uang/18/15",
    category: "Stock and Finance",
  },
];