export const Data = [
  {
    id: "1",
    title: "Intro to Modern Day Crypto Trading",
    drive: "https://drive.google.com/file/d/1ABeo3l3HyLNMTvI-NaIhMEQJuHD0LFrz/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/1-The-Art-of-Crypto-Trading/1-Intro-to-Modern-Day-Crypto-Trading",
    category: "The Art of Crypto Trading",
  },
  {
    id: "2",
    title: "How to Transform a Crypto Bro into Crypto Pro",
    drive: "https://drive.google.com/file/d/1N83sEuWBx_7u9l2QExO6tVbH_GluP_0P/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/1-The-Art-of-Crypto-Trading/2-How-to-Transform-a-Crypto-Bro-into-Crypto-Pro",
    category: "The Art of Crypto Trading",
  },
  {
    id: "3",
    title: "Deep Understanding of Narrative Research",
    drive: "https://drive.google.com/file/d/1NBqMwZ7sTw4jYKMUjWs5aOyumuFhKBGm/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/1-The-Art-of-Crypto-Trading/3-Deep-Understanding-of-Narrative-Research",
    category: "The Art of Crypto Trading",
  },
  {
    id: "4",
    title: "Deep Understanding of Fundamental Research",
    drive: "https://drive.google.com/file/d/1NFvBHeFaKdzATiTvM01iYD26fzQwAaMa/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/1-The-Art-of-Crypto-Trading/4-Deep-Understanding-of-Fundamental-Research",
    category: "The Art of Crypto Trading",
  },
  {
    id: "5",
    title: "Deep Understanding of Technical Research",
    drive: "https://drive.google.com/file/d/1NHX2ynEIwHbWtl_u0fkJKwhJKTg3n4Is/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/1-The-Art-of-Crypto-Trading/5-Deep-Understanding-of-Technical-Research",
    category: "The Art of Crypto Trading",
  },
  {
    id: "6",
    title: "Comprehensive Guide on How to Market Timing and Market Positioning",
    drive: "https://drive.google.com/file/d/1NKmFiVsrtBwVdMzJwdoxrjBAAY90WObR/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/1-The-Art-of-Crypto-Trading/6-Comprehensive-Guide-on-How-to-Market-Timing-and-Market-Positioning",
    category: "The Art of Crypto Trading",
  },
  {
    id: "7",
    title: "Step by Step Portfolio Allocation and Portfolio Management",
    drive: "hhttps://drive.google.com/file/d/1NLh0cdgtMhYYaKg3-JuxGYftp82XtwRA/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/1-The-Art-of-Crypto-Trading/7-Step-by-Step-Portfolio-Allocation-and-Portfolio-Management",
    category: "The Art of Crypto Trading",
  },
];