export const Data = [
  {
    id: "1",
    title: "1 Apa Itu Uang",
    drive: "https://drive.google.com/file/d/1yFKyKlv8S-TS8zu5KcxkDiji92xQrcfq",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/1-Apa-Itu-Uang",
    category: "Crypto Blockchain",
  },
  {
    id: "2",
    title: "2 Kriptografi dan Hash Function",
    drive: "https://drive.google.com/file/d/1tfgUNd1_qGnatZle_TpGoByx29rcoKAA",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/2-Kriptografi-dan-Hash-Function",
    category: "Crypto Blockchain",
  },
  {
    id: "3",
    title: "3 Byzantine Generals Problem",
    drive: "https://drive.google.com/file/d/1ZlJKLxcHWkGaogOCbJTKCkn_wZ9Ho8c3",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/3-Byzantine-Generals-Problem",
    category: "Crypto Blockchain",
  },
  {
    id: "4",
    title: "4 The Basics of Bitcoin and Blockchain",
    drive: "https://drive.google.com/file/d/1NC0BC776d_mLs4pf-M3yMQSwpa1INQCv",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/4-The-Basics-of-Bitcoin-and-Blockchain",
    category: "Crypto Blockchain",
  },
  {
    id: "5",
    title: "5 Mining Concepts",
    drive: "https://drive.google.com/file/d/1QAWUzVWp-8IV1lc0Nf9CQ8HxQrNpR4YM",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/5-Mining-Concepts",
    category: "Crypto Blockchain",
  },
  {
    id: "6",
    title: "6 Crypto Wallets",
    drive: "https://drive.google.com/file/d/1P8274z9no0CtjyOCe626xUnKcc4sT8Nd",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/6-Crypto-Wallets",
    category: "Crypto Blockchain",
  },
  {
    id: "7",
    title: "7 How to Earn Bitcoin",
    drive: "https://drive.google.com/file/d/1OlT8_58P9r2DdIujMDSmyI-uC2PMZXOx",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/7-How-to-Earn-Bitcoin",
    category: "Crypto Blockchain",
  },
  {
    id: "8",
    title: "8 Bitcoin Usage",
    drive: "https://drive.google.com/file/d/1QGt9QDeHHg37tthqTCgmefA4VANZedlC",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/8-Bitcoin-Usage",
    category: "Crypto Blockchain",
  },
  {
    id: "9",
    title: "9 Blockchain and Consensus Algorithm",
    drive: "https://drive.google.com/file/d/1cCiCE5xfOi4WhEyeEO-gg8UtjYslvhNc",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/9-Blockchain-and-Consensus-Algorithm",
    category: "Crypto Blockchain",
  },
  {
    id: "10",
    title: "10 Blockchain Security",
    drive: "https://drive.google.com/file/d/1L1LBMPM9C4M1a5c8rd6pOt0cwYEy2EE6",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/10-Blockchain-Security",
    category: "Crypto Blockchain",
  },
  {
    id: "11",
    title: "11 Problem Pada Blockchain",
    drive: "https://drive.google.com/file/d/1JtqJ3FPxXp2FvE8htZvtxOZzs44oHvaV",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/11-Problem-Pada-Blockchain",
    category: "Crypto Blockchain",
  },
  {
    id: "12",
    title: "12 Privasi dan Anonimitas",
    drive: "https://drive.google.com/file/d/11l-8GzJU2FoZ1_sfGTJxIecHQCiDyD8E",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/12-Privasi-dan-Anonimitas",
    category: "Crypto Blockchain",
  },
  {
    id: "13",
    title: "13 Perangkat Anonimitas",
    drive: "https://drive.google.com/file/d/1d7TjLy-YUqQKnkAxBBtz3sSElf8k1jwL",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/13-Perangkat-Anonimitas",
    category: "Crypto Blockchain",
  },
  {
    id: "14",
    title: "14 Pemanfaatan Blockchain",
    drive: "https://drive.google.com/file/d/1kGmxxl3sbBmu1DfXeOKfZB4pEBsjK-y-",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/14-Pemanfaatan-Blockchain",
    category: "Crypto Blockchain",
  },
  {
    id: "15",
    title: "15 Teknologi Blockchain",
    drive: "https://drive.google.com/file/d/1k2xky1shsTP-pwNrdvt-sfWjFeqFPNT6",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/15-Teknologi-Blockchain",
    category: "Crypto Blockchain",
  }
];