export const Data = [
  {
    id: "1",
    title: "1 Apa Itu Uang",
    drive: "https://drive.google.com/file/d/1Wg2qGmwbzA2zGeytyycKqxwt1KBLQcim/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/1-Apa-Itu-Uang",
    category: "Crypto Blockchain",
  },
  {
    id: "2",
    title: "2 Kriptografi dan Hash Function",
    drive: "https://drive.google.com/file/d/1X-2ZFKzdQA9pySfwYi9G8N5uHwaDMQMm/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/2-Kriptografi-dan-Hash-Function",
    category: "Crypto Blockchain",
  },
  {
    id: "3",
    title: "3 Byzantine Generals Problem",
    drive: "https://drive.google.com/file/d/1Wtlw1IwvMBUv3ldtI5KLacxqYYOT0ffL/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/3-Byzantine-Generals-Problem",
    category: "Crypto Blockchain",
  },
  {
    id: "4",
    title: "4 The Basics of Bitcoin and Blockchain",
    drive: "https://drive.google.com/file/d/1WsqNn3aePmmGB95cPG3l9QM2H1VYg9qY/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/4-The-Basics-of-Bitcoin-and-Blockchain",
    category: "Crypto Blockchain",
  },
  {
    id: "5",
    title: "5 Mining Concepts",
    drive: "https://drive.google.com/file/d/1WmX20sxH6bifuAIJsOrEoBfICVuLys2O/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/5-Mining-Concepts",
    category: "Crypto Blockchain",
  },
  {
    id: "6",
    title: "6 Crypto Wallets",
    drive: "https://drive.google.com/file/d/1X89_4-zUNlVTa7WBVRil-krSsqHmQ09M/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/6-Crypto-Wallets",
    category: "Crypto Blockchain",
  },
  {
    id: "7",
    title: "7 How to Earn Bitcoin",
    drive: "https://drive.google.com/file/d/1X890m9FrzMyNS4Fx_e856E4YBJOH_oJy/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/7-How-to-Earn-Bitcoin",
    category: "Crypto Blockchain",
  },
  {
    id: "8",
    title: "8 Bitcoin Usage",
    drive: "https://drive.google.com/file/d/1X3WOUR_ezEsCnHiyPOqyeP7hpwmaJoCc/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/8-Bitcoin-Usage",
    category: "Crypto Blockchain",
  },
  {
    id: "9",
    title: "9 Blockchain and Consensus Algorithm",
    drive: "https://drive.google.com/file/d/1X-fSPAJNGS2DmXpwLEDRTUNyGVCRM4Ua/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/9-Blockchain-and-Consensus-Algorithm",
    category: "Crypto Blockchain",
  },
  {
    id: "10",
    title: "10 Blockchain Security",
    drive: "https://drive.google.com/file/d/1XDbIZzL1Il56kc-ei6yWs_l6bL9hnqcW/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/10-Blockchain-Security",
    category: "Crypto Blockchain",
  },
  {
    id: "11",
    title: "11 Problem Pada Blockchain",
    drive: "https://drive.google.com/file/d/1XAY-cveolvd_2LHK3qza38JSz9nkLdkt/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/11-Problem-Pada-Blockchain",
    category: "Crypto Blockchain",
  },
  {
    id: "12",
    title: "12 Privasi dan Anonimitas",
    drive: "https://drive.google.com/file/d/1X913aLJ1rM7IYnJaPTK6YPeE8uOq9Nqm/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/12-Privasi-dan-Anonimitas",
    category: "Crypto Blockchain",
  },
  {
    id: "13",
    title: "13 Perangkat Anonimitas",
    drive: "https://drive.google.com/file/d/1Xaj4K2YzMk45SU-XoOvoAyLyGTr809rS/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/13-Perangkat-Anonimitas",
    category: "Crypto Blockchain",
  },
  {
    id: "14",
    title: "14 Pemanfaatan Blockchain",
    drive: "https://drive.google.com/file/d/1XU0SazGG1n309s6uLsEjNS5lXcycRTxO/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/14-Pemanfaatan-Blockchain",
    category: "Crypto Blockchain",
  },
  {
    id: "15",
    title: "15 Teknologi Blockchain",
    drive: "https://drive.google.com/file/d/1XRoZTGEtNhtxXf5BboZ5CuMOZuQxcuyY/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/15-Teknologi-Blockchain",
    category: "Crypto Blockchain",
  }
];