export const Data = [
  {
    id: "1",
    title: "1 Apa Itu Uang",
    drive: "https://drive.google.com/file/d/1v_C2IQ4NNoPDSbvkjIyFZICC2IBYdGMl/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/1-Apa-Itu-Uang",
    category: "Crypto Blockchain",
  },
  {
    id: "2",
    title: "2 Kriptografi dan Hash Function",
    drive: "https://drive.google.com/file/d/1191FnUG1rMlW3D1dd0kPdNtC-LeElHRX/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/2-Kriptografi-dan-Hash-Function",
    category: "Crypto Blockchain",
  },
  {
    id: "3",
    title: "3 Byzantine Generals Problem",
    drive: "https://drive.google.com/file/d/1ASDKVfQVFgU48VWd24JoZoUqjZRnNytd/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/3-Byzantine-Generals-Problem",
    category: "Crypto Blockchain",
  },
  {
    id: "4",
    title: "4 The Basics of Bitcoin and Blockchain",
    drive: "https://drive.google.com/file/d/193F1_bK4GgypBGUewYlaiGDAebvHbc6F/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/4-The-Basics-of-Bitcoin-and-Blockchain",
    category: "Crypto Blockchain",
  },
  {
    id: "5",
    title: "5 Mining Concepts",
    drive: "https://drive.google.com/file/d/1orFGKeC9MxQ2zp1glK1q-WFpFxSzVdVk/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/5-Mining-Concepts",
    category: "Crypto Blockchain",
  },
  {
    id: "6",
    title: "6 Crypto Wallets",
    drive: "https://drive.google.com/file/d/1hV5JLkyJdh9_JlJ9Ft6MoveXKJrpu-_L/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/6-Crypto-Wallets",
    category: "Crypto Blockchain",
  },
  {
    id: "7",
    title: "7 How to Earn Bitcoin",
    drive: "https://drive.google.com/file/d/1IiwjItVN5EZlOa8hLzrwYOab7J1E9AVL/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/7-How-to-Earn-Bitcoin",
    category: "Crypto Blockchain",
  },
  {
    id: "8",
    title: "8 Bitcoin Usage",
    drive: "https://drive.google.com/file/d/1lfItFnrc8iM1oB3_7eRe5-xEYzOcZogU/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/8-Bitcoin-Usage",
    category: "Crypto Blockchain",
  },
  {
    id: "9",
    title: "9 Blockchain and Consensus Algorithm",
    drive: "https://drive.google.com/file/d/1GkdTSlq0UpxJkry56eoUMToN5fzt0BsA/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/9-Blockchain-and-Consensus-Algorithm",
    category: "Crypto Blockchain",
  },
  {
    id: "10",
    title: "10 Blockchain Security",
    drive: "https://drive.google.com/file/d/1uUwebqNEN9Er8dVZxOeeO7Mr2wN15tYJ/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/10-Blockchain-Security",
    category: "Crypto Blockchain",
  },
  {
    id: "11",
    title: "11 Problem Pada Blockchain",
    drive: "https://drive.google.com/file/d/1zOsd4OQiNQU_L1vvTPPhxpSWeCSlIlao/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/11-Problem-Pada-Blockchain",
    category: "Crypto Blockchain",
  },
  {
    id: "12",
    title: "12 Privasi dan Anonimitas",
    drive: "https://drive.google.com/file/d/1DkbqZ4MgDoue6MvdXUd67hMOIzMo0MNR/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/12-Privasi-dan-Anonimitas",
    category: "Crypto Blockchain",
  },
  {
    id: "13",
    title: "13 Perangkat Anonimitas",
    drive: "https://drive.google.com/file/d/1XkrqOG0YDUKfj8d1QoRIEF4CAHLAhQFU/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/13-Perangkat-Anonimitas",
    category: "Crypto Blockchain",
  },
  {
    id: "14",
    title: "14 Pemanfaatan Blockchain",
    drive: "https://drive.google.com/file/d/1cTqLTjqcWR7DMNWKTjkvIPo9QN6Zf7pm/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/14-Pemanfaatan-Blockchain",
    category: "Crypto Blockchain",
  },
  {
    id: "15",
    title: "15 Teknologi Blockchain",
    drive: "https://drive.google.com/file/d/1YBCZFNfTQGEvVTXA2ijj2EI8Km4RspGd/view?usp=drive_link",
    link: "/Halaman/page/3-crypto-blockchain/6-Cryptocurrency-Fundamentals/15-Teknologi-Blockchain",
    category: "Crypto Blockchain",
  }
];