export const Data = [
  // {
  //   id: "1",
  //   title: "The Art of Crypto Trading",
  //   drive: "",
  //   link: "/Halaman/page/4-liveclass/1-The-Art-of-Crypto-Trading",
  //   category: "Live Class",
  // },
  {
    id: "2",
    title: "Crypto Market Outlook 2025",
    drive: "https://drive.google.com/file/d/1JEBXBBAwbYsxPNg0rdrLU01fK9OkLlnn/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/2-Crypto-Market-Outlook-2025",
    category: "Webinar & Live Class",
  },
  {
    id: "3",
    title: "US Election Market Outlook",
    drive: "https://drive.google.com/file/d/1JWNVulz1bzjeAyE0SiWIOJKSBJrV00Iv/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/3-US-Election-Market-Outlook",
    category: "Webinar & Live Class",
  },
  {
    id: "4",
    title: "Preparing For Octobull",
    drive: "https://drive.google.com/file/d/1JMfm_MlcyeKMScSWwMe1FsJglcyfHpm6/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/4-Preparing-For-Octobull",
    category: "1 oktober 2024",
  },
  {
    id: "5",
    title: "Crypto Trading Psychology",
    drive: "https://drive.google.com/file/d/1IeNPjms2OYElJTRJR8w-f4FPJn6cmrsG/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/5-Crypto-Trading-Psychology",
    category: "Webinar & Live Class",
  },
  {
    id: "6",
    title: "Mastering Altcoins",
    drive: "https://drive.google.com/file/d/1IIEw_B3iIzNDzr8mapvYtNURaPIXGeIT/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/6-Mastering-Altcoins",
    category: "Webinar & Live Class",
  },
  {
    id: "7",
    title: "Masterclass Session 1 Crypto Smart Money",
    drive: "https://drive.google.com/file/d/1JIvkkxKLV017K8-64zrBs70Cg6vpzLDR/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/7-Masterclass-Session-1-Crypto-Smart-Money",
    category: "Masterclass",
  },
  {
    id: "12",
    title: "Big Crypto Thesis",
    drive: "https://drive.google.com/file/d/1JqdR-53HzS2wn8FGjJErsMB4Z3Ne3UAS/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/12-Big-Crypto-Thesis",
    category: "Webinar & Live Class",
  },
  {
    id: "13",
    title: "Akademi Crypto Grand Launching",
    drive: "https://drive.google.com/file/d/1IKULkvFRRWudKXUpH4NQszj6ffojx0AZ/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/13-Akademi-Crypto-Grand-Launching",
    category: "Webinar & Live Class",
  },
  {
    id: "14",
    title: "BTC to Alts Switching Timing",
    drive: "https://drive.google.com/file/d/1JGB5fGcUZuTx59fRMGY6LeylJ_4ya9m8/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/14-BTC-to-Alts-Switching-Timing",
    category: "Webinar & Live Class",
  },
  {
    id: "15",
    title: "Narratives for 2024 Bull Run",
    drive: "https://drive.google.com/file/d/1JiPPRi9tvq6IPkxrMpB9Zwc2LFvCOEF5/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/15-Narratives-for-2024-Bull-Run",
    category: "Webinar & Live Class",
  },
  {
    id: "16",
    title: "Strategi Jadi Miliarder Dari Crypto",
    drive: "https://drive.google.com/file/d/1Jus1DNjqrnFh-YGE9Cgd3tfIGYxpX7WC/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/16-Strategi-Jadi-Miliarder-Dari-Crypto",
    category: "Webinar & Live Class",
  },
  {
    id: "17",
    title: "Kopi Darat Akademi Crypto 9 September 2023",
    drive: "https://drive.google.com/file/d/1IEILDu4GvysdLiknGLKkO7kWHlaMMhUG/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/17-Kopi-Darat-Akademi-Crypto-9-September-2023",
    category: "Webinar & Live Class",
  },
  {
    id: "18",
    title: "Cara Mencari Altcoin yang Minimal Akan Naik 10X",
    drive: "https://drive.google.com/file/d/1JH-j_r8IV2bg8dTW6Dmz00HlqjN9If8J/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/18-Cara-Mencari-Altcoin-yang-Minimal-Akan-Naik-10X",
    category: "Webinar & Live Class",
  },
  {
    id: "19",
    title: "10X YOUR PORTFOLIO THIS BULLRUN",
    drive: "https://drive.google.com/file/d/1Jj6aqpgPHO_GJxNPqAmobHCCJvJ-xkij/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/19-10X-YOUR-PORTFOLIO-THIS-BULLRUN",
    category: "Webinar & Live Class",
  },
  {
    id: "20",
    title: "Riding the Crypto Super Mega Cycle",
    drive: "https://drive.google.com/file/d/1JndxTPTuXZ-4qb-24SBAFHoQbSGvvQkx/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/20-Riding-the-Crypto-Super-Mega-Cycle",
    category: "Webinar & Live Class",
  },
  {
    id: "21",
    title: "Cara Menggandakan Portofolio di AI Supercycle",
    drive: "https://drive.google.com/file/d/1JZuflqGwTSgViOWfw1sOw0M6MOIyYaGi/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/21-Cara-Menggandakan-Portofolio-di-AI-Supercycle",
    category: "17 januari 2025",
  },
  {
    id: "22",
    title: "2030 The Great Reset",
    drive: "https://drive.google.com/file/d/1JeHlG6VEWORxeVPQ5pxDHA_6F8lQ1TiV/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/22-2030-The-Great-Reset",
    category: "Webinar & Live Class",
  },
  {
    id: "23",
    title: "2025 Crypto Regulation",
    drive: "https://drive.google.com/file/d/1JerHApfev_lvLUvLp0HCcfcfTm9ERMPL/view?usp=drivesdk",
    link: "/Halaman/page/4-liveclass/23-2025-Crypto-Regulation",
    category: "Webinar & Live Class",
  },
];