export const Data = [
  // {
  //   id: "1",
  //   title: "The Art of Crypto Trading",
  //   drive: "",
  //   link: "/Halaman/page/4-liveclass/1-The-Art-of-Crypto-Trading",
  //   category: "Live Class",
  // },
  {
    id: "2",
    title: "Crypto Market Outlook 2025",
    drive: "https://drive.google.com/file/d/1LzkKP13gYi6VYU7AKVBc9xsy2MYJgJMB/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/2-Crypto-Market-Outlook-2025",
    category: "Webinar & Live Class",
  },
  {
    id: "3",
    title: "US Election Market Outlook",
    drive: "https://drive.google.com/file/d/1-VO2T4RBw-mVs9ZAFKd9uPYZzyThKkdZ/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/3-US-Election-Market-Outlook",
    category: "Webinar & Live Class",
  },
  {
    id: "4",
    title: "Preparing For Octobull",
    drive: "https://drive.google.com/file/d/1FxeiEoLnU37iGQADR69uyVJ31Rg-3qn3/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/4-Preparing-For-Octobull",
    category: "1 oktober 2024",
  },
  {
    id: "5",
    title: "Crypto Trading Psychology",
    drive: "https://drive.google.com/file/d/158Eek0igovhHbwyc8v_j9YntB3yFbQkm/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/5-Crypto-Trading-Psychology",
    category: "Webinar & Live Class",
  },
  {
    id: "6",
    title: "Mastering Altcoins",
    drive: "https://drive.google.com/file/d/1_VvD4kKzxqnV2BKkpIwBO_DkPDBo1YyE/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/6-Mastering-Altcoins",
    category: "Webinar & Live Class",
  },
  // {
  //   id: "7",
  //   title: "Masterclass Session 1 Crypto Smart Money",
  //   drive: "https://drive.google.com/file/d/1MwR8xHmcpIVbYTGYlitzkyLGs1M5CqjG/view?usp=drive_link",
  //   link: "/Halaman/page/4-liveclass/7-Masterclass-Session-1-Crypto-Smart-Money",
  //   category: "Masterclass",
  // },
  // {
  //   id: "8",
  //   title: "Masterclass Session 2 Crypto Harmonic Trading",
  //   drive: "https://drive.google.com/file/d/1pf4GQdXlDP5_eCJW7oRb4sjEKK78uEsT/view?usp=drive_link",
  //   link: "/Halaman/page/4-liveclass/8-Masterclass-Session-2-Crypto-Harmonic-Trading",
  //   category: "Masterclass",
  // },
  // {
  //   id: "9",
  //   title: "Masterclass Session 3 Crypto Order Flow",
  //   drive: "https://drive.google.com/file/d/14ePWKgNYMl_pIp3FZ7jb-ktYmY091sAG/view?usp=drive_link",
  //   link: "/Halaman/page/4-liveclass/9-Masterclass-Session-3-Crypto-Order-Flow",
  //   category: "Masterclass",
  // },
  // {
  //   id: "10",
  //   title: "Kuliah Crypto",
  //   drive: "",
  //   link: "/Halaman/page/4-liveclass/10-Kuliah-Crypto",
  //   category: "Webinar & Live Class",
  // },
  // {
  //   id: "11",
  //   title: "Bonus Sales Mastery",
  //   drive: "",
  //   link: "/Halaman/page/4-liveclass/11-Bonus-Sales-Mastery",
  //   category: "Webinar & Live Class",
  // },
  {
    id: "12",
    title: "Big Crypto Thesis",
    drive: "https://drive.google.com/file/d/1L6WWODgd4I8Osh51tDWEdDoH-UEHx_hB/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/12-Big-Crypto-Thesis",
    category: "Webinar & Live Class",
  },
  {
    id: "13",
    title: "Akademi Crypto Grand Launching",
    drive: "https://drive.google.com/file/d/1NWy4oFnXqLRb7Ts-zAOJBs5bkwRwOj8T/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/13-Akademi-Crypto-Grand-Launching",
    category: "Webinar & Live Class",
  },
  {
    id: "14",
    title: "BTC to Alts Switching Timing",
    drive: "https://drive.google.com/file/d/1F5aKWHKtNfR_iZFqWYFS8hztxT8gldLZ/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/14-BTC-to-Alts-Switching-Timing",
    category: "Webinar & Live Class",
  },
  {
    id: "15",
    title: "Narratives for 2024 Bull Run",
    drive: "https://drive.google.com/file/d/10KQtthJFOf3puKHAsQ8_5H9t16scUgrs/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/15-Narratives-for-2024-Bull-Run",
    category: "Webinar & Live Class",
  },
  {
    id: "16",
    title: "Strategi Jadi Miliarder Dari Crypto",
    drive: "https://drive.google.com/file/d/1gN1wcrR3nFweNxmxN30Rti9UoJyp8BUe/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/16-Strategi-Jadi-Miliarder-Dari-Crypto",
    category: "Webinar & Live Class",
  },
  {
    id: "17",
    title: "Kopi Darat Akademi Crypto 9 September 2023",
    drive: "https://drive.google.com/file/d/16b1gieX1nh0XLHBTVemMqdqJAFVS_bcn/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/17-Kopi-Darat-Akademi-Crypto-9-September-2023",
    category: "Webinar & Live Class",
  },
  {
    id: "18",
    title: "Cara Mencari Altcoin yang Minimal Akan Naik 10X",
    drive: "https://drive.google.com/file/d/1KoXMJOvQ800UxPw4BYVNIS6vLw0nObPj/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/18-Cara-Mencari-Altcoin-yang-Minimal-Akan-Naik-10X",
    category: "Webinar & Live Class",
  },
  {
    id: "19",
    title: "10X YOUR PORTFOLIO THIS BULLRUN",
    drive: "https://drive.google.com/file/d/1N7_8ABsCkF7ZMy1DQd9Po1IOa40zAWGP/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/19-10X-YOUR-PORTFOLIO-THIS-BULLRUN",
    category: "Webinar & Live Class",
  },
  {
    id: "20",
    title: "Riding the Crypto Super Mega Cycle",
    drive: "https://drive.google.com/file/d/18T5_JSz-U-Sz1k9YypYmAEKlNla7m9S4/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/20-Riding-the-Crypto-Super-Mega-Cycle",
    category: "Webinar & Live Class",
  },
  {
    id: "21",
    title: "Cara Menggandakan Portofolio di AI Supercycle",
    drive: "https://drive.google.com/file/d/1400yal8wWrOREBc79QdGWmAYD092X-Kw/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/21-Cara-Menggandakan-Portofolio-di-AI-Supercycle",
    category: "17 januari 2025",
  },
  {
    id: "22",
    title: "2030 The Great Reset",
    drive: "https://drive.google.com/file/d/14Zg9VI8tl4amMu-sfZStn8ny0FQYvZZT/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/22-2030-The-Great-Reset",
    category: "Webinar & Live Class",
  },
  {
    id: "23",
    title: "2025 Crypto Regulation",
    drive: "https://drive.google.com/file/d/1ukXrKlvNH2QLrqihBzA-OfCF9TJ4oNG5/view?usp=drive_link",
    link: "/Halaman/page/4-liveclass/23-2025-Crypto-Regulation",
    category: "Webinar & Live Class",
  }
];