export const Data = [
  {
    id: "1",
    title: "Telaah Laporan Keuangan Lebih Dalam",
    drive: "https://drive.google.com/file/d/1l29ly1T9Nd9VkwGVlm2BNVwERAA3auPu",
    link: "/Halaman/page/5-ternak-uang/20/1",
    category: "Stock and Finance",
  },
  {
    id: "2",
    title: "Understanding Company’s Business with Income Statement",
    drive: "https://drive.google.com/file/d/1X06drurfSYirL303PkJA2bk7Itkgbyv9",
    link: "/Halaman/page/5-ternak-uang/20/2",
    category: "Stock and Finance",
  },
  {
    id: "3",
    title: "Neraca Saldo 101 Part 1",
    drive: "https://drive.google.com/file/d/1KNTMdPp48M4-5pfP9C1diWhlrn9JYBls",
    link: "/Halaman/page/5-ternak-uang/20/3",
    category: "Stock and Finance",
  },
  {
    id: "4",
    title: "Neraca Saldo 101 Part 2",
    drive: "https://drive.google.com/file/d/1yliPz0y-IYVwzptt_LTY5SOF81gFTBGg",
    link: "/Halaman/page/5-ternak-uang/20/4",
    category: "Stock and Finance",
  },
  {
    id: "5",
    title: "Neraca Saldo 101 Part 3",
    drive: "https://drive.google.com/file/d/1Ro6foHbjp2vtuLOX6N2YoT-0RZE0_Q9e",
    link: "/Halaman/page/5-ternak-uang/20/5",
    category: "Stock and Finance",
  },
 {
    id: "6",
    title: "Step Menganalisa Laporan Arus Kas",
    drive: "https://drive.google.com/file/d/1oIa-axqpv1vtWA_sIO-7nJWk3eD_ccO7",
    link: "/Halaman/page/5-ternak-uang/20/6",
    category: "Stock and Finance",
  },
  {
    id: "7",
    title: "Yang Indah Belum Tentu Benar",
    drive: "https://drive.google.com/file/d/1hBZ-5KdteNkA98B3SHchZ6xzVVsRNoyD",
    link: "/Halaman/page/5-ternak-uang/20/7",
    category: "Stock and Finance",
  },
];