export const Data = [
  {
    id: "1",
    title: "Introduction",
    drive: "https://drive.google.com/file/d/1jUAnq7wArtuLYAA-AOL2f9TvYSbaFU8P",
    link: "/Halaman/page/5-ternak-uang/22/1",
    category: "Stock and Finance",
  },
  {
    id: "2",
    title: "Kenapa Belajar Excel",
    drive: "https://drive.google.com/file/d/1kQf30bYnDLW8EkN7avzlysQVB2Lmcc1G",
    link: "/Halaman/page/5-ternak-uang/22/2",
    category: "Stock and Finance",
  },
  {
    id: "3",
    title: "Apa Yang Akan Kita Bahas",
    drive: "https://drive.google.com/file/d/1V4ChnlZD9_eN4FcQoOzcCyY5ZrSXIGkn",
    link: "/Halaman/page/5-ternak-uang/22/3",
    category: "Stock and Finance",
  },
  {
    id: "4",
    title: "Keyboard atau Mouse",
    drive: "https://drive.google.com/file/d/1xIL2kjKMkP__-ftTbt6LRbPRCgigwaw1",
    link: "/Halaman/page/5-ternak-uang/22/4",
    category: "Stock and Finance",
  },
  {
    id: "5",
    title: "Yuk Praktek",
    drive: "https://drive.google.com/file/d/1_ERgMCpd9Tk1EM4S7C0w6Kv9y9Jyo8gz",
    link: "/Halaman/page/5-ternak-uang/22/5",
    category: "Stock and Finance",
  },
  {
    id: "6",
    title: "Layout Overview",
    drive: "https://drive.google.com/file/d/1TU88nadyaYSmjZhbC2JGHrvKGGmvnsQq",
    link: "/Halaman/page/5-ternak-uang/22/6",
    category: "Stock and Finance",
  },
  {
    id: "7",
    title: "Ribbon Part 1",
    drive: "https://drive.google.com/file/d/1m_4yUVXQeq1VLGFl54t6ur3-dVza_dWx",
    link: "/Halaman/page/5-ternak-uang/22/7",
    category: "Stock and Finance",
  },
  {
    id: "8",
    title: "Ribbon Part 2",
    drive: "https://drive.google.com/file/d/1jOAKQbFQaTY00IDHMZiM9yqcobWgdokO",
    link: "/Halaman/page/5-ternak-uang/22/8",
    category: "Stock and Finance",
  },
  {
    id: "9",
    title: "Shortcuts Dalam mengakses ribbon",
    drive: "https://drive.google.com/file/d/1r-t5oxzndDp20PdKQbR5jig7bDcO7XRT",
    link: "/Halaman/page/5-ternak-uang/22/9",
    category: "Stock and Finance",
  },
  {
    id: "10",
    title: "Overview",
    drive: "https://drive.google.com/file/d/1tuE0ftK2ucB9tnDJFQjeDTGWAn1rLGUv",
    link: "/Halaman/page/5-ternak-uang/22/10",
    category: "Stock and Finance",
  },
  {
    id: "11",
    title: "Excel Option General",
    drive: "https://drive.google.com/file/d/1kmoQFbLGBsrqPxh3lu31b9_7CagbtxtJ",
    link: "/Halaman/page/5-ternak-uang/22/11",
    category: "Stock and Finance",
  },
  {
    id: "12",
    title: "Excel Option Formulas",
    drive: "https://drive.google.com/file/d/1CDCWMNTMLTzff1DTO39A-lCIfUvuJSFt",
    link: "/Halaman/page/5-ternak-uang/22/12",
    category: "Stock and Finance",
  },
  {
    id: "13",
    title: "Excel Option Data Proofing Save Language Ease of Access Settings",
    drive: "https://drive.google.com/file/d/1Ok4-nqAgUL6WaUeXO2FqTDm5oAqVw0mZ",
    link: "/Halaman/page/5-ternak-uang/22/13",
    category: "Stock and Finance",
  },
  {
    id: "14",
    title: "Excel Option Advanced Settings Customize Ribbon Quick Access Toolbar Add Ins",
    drive: "https://drive.google.com/file/d/12ruBu--HqV3j_szu9Fzn7ceof4qHXRUd",
    link: "/Halaman/page/5-ternak-uang/22/14",
    category: "Stock and Finance",
  },
  {
    id: "15",
    title: "Overview",
    drive: "https://drive.google.com/file/d/1FLqxitKw2ebdhhc2zuNTYjpc10VySIyG",
    link: "/Halaman/page/5-ternak-uang/22/15",
    category: "Stock and Finance",
  },
  {
    id: "16",
    title: "Format Background Special Numbers Column Width",
    drive: "https://drive.google.com/file/d/1zkjWZ87kXssXxnoLQudB4JfkiH8TnY3B",
    link: "/Halaman/page/5-ternak-uang/22/16",
    category: "Stock and Finance",
  },
  {
    id: "17",
    title: "Page Break Preview Orientation Freeze Panes",
    drive: "https://drive.google.com/file/d/1H8MGVwgwCzfVKctFn8C0okUM54x1hQLv",
    link: "/Halaman/page/5-ternak-uang/22/17",
    category: "Stock and Finance",
  },
  {
    id: "18",
    title: "Paste Special Format Numbers Subtotals",
    drive: "https://drive.google.com/file/d/1_nWWbKJlrdaZfQCDzjwTueyw-l-79Qfl",
    link: "/Halaman/page/5-ternak-uang/22/18",
    category: "Stock and Finance",
  },
  {
    id: "19",
    title: "Font Colors with Paste Special",
    drive: "https://drive.google.com/file/d/1f_FRSqdHbumBwSt1hf59ShjZxmV5ORfm",
    link: "/Halaman/page/5-ternak-uang/22/19",
    category: "Stock and Finance",
  },
  {
    id: "20",
    title: "Assumptions Percentages Decimal Places",
    drive: "https://drive.google.com/file/d/1lJaVMHiNlcpNHYmfFJK0fTXl_-zP3YfG",
    link: "/Halaman/page/5-ternak-uang/22/20",
    category: "Stock and Finance",
  },
  {
    id: "21",
    title: "Fill Right Borders View Gridlines",
    drive: "https://drive.google.com/file/d/1_8WRviqQ3SdE9gfr6E0fUVptD5stJA1x",
    link: "/Halaman/page/5-ternak-uang/22/21",
    category: "Stock and Finance",
  },
  {
    id: "22",
    title: "Overview",
    drive: "https://drive.google.com/file/d/10dLWZ38de1BUUejkUAay7G9yK3JGHcBI",
    link: "/Halaman/page/5-ternak-uang/22/22",
    category: "Stock and Finance",
  },
  {
    id: "23",
    title: "Structure Organization Duplicate Sheets Grouping",
    drive: "https://drive.google.com/file/d/1ZscMyKkB-Ogl2Ria2MV-EthK6b0c1Zq2",
    link: "/Halaman/page/5-ternak-uang/22/23",
    category: "Stock and Finance",
  },
  {
    id: "24",
    title: "Anchoring Formatting and Grouping Cells",
    drive: "https://drive.google.com/file/d/1B94E3opZcYvHV9KC6B0e6RbiIdXZlWDa",
    link: "/Halaman/page/5-ternak-uang/22/24",
    category: "Stock and Finance",
  },
  {
    id: "25",
    title: "Naming Cells",
    drive: "https://drive.google.com/file/d/19myFWdQWWzxFUbnlg3K8txS-c_6Jwyc2",
    link: "/Halaman/page/5-ternak-uang/22/25",
    category: "Stock and Finance",
  },
  {
    id: "26",
    title: "Tracing Precedents and Dependents",
    drive: "https://drive.google.com/file/d/1g5FVB6aPxn2M1eAZmTXD6eMi6hcRvoJa",
    link: "/Halaman/page/5-ternak-uang/22/26",
    category: "Stock and Finance",
  },
  {
    id: "27",
    title: "Go to Special Conditional Formatting",
    drive: "https://drive.google.com/file/d/1vPRjF7VdiqamhAyh7k6G62Q_zpunJdxG",
    link: "/Halaman/page/5-ternak-uang/22/27",
    category: "Stock and Finance",
  },
  {
    id: "28",
    title: "Dynamic Titles and Headers",
    drive: "https://drive.google.com/file/d/1z6lIX6i7fCu5H0HhDaHqTrKVvj39l6-1",
    link: "/Halaman/page/5-ternak-uang/22/28",
    category: "Stock and Finance",
  },
  {
    id: "29",
    title: "Overview",
    drive: "https://drive.google.com/file/d/137t8wlac7U1i9S1J0FyXEu5_LQ2Q1CX8",
    link: "/Halaman/page/5-ternak-uang/22/29",
    category: "Stock and Finance",
  },
  {
    id: "30",
    title: "Date Functions and Time Periods",
    drive: "https://drive.google.com/file/d/1wKw1Piuk1HBl6djSau0m9Bh_fsFXMzvD",
    link: "/Halaman/page/5-ternak-uang/22/30",
    category: "Stock and Finance",
  },
  {
    id: "31",
    title: "Yearfrac Function",
    drive: "https://drive.google.com/file/d/1Ayp307IT1uhLiMKymyoUj6INcEdyt1Wi",
    link: "/Halaman/page/5-ternak-uang/22/31",
    category: "Stock and Finance",
  },
  {
    id: "32",
    title: "SUM AVERAGE SUMPRODUCT MEDIAN",
    drive: "https://drive.google.com/file/d/1_5DQdpXBsL1PUWICHbk4RmeA1bMs9bRE",
    link: "/Halaman/page/5-ternak-uang/22/32",
    category: "Stock and Finance",
  },
  {
    id: "33",
    title: "IF STATEMENTS",
    drive: "https://drive.google.com/file/d/1OSlkY8j83s2-tmhWbE8PelxuKEsvrwlH",
    link: "/Halaman/page/5-ternak-uang/22/33",
    category: "Stock and Finance",
  },
  {
    id: "34",
    title: "Rounding and Absolute Functions",
    drive: "https://drive.google.com/file/d/1aBef9LjIFFz2WA314wUTYS-GEE1-GSg-",
    link: "/Halaman/page/5-ternak-uang/22/34",
    category: "Stock and Finance",
  },
  {
    id: "35",
    title: "MIN MAX SMALL LARGE Functions",
    drive: "https://drive.google.com/file/d/15aCu7HPwYrDx7MHnUxY_c6kAC-seThzg",
    link: "/Halaman/page/5-ternak-uang/22/35",
    category: "Stock and Finance",
  },
  {
    id: "36",
    title: "IFERROR Function",
    drive: "https://drive.google.com/file/d/1_Gb29g7bENuzGppHUGrOcNokEH4bNhrG",
    link: "/Halaman/page/5-ternak-uang/22/36",
    category: "Stock and Finance",
  },
  {
    id: "37",
    title: "Find and Replace",
    drive: "https://drive.google.com/file/d/1ONzzN7SUY1i9f92f1YgcOa27S1s8cP9D",
    link: "/Halaman/page/5-ternak-uang/22/37",
    category: "Stock and Finance",
  },
  {
    id: "38",
    title: "Rangkuman",
    drive: "https://drive.google.com/file/d/1bWDtWqH4_YwF7wD_f-EO1ekOvTYns_Tv",
    link: "/Halaman/page/5-ternak-uang/22/38",
    category: "Stock and Finance",
  },
];