export const Data = [
  {
    id: "1",
    title: "Traditional vs Behavioral Finance",
    drive: "https://drive.google.com/file/d/1hLpVDcZc4aCyVQFqtWV7RVJM5QY6waF6",
    link: "/Halaman/page/5-ternak-uang/21/1",
    category: "Stock and Finance",
  },
  {
    id: "2",
    title: "Apa Itu Bias Investor",
    drive: "https://drive.google.com/file/d/1hMvv2nK1_AdokFaRjyYf1JrnWu4zI2lK",
    link: "/Halaman/page/5-ternak-uang/21/2",
    category: "Stock and Finance",
  },
  {
    id: "3",
    title: "Bagaimana Bias Bisa Mempengaruhi Keputusan Investor",
    drive: "https://drive.google.com/file/d/1eon9MKkcLt3bqPkFQ0rBSc04HP3CL6th",
    link: "/Halaman/page/5-ternak-uang/21/3",
    category: "Stock and Finance",
  },
  {
    id: "4",
    title: "Apa itu Bias Kognitif",
    drive: "https://drive.google.com/file/d/1FXn-6i62gwA8YAi5rptEHxr7_hvRJGZH",
    link: "/Halaman/page/5-ternak-uang/21/4",
    category: "Stock and Finance",
  },
  {
    id: "5",
    title: "Mental Accounting - Hyperbolic Discounting",
    drive: "https://drive.google.com/file/d/1MBne4NMHk_7phTvddfnXwvFjup5XPi5b",
    link: "/Halaman/page/5-ternak-uang/21/5",
    category: "Stock and Finance",
  },
  {
    id: "6",
    title: "Dunning Krueger Effect - Illusion of Control",
    drive: "https://drive.google.com/file/d/1jtkWLa6LOPBtgnIF7vQaI1tZDdV-_uWs",
    link: "/Halaman/page/5-ternak-uang/21/6",
    category: "Stock and Finance",
  },
  {
    id: "7",
    title: "Apa itu Bias Emosional",
    drive: "https://drive.google.com/file/d/1Ryg61_wt1Y04GK69_zQaSRgeIBfY5Yyu",
    link: "/Halaman/page/5-ternak-uang/21/7",
    category: "Stock and Finance",
  },
  {
    id: "8",
    title: "Loss Aversion - Sunk Cost Fallacy",
    drive: "https://drive.google.com/file/d/1JjSsB-1vKAjy0Ly4T88d5hmA8_olI424",
    link: "/Halaman/page/5-ternak-uang/21/8",
    category: "Stock and Finance",
  },
  {
    id: "9",
    title: "Overconfidence - Self Control Bias",
    drive: "https://drive.google.com/file/d/1K0kjcBTZ2f976Eb1kYyum9mnAJgP1gel",
    link: "/Halaman/page/5-ternak-uang/21/9",
    category: "Stock and Finance",
  },
  {
    id: "10",
    title: "Regret Aversion Bias - Herd Mentality",
    drive: "https://drive.google.com/file/d/1lHekxkUPb5fUctkfGFl9UdkDXJjpfDW9",
    link: "/Halaman/page/5-ternak-uang/21/10",
    category: "Stock and Finance",
  },
  {
    id: "11",
    title: "Apa yang harus dilakukan Investor",
    drive: "https://drive.google.com/file/d/1gPjh4W5gdwfu3l-_AHS4vYmKcHqMNNS3",
    link: "/Halaman/page/5-ternak-uang/21/11",
    category: "Stock and Finance",
  },
];