export const Data = [
  {
    id: "1",
    title: "Big Crypto Thesis",
    drive: "https://drive.google.com/file/d/1h4whupHDhFwlsvCpjHfzw0rUdRNmKpjt",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/1-Big-Crypto-Thesis",
    category: "Crypto Investing",
  },
  {
    id: "2",
    title: "Bitcoin a Ponzi Scheme",
    drive: "https://drive.google.com/file/d/1MJj_2n5kYMCba9M93tJPl2brTvxG3uQy",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/2-Bitcoin-a-Ponzi-Scheme",
    category: "Crypto Investing",
  },
  {
    id: "3",
    title: "Crypto Basics",
    drive: "https://drive.google.com/file/d/14Tt6Ck85iLonsYsfwdAvxWrBKQHacgv5",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/3-Crypto-Basics",
    category: "Crypto Investing",
  },
  {
    id: "4",
    title: "Mindset Crypto Gambler Mentality",
    drive: "https://drive.google.com/file/d/1NDMoboAwtRcXHyVP919qXhgdBA4PiNdy",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/4-Mindset-Crypto-Gambler-Mentality",
    category: "Crypto Investing",
  },
  {
    id: "5",
    title: "Market Cycles",
    drive: "https://drive.google.com/file/d/1W9KpA0lP0wXEj9Uuxaqhdey1bTOSMD-W",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/5-Market-Cycles",
    category: "Crypto Investing",
  },
  {
    id: "6",
    title: "Types of Cryptocurrencies",
    drive: "https://drive.google.com/file/d/16NWYXB8nX7aixL6Gj5qpb_VlH_33isZ7",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/6-Types-of-Cryptocurrencies",
    category: "Crypto Investing",
  },
  {
    id: "7",
    title: "Attention Economy in Crypto",
    drive: "https://drive.google.com/file/d/1WDZL9-wY03T-e02fyvGWcCkRHHouC0Tc",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/7-Attention-Economy-in-Crypto",
    category: "Crypto Investing",
  },
  {
    id: "8",
    title: "How to Research Crypto",
    drive: "https://drive.google.com/file/d/12WVN7jFrQdm-pCAcvixYZfADgOzFdTa5",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/8-How-to-Research-Crypto",
    category: "Crypto Investing",
  },
  {
    id: "9",
    title: "Risk and Portfolio Management",
    drive: "https://drive.google.com/file/d/1w5CbOKs1iLDBq4uwfseG21p5f_hX_i6n",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/9-Risk-and-Portfolio-Management",
    category: "Crypto Investing",
  },
  {
    id: "10",
    title: "NFT Fundamentals",
    drive: "https://drive.google.com/file/d/1o1Q_vFRE-0tT1u9xy1PpaccV5XkmLWUJ",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/10-NFT-Fundamentals",
    category: "Crypto Investing",
  },
  {
    id: "11",
    title: "Trade Probabilistic Thinking",
    drive: "https://drive.google.com/file/d/131ACUUhpMOYS_TowvjIybX7bnL6eBHpj",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/11-Trade-Probablistic-Thinking",
    category: "Crypto Investing",
  },
  {
    id: "12",
    title: "Bitcoin and Altcoin Correlation",
    drive: "https://drive.google.com/file/d/1NOC9fmfOtOTU4IZp4toIgcscAeJZteJg",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/12-Bitcoin-and-Altcoin-Correlation",
    category: "Crypto Investing",
  },
  {
    id: "13",
    title: "Crypto Tools",
    drive: "https://drive.google.com/file/d/1S6dh-_wg3osqSdLOS9vjsJ0_CxqRKpDY",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/13-Crypto-Tools",
    category: "Crypto Investing",
  },
  {
    id: "14",
    title: "Smart Money in Crypto",
    drive: "https://drive.google.com/file/d/1ykQGQ1H_xqnUT_vqNHeg3o5HQBoA5Yil",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/14-Smart-Money-in-Crypto",
    category: "Crypto Investing",
  },
  {
    id: "15",
    title: "Portfolio Strategy 2023 Cheat Sheet",
    drive: "https://drive.google.com/file/d/1oGpF3wHCmMDrxIjvOxtqi7w6Pmb0OWOz",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/15-Portofolio-Strategy-2023-Cheat-Sheet",
    category: "Crypto Investing",
  },
  {
    id: "16",
    title: "Crypto Staking Strategy",
    drive: "https://drive.google.com/file/d/1_uToeEG8haB4-caulTVVKxrvHcnkYM4S",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/16-Crypto-Staking-Strategy",
    category: "Crypto Investing",
  },
  {
    id: "17",
    title: "Tutorial Exchange",
    drive: "https://drive.google.com/file/d/1RD67fwkixfpXMFZQ6sth6Z53C7GSPfyr",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/17-Tutorial-Exchange",
    category: "Crypto Investing",
  }
];