export const Data = [
  {
    id: "1",
    title: "Big Crypto Thesis",
    drive: "https:/drive.google.com/file/d/1qaOblXCIJvF6pJW6eCds7tFNYgo0ygoN/view?usp=drive_link",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/1-Big-Crypto-Thesis",
    category: "Crypto Investing",
  },
  {
    id: "2",
    title: "Bitcoin a Ponzi Scheme",
    drive: "https:/drive.google.com/file/d/174BcHEkKY_ZBUtigcCiTT73k3kbhuLNn/view?usp=drive_link",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/2-Bitcoin-a-Ponzi-Scheme",
    category: "Crypto Investing",
  },
  {
    id: "3",
    title: "Crypto Basics",
    drive: "https:/drive.google.com/file/d/19iSV3NJDJ4kzP4bCTCnkwMuYoeru2xcC/view?usp=drive_link",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/3-Crypto-Basics",
    category: "Crypto Investing",
  },
  {
    id: "4",
    title: "Mindset Crypto Gambler Mentality",
    drive: "https:/drive.google.com/file/d/1sMeii4M5HSyBn3z9wlEWjhHSRDElLnAM/view?usp=drive_link",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/4-Mindset-Crypto-Gambler-Mentality",
    category: "Crypto Investing",
  },
  {
    id: "5",
    title: "Market Cycles",
    drive: "https:/drive.google.com/file/d/1DeIeknWgfxrnfAFr1Ixs9n8-vklOnOMa/view?usp=drive_link",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/5-Market-Cycles",
    category: "Crypto Investing",
  },
  {
    id: "6",
    title: "Types of Cryptocurrencies",
    drive: "https:/drive.google.com/file/d/16M6_ADq8du45xVbq7IuaYML4qhd4Q_B_/view?usp=drive_link",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/6-Types-of-Cryptocurrencies",
    category: "Crypto Investing",
  },
  {
    id: "7",
    title: "Attention Economy in Crypto",
    drive: "https:/drive.google.com/file/d/1GjmURBE3n6LUPlnKA-wTFwX6xNyomN58/view?usp=drive_link",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/7-Attention-Economy-in-Crypto",
    category: "Crypto Investing",
  },
  {
    id: "8",
    title: "How to Research Crypto",
    drive: "https:/drive.google.com/file/d/1Q6lR9LHk6_OcqUlM_LyKYanuVCHKhGnw/view?usp=drive_link",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/8-How-to-Research-Crypto",
    category: "Crypto Investing",
  },
  {
    id: "9",
    title: "Risk and Portfolio Management",
    drive: "https:/drive.google.com/file/d/1DwMHsOS1I0ShvLb3l7YCELpPe_qDQXWv/view?usp=drive_link",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/9-Risk-and-Portfolio-Management",
    category: "Crypto Investing",
  },
  {
    id: "10",
    title: "NFT Fundamentals",
    drive: "https:/drive.google.com/file/d/1_uyYVqiL5arIZ_ZAZQyAyiIYaJGo7IO-/view?usp=drive_link",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/10-NFT-Fundamentals",
    category: "Crypto Investing",
  },
  {
    id: "11",
    title: "Trade Probabilistic Thinking",
    drive: "https:/drive.google.com/file/d/15adBmJQjl-Sgl_Xro-98Jk7YOacbzYDw/view?usp=drive_link",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/11-Trade-Probablistic-Thinking",
    category: "Crypto Investing",
  },
  {
    id: "12",
    title: "Bitcoin and Altcoin Correlation",
    drive: "https:/drive.google.com/file/d/1Nj6t22fwzX3D4M9N2BOV89rth7ZQGRRW/view?usp=drive_link",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/12-Bitcoin-and-Altcoin-Correlation",
    category: "Crypto Investing",
  },
  {
    id: "13",
    title: "Crypto Tools",
    drive: "https:/drive.google.com/file/d/1WcztAihaO_N_Jonf9e9mRUiTDvfWUezq/view?usp=drive_link",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/13-Crypto-Tools",
    category: "Crypto Investing",
  },
  {
    id: "14",
    title: "Smart Money in Crypto",
    drive: "https:/drive.google.com/file/d/1VyhX3jgXlLkUhypCNe5coTUBVBKjCwDB/view?usp=drive_link",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/14-Smart-Money-in-Crypto",
    category: "Crypto Investing",
  },
  {
    id: "15",
    title: "Portfolio Strategy 2023 Cheat Sheet",
    drive: "https:/drive.google.com/file/d/15j2_aQHzhwxs0a74F8cOpLR2-m2f24jG/view?usp=drive_link",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/15-Portofolio-Strategy-2023-Cheat-Sheet",
    category: "Crypto Investing",
  },
  {
    id: "16",
    title: "Crypto Staking Strategy",
    drive: "https:/drive.google.com/file/d/1uBCVjB83dSbDUq3pLK391jvnCRBqd_1l/view?usp=drive_link",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/16-Crypto-Staking-Strategy",
    category: "Crypto Investing",
  },
  {
    id: "17",
    title: "Tutorial Exchange",
    drive: "https:/drive.google.com/file/d/1RCgeSQO-01km4boxi-98BhM6V8CpLkQ5/view?usp=drive_link",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/17-Tutorial-Exchange",
    category: "Crypto Investing",
  }
];