export const Data = [
  {
    id: "1",
    title: "Big Crypto Thesis",
    drive: "https://drive.google.com/file/d/1Gmoycv8OkXwl-pGcITAeuJZHtZwTak1e/view?usp=drive_link",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/1-Big-Crypto-Thesis",
    category: "Crypto Investing",
  },
  {
    id: "2",
    title: "Bitcoin a Ponzi Scheme",
    drive: "https://drive.google.com/file/d/1GrY7i4Fmsi5_CgYbQJ6KrtOWYKQSV25N/view?usp=drive_link",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/2-Bitcoin-a-Ponzi-Scheme",
    category: "Crypto Investing",
  },
  {
    id: "3",
    title: "Crypto Basics",
    drive: "https://drive.google.com/file/d/1H4b1xOcGDfN2RjWvbalLbC5PY63KH2a4/view?usp=drive_link",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/3-Crypto-Basics",
    category: "Crypto Investing",
  },
  {
    id: "4",
    title: "Mindset Crypto Gambler Mentality",
    drive: "https://drive.google.com/file/d/1HAoBGxNtoOoQC_yZe3UNDDsFAdMS1vIq/view?usp=drive_link",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/4-Mindset-Crypto-Gambler-Mentality",
    category: "Crypto Investing",
  },
  {
    id: "5",
    title: "Market Cycles",
    drive: "https://drive.google.com/file/d/1H2B3ndGHLlFHaXS81-5AbIDb4S2s4RO6/view?usp=drive_link",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/5-Market-Cycles",
    category: "Crypto Investing",
  },
  {
    id: "6",
    title: "Types of Cryptocurrencies",
    drive: "https://drive.google.com/file/d/1H7xSjTQLGlJ3EWdNE4Bx9ips7mB_dooR/view?usp=drive_link",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/6-Types-of-Cryptocurrencies",
    category: "Crypto Investing",
  },
  {
    id: "7",
    title: "Attention Economy in Crypto",
    drive: "https://drive.google.com/file/d/1HM46dkBRx_VNRepjez5PXXovPGagZ4oD/view?usp=drive_link",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/7-Attention-Economy-in-Crypto",
    category: "Crypto Investing",
  },
  {
    id: "8",
    title: "How to Research Crypto",
    drive: "https://drive.google.com/file/d/1HNrafsdNY_t2-I_EmhRkqtbqHDzXnOZ2/view?usp=drive_link",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/8-How-to-Research-Crypto",
    category: "Crypto Investing",
  },
  {
    id: "9",
    title: "Risk and Portfolio Management",
    drive: "https://drive.google.com/file/d/1HfyYJb2jkgdXXG6RQdjt0IbnnyyD3OFj/view?usp=drive_link",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/9-Risk-and-Portfolio-Management",
    category: "Crypto Investing",
  },
  {
    id: "10",
    title: "NFT Fundamentals",
    drive: "https://drive.google.com/file/d/1Hn8WN4mzr9m9b5bVRYynsKkcntUzZhcy/view?usp=drive_link",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/10-NFT-Fundamentals",
    category: "Crypto Investing",
  },
  {
    id: "11",
    title: "Trade Probabilistic Thinking",
    drive: "https://drive.google.com/file/d/1HsaMzAIx8_ezYxuXpytyu95MGUh--tcE/view?usp=drive_link",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/11-Trade-Probablistic-Thinking",
    category: "Crypto Investing",
  },
  {
    id: "12",
    title: "Bitcoin and Altcoin Correlation",
    drive: "https://drive.google.com/file/d/1GnXJ_0RzXxCDSdrAPYegcQH1EaCVPoiF/view?usp=drive_link",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/12-Bitcoin-and-Altcoin-Correlation",
    category: "Crypto Investing",
  },
  {
    id: "13",
    title: "Crypto Tools",
    drive: "https://drive.google.com/file/d/1HtBWUa-8Z0S1Z_69-xdk8exFOezU6C-u/view?usp=drive_link",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/13-Crypto-Tools",
    category: "Crypto Investing",
  },
  {
    id: "14",
    title: "Smart Money in Crypto",
    drive: "https://drive.google.com/file/d/1HrFKue9zRBvKuWAWHYRA5pLWPNhZxtkC/view?usp=drive_link",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/14-Smart-Money-in-Crypto",
    category: "Crypto Investing",
  },
  {
    id: "15",
    title: "Portfolio Strategy 2023 Cheat Sheet",
    drive: "https://drive.google.com/file/d/1HIZ3TOeKO8WDAHSog0njprTV93zvN-ts/view?usp=drive_link",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/15-Portofolio-Strategy-2023-Cheat-Sheet",
    category: "Crypto Investing",
  },
  {
    id: "16",
    title: "Crypto Staking Strategy",
    drive: "https://drive.google.com/file/d/1HtoPKWQEuQP5BfXVG_8ja7MTvoliLarc/view?usp=drive_link",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/16-Crypto-Staking-Strategy",
    category: "Crypto Investing",
  },
  {
    id: "17",
    title: "Tutorial Exchange",
    drive: "https://drive.google.com/file/d/1I-G6QrPxmQ93J8Cd0hlSaU1QE0SPEkFu/view?usp=drive_link",
    link: "/Halaman/page/2-crypto-investing/1-Crypto-Investing/17-Tutorial-Exchange",
    category: "Crypto Investing",
  }
];