export const Data = [
  {
    id: "1",
    title: "1 Smart Contract Security Context",
    drive: "https://drive.google.com/file/d/1Q8upaAqR5ULukerp9LpYp0lv8ytuA1wT",
    link: "/Halaman/page/3-crypto-blockchain/3-Smart-Contract-Security/1-Smart-Contract-Security-Context",
    category: "Crypto Blockchain",
  },
  {
    id: "2",
    title: "2 How to Become a Security Auditor Requirements",
    drive: "https://drive.google.com/file/d/1KdEouvhBe4zasZFaMio13DWwWAfyfY9M",
    link: "/Halaman/page/3-crypto-blockchain/3-Smart-Contract-Security/2-How-to-Become-a-Security-Auditor-Requirements",
    category: "Crypto Blockchain",
  },
  {
    id: "3",
    title: "3 How to Become a Security Auditor Experience",
    drive: "https://drive.google.com/file/d/1N-L9K_N31u5caIvbWvuk-sELAk0JX8Ol",
    link: "/Halaman/page/3-crypto-blockchain/3-Smart-Contract-Security/3-How-to-Become-a-Security-Auditor-Experience",
    category: "Crypto Blockchain",
  },
  {
    id: "4",
    title: "4 How to Become a Security Auditor Risks",
    drive: "https://drive.google.com/file/d/1O5O5ZrFovmIiTZfc1L0lFpx57DdYODqd",
    link: "/Halaman/page/3-crypto-blockchain/3-Smart-Contract-Security/4-How-to-Become-a-Security-Auditor-Risks",
    category: "Crypto Blockchain",
  },
  {
    id: "5",
    title: "5 Smart Contract Security Overview",
    drive: "https://drive.google.com/file/d/1DH21eJCUnPDnC4lIxVDf58duV1kcr-nQ",
    link: "/Halaman/page/3-crypto-blockchain/3-Smart-Contract-Security/5-Smart-Contract-Security-Overview",
    category: "Crypto Blockchain",
  },
  {
    id: "6",
    title: "6 What is Smart Contract Security",
    drive: "https://drive.google.com/file/d/1y-ZUIMm9VwoBvUS2b9LuglA4lWODYYcv",
    link: "/Halaman/page/3-crypto-blockchain/3-Smart-Contract-Security/6-What-is-Smart-Contract-Security",
    category: "Crypto Blockchain",
  },
  {
    id: "7",
    title: "7 Security Auditing Process",
    drive: "https://drive.google.com/file/d/1sBf2emLl_Xa2faGhysZHSN2na9rVIwRm",
    link: "/Halaman/page/3-crypto-blockchain/3-Smart-Contract-Security/7-Security-Auditing-Process",
    category: "Crypto Blockchain",
  },
  {
    id: "8",
    title: "8 Tools and Techniques",
    drive: "https://drive.google.com/file/d/1MS3sjAo5mMHGlraQu3h_suKn1CfjuFpC",
    link: "/Halaman/page/3-crypto-blockchain/3-Smart-Contract-Security/8-Tools-and-Techniques",
    category: "Crypto Blockchain",
  },
  {
    id: "9",
    title: "9 Security Challenges Part 1",
    drive: "https://drive.google.com/file/d/1gqkHfe5aDa752mzPppa9Lip2mw1Y8MmY",
    link: "/Halaman/page/3-crypto-blockchain/3-Smart-Contract-Security/9-Security-Challenges-Part-1",
    category: "Crypto Blockchain",
  },
  {
    id: "10",
    title: "10 Security Challenges Part 2",
    drive: "https://drive.google.com/file/d/1JWHw4neUycS-5Q4ZSiftL4dK3eDXYykI",
    link: "/Halaman/page/3-crypto-blockchain/3-Smart-Contract-Security/10-Security-Challenges-Part-2",
    category: "Crypto Blockchain",
  }
];